homeassistant:
  name: Vas & Squrriels Castle
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: imperial
  time_zone: America/Chicago
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24


####Zone files
zone: !include zones.yaml

map:
http:
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
   base_url: !secret http_base_url
   ip_ban_enabled: True
   login_attempts_threshold: 5

sun:

sensor: !include sensors.yaml

#group: !include tabs.yaml

mqtt:
  broker: 192.168.1.153
  port: 1883
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  will_message:
    topic: 'arduino/small_tank/status'
    payload: 'offline'

mqtt_eventstream:
  publish_topic: master/topic
  subscribe_topic: slaves/#
  ignore_event:
    - call_service
    - state_changed


intent_script: !include intent_scripts.yaml
alexa:

script: !include scripts.yaml

automation old: !include automations old.yaml

hue:
  bridges:
    - host: 192.168.1.185
      allow_unreachable: True

scene: !include scenes.yaml

rest_command: !include restcommands.yaml

config:

wink:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

xiaomi_aqara:
  gateways:
     - mac: !secret xiaomi_mac
       key: !secret xiaomi_key
       host: 192.168.1.11
     - mac: !secret xiaomi_mac_2
       key: !secret xiaomi_key_2
       host: 192.168.1.178
input_label:
  some_string1:
    name: Some String 1
    icon: mdi:alphabetical
  input_label:
    name: Some String 2
    value: 'Hello, Home Assistant!'
    icon: mdi:alphabetical

system_health:

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

discovery:
stream:
