homeassistant:
  name: Vas & Squrriels Castle
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include Customize.yaml
  packages: !include_dir_named packages

####Zone files
zone: !include zones.yaml

# Enables the frontend
#frontend:
map:
http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
  # base_url: !secret http_base_url
   use_x_forwarded_for: True
   trusted_networks:
     - 127.0.0.1
     - 192.168.1.0/24
   ip_ban_enabled: True
   login_attempts_threshold: 5

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Track the sun
sun:

# Sensors
sensor: !include Sensors.yaml

group: !include tabs.yaml

mqtt:
  broker: 192.168.1.153
  port: 1883
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

intent_script: !include intent_scripts.yaml
alexa:

script: !include scripts.yaml

automation old: !include automations old.yaml

hue:
  bridges:
    - host: 192.168.1.185
      allow_unreachable: True

scene: !include Scenes.yaml

rest_command: !include restcommands.yaml

config:

wink:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

#discovery:
wemo:
  static:
    - 192.168.1.254  #Driveway Camera
    - 192.168.1.204  #washer
    - 192.168.1.146  #gabbies_lamp
    - 192.168.1.126  #Kids Bathroom Scent
    - 192.168.1.218  #Master Bedroom Network Reboot
    - 192.168.1.230  #Master Bathroom Fan
#    - 192.168.1.171  #Master Bathroom Heat
    - 192.168.1.162  #rear network
