homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'disarm'
    input_boolean.boolean_alarm_bypass:
      friendly_name: Bypass Alarm
      hasska_name: Bypass Alarm

input_boolean:
  boolean_alarm_bypass:
    initial: off

automation:
#################################################
#          Alarm Auto DISARM when RETURN                         #
#################################################
  - alias: 'alarm disarm when return home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.set_hold_mode
        to: 'home'
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
      - service: light.turn_on
        data:
          entity_id: light.kitchen_under_cabinet
          effect: "solid"
          brightness: 255
      # - service: light.turn_off
      #   entity_id: light.kitchen_under_cabinet
      - service: light.turn_off
        entity_id: light.light_bulb
      - service: automation.turn_off
        entity_id: automation.where_is_motion_alarm_triggered

#################################################
#          Alarm Bypass                         #
#################################################
  - alias: 'alarm_bypass'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_alarm_bypass
        to: 'on'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
      - service: light.turn_off
        entity_id: light.light_bulb
      - service: automation.turn_off
        entity_id: automation.where_is_motion_alarm_triggered

  - alias: 'alarm_rearm_after_bypass'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_alarm_bypass
        from: 'on'
        to: 'off'
    action:
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
