homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'alarm_arm_away'



automation:
  - alias: rerun alarm
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'triggered'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'away'
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'triggered'
    action:
      - delay: '00:00:02'
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'You are detected and recorded'
      - service: light.turn_on
        data:
          entity_id: group.all_lights
          flash: short
      - service: light.turn_off
        entity_id: light.light_bulb

#################################################
#             Alarm Auto Arm Away when LEAVE                       #
#################################################
  - alias: 'Alarm Away when Leave home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.set_hold_mode
        to: 'away'
      - platform: state
        entity_id: input_boolean.boolean_away
        to: 'on'
    action:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
