homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'alarm'

group:
  alarm_panel_card:
   name: Alarm
   entities:
     - alarm_control_panel.ha_alarm
     - sensor.blue_iris_profile

##############################################################################
###### see home mode package for setting of the mode house is in      ########
######   ie sleep home or away  (sets cameras thermostat and some lights  ####
##############################################################################
alarm_control_panel:
  - platform: manual
#    code:  # move this to secrets when you have time
    # code: !secret alarm_control_panel_code
    trigger_time: 1
    pending_time: 5

automation:
  - alias: rerun alarm
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'triggered'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'away'
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: 'triggered'
    action:
      - delay: '00:00:02'
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'You are detected and recorded'
      - service: light.turn_on
        data:
          entity_id: group.all_lights
          flash: short
      - service: light.turn_off
        entity_id: light.light_bulb

########################################################
#        Notify of where is motion after alarm is triggered
########################################################
  - alias: 'where_is_motion_alarm_triggered'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_kids_bathroom
        to: 'on'
      - platform: state
        entity_id: binary_sensor.gabbies_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kids_hallway_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_tablet_camera
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_home'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.ha_speaker
          volume_level: '{{ states.input_number.alarm_mode_chromecast_lv.state }}'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.master_bedroom_cast
          volume_level: '{{ states.input_number.alarm_mode_chromecast_masterbedroom.state }}'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: >
            An alarm has been Triggered in the {% if is_state('binary_sensor.motion_sensor_kids_bathroom', 'on') %}
            Kids Bathroom
            {% elif is_state('binary_sensor.binary_sensor.gabbies_room_motion', 'on') %}
            Gabbies Room
            {% elif is_state('binary_sensor.kids_hallway_motion', 'on') %}
            Kids Hallway
            {% elif is_state('binary_sensor.kitchen_motion', 'on') %}
            Kitchen
            {% elif is_state('binary_sensor.hallway_motion', 'on') %}
            Hallway
            {%elif is_state('binary_sensor.bathroom_motion', 'on') %}
            Master Bath
            {%elif is_state('binary_sensor.master_motion', 'on') %}
            Master
            {% elif is_state('binary_sensor.laundry_room_motion', 'on') %}
            Laundry Room
            {% elif is_state('binary_sensor.motion_tablet_camera', 'on') %}
            Living Room
            {% endif %}
      - service: light.turn_on
        data:
          entity_id: group.all_lights
          flash: short
      - service: light.turn_off
        entity_id: light.light_bulb
      - service: notify.Pushbullet
        data:
          message: 'An alarm has been Triggered!'
        data_template:
          message: >
            An alarm has been Triggered in the {% if is_state('binary_sensor.motion_sensor_kids_bathroom', 'on') %}
            Kids Bathroom
            {% elif is_state('binary_sensor.binary_sensor.gabbies_room_motion', 'on') %}
            Gabbies Room
            {% elif is_state('binary_sensor.kids_hallway_motion', 'on') %}
            Kids Hallway
            {% elif is_state('binary_sensor.kitchen_motion', 'on') %}
            Kitchen
            {% elif is_state('binary_sensor.hallway_motion', 'on') %}
            Hallway
            {%elif is_state('binary_sensor.bathroom_motion', 'on') %}
            Master Bath
            {%elif is_state('binary_sensor.master_motion', 'on') %}
            Master
            {% elif is_state('binary_sensor.laundry_room_motion', 'on') %}
            Laundry Room
            {% elif is_state('binary_sensor.motion_tablet_camera', 'on') %}
            Living Room
            {% endif %}


#################################################
# a door opened when armed
#################################################
  - alias: 'Triggers for when armed'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_front_door
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_back_door
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_home'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: >
            The {% if is_state('binary_sensor.door_window_sensor_front_door', 'on') %}
            Front Door Has Been Opened
            {% elif is_state('binary_sensor.door_window_sensor_back_door', 'on') %}
            Back Door Has Been Open
            {% endif %}
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_mac
          ringtone_id: 1
          ringtone_vol: 100
      - service: notify.Pushbullet
        data:
          message: 'An alarm has been Triggered!'
        data_template:
          message: >
             The {% if is_state('binary_sensor.door_window_sensor_front_door', 'on') %}
             Front Door Has Been Opened
             {% elif is_state('binary_sensor.door_window_sensor_back_door', 'on') %}
             Back Door Has Been Open
             {% endif %}
      - service: automation.turn_on
        entity_id: automation.where_is_motion_alarm_triggered

###### booleans on and off for alarms
#################################################
#             Alarm Auto Arm Away when LEAVE                       #
#################################################
  - alias: 'Alarm Away when Leave home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.set_hold_mode
        to: 'away'
      - platform: state
        entity_id: input_boolean.boolean_away
        to: 'on'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.ha_alarm

#################################################
#          Alarm Auto DISARM when RETURN                         #
#################################################
  - alias: 'Alarm disarm when return home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.set_hold_mode
        to: 'home'
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.ha_alarm
      - service: light.turn_off
        entity_id: light.light_bulb
      - service: automation.turn_off
        entity_id: automation.where_is_motion_alarm_triggered

######################################################
#        Alarm auto arm home when house is in sleep
######################################################
  - alias: 'Alarm set armed home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_sleep
        to: 'on'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.ha_alarm
