homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'alarm'

    sensor.motion_count:
      haaska_hidden: true
      icon: mdi:alert
      friendly_name: Motion Counts
      unit_of_measurement: '#'

##############################################################################
###### see home mode package for setting of the mode house is in      ########
######   ie sleep home or away  (sets cameras thermostat and some lights  ####
##############################################################################
alarm_control_panel:
  - platform: manual
    trigger_time: 1
    pending_time: 60
    delay_time: 120
    code: !secret alarm_code
########################################################
#        Notify of where is motion after alarm is triggered
########################################################
automation:
  - alias: 'where_is_motion_alarm_triggered'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_sensor_kids_bathroom
          - binary_sensor.gabbies_room_motion
          - binary_sensor.kids_hallway_motion
          - binary_sensor.laundry_room_motion
          - binary_sensor.kitchen_motion
          - binary_sensor.hallway_motion
          - binary_sensor.bathroom_motion
          - binary_sensor.master_motion
          - binary_sensor.motion_tablet_camera
          - binary_sensor.motion_master_bedroom
          - binary_sensor.motion_frontdoor
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_home'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.ha_speaker
          volume_level: '{{ states.input_number.alarm_mode_chromecast_lv.state }}'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.master_bedroom_cast
          volume_level: '{{ states.input_number.alarm_mode_chromecast_masterbedroom.state }}'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: >
            There is motion in the {{ states[trigger.entity_id.split(".")[0]][ trigger.entity_id.split(".")[1]].name }}
      - service: light.turn_on
        data:
          entity_id: group.all_lights
          flash: short
      - service: light.turn_off
        entity_id: light.light_bulb
      - service: notify.pushbullet
        data:
          message: 'An alarm has been Triggered!'
        data_template:
          message: >
            An alarm has been Triggered in the {{ states[trigger.entity_id.split(".")[0]][ trigger.entity_id.split(".")[1]].name }}

#################################################
# a door opened when armed away/home
#################################################
  - alias: 'Triggers for when armed'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_window_sensor_front_door
          - binary_sensor.door_window_sensor_back_door
          - binary_sensor.door_window_sensor_shed_door
          - binary_sensor.door_window_sensor_gabbies_room
          - binary_sensor.door_window_sensor_ruths_room
          - binary_sensor.door_window_sensor_kitchen_sink
          - binary_sensor.door_window_sensor_kitchen_table
          - binary_sensor.door_window_sensor_dawns_side
          - binary_sensor.door_window_sensor_herbs_side
          - binary_sensor.door_window_sensor_livingroom_front
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_home'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: >
            The {{ states[trigger.entity_id.split(".")[0]][ trigger.entity_id.split(".")[1]].name }} just opened!

      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_mac
          ringtone_id: 1
          ringtone_vol: 100
      - service: light.turn_on
        data:
          entity_id: light.kitchen_under_cabinet
          # effect: solid
          brightness: 255
          effect: "police all"
      - service: notify.pushbullet
        data:
          message: 'An alarm has been Triggered!'
        data_template:
          message: >
            The {{ states[trigger.entity_id.split(".")[0]][ trigger.entity_id.split(".")[1]].name }} just opened!
      - service: automation.turn_on
        entity_id: automation.where_is_motion_alarm_triggered

sensor:
  - platform: template
    sensors:
      motion_count:
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'motion') | list | count }}
