homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'blue_iris'

    binary_sensor.motion_outdoor_shed:
      friendly_name: Shed Camera
      device_class: motion
    binary_sensor.motion_outdoor_driveway:
      friendly_name: Driveway
      device_class: motion
    binary_sensor.motion_outdoor_frontdoor:
      friendly_name: Front Door
      device_class: motion
    binary_sensor.motion_outdoor_number12:
      friendly_name: Number 12
      device_class: motion
    binary_sensor.motion_outdoor_backdoor:
      friendly_name: Back Door
      device_class: motion
    binary_sensor.motion_outdoor_swamp:
      friendly_name: Swamp
      device_class: motion
    binary_sensor.motion_tablet_lv_camera:
      friendly_name: Tablet Camera
      device_class: motion
    binary_sensor.motion_tablet_mb_camera:
      friendly_name: Master Bedroom Camera
      device_class: motion
    binary_sensor.motion_tablet_gb_camera:
      friendly_name: Gabbies Bedroom Camera
      device_class: motion
    automation.flash_red_motion_shed:
      friendly_name: Motion Front Door Outside
      haaska_hidden: true
    automation.flash_blue_motion_backdoor:
      friendly_name: Motion Back Door Outside
      haaska_hidden: true
    automation.white_no_motion:
      friendly_name: White No Motion
      haaska_hidden: true

group:
  blue_iris_motion_card:
   name: Camera Motion
   entities:
     - binary_sensor.motion_outdoor_shed
     - binary_sensor.motion_outdoor_driveway
     - binary_sensor.motion_outdoor_number12
     - binary_sensor.motion_outdoor_swamp
     - binary_sensor.motion_outdoor_frontdoor
     - binary_sensor.motion_outdoor_backdoor
     - binary_sensor.motion_tablet_lv_camera
     - binary_sensor.motion_tablet_mb_camera
     - binary_sensor.motion_tablet_gb_camera

#######################################################################################################################
###### Sets profile on blue iris   ####################################################################################
#######################################################################################################################
sensor:
  - platform: rest
    resource: !secret rest_blue_iris_profile
    value_template: >-
       {% if 'profile=1' in value %}
         No Motion Detection
       {% elif 'profile=5' in value %}
         Lockdown Full Motion Detection
       {% elif 'profile=6' in value %}
         Sleep
       {% endif %}
    name: 'Blue Iris Profile'

#######################################################################################################################
###### Motion sensor templates for blue Iris  #########################################################################
#######################################################################################################################
binary_sensor:
  - platform: mqtt
    state_topic: "blue_iris/driveway_cam/state"
    name: motion_outdoor_driveway
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/swamp_cam/state"
    name: motion_outdoor_swamp
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/shed_cam/state"
    name: motion_outdoor_shed
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/backdoor_cam/state"
    name: motion_outdoor_backdoor
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/frontdoor_cam/state"
    name: motion_outdoor_frontdoor
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/dashboard_lv_cam/state"
    name: motion_tablet_lv_camera
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/dashboard_mb_cam/state"
    name: motion_tablet_mb_camera
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/dashboard_gb_cam/state"
    name: motion_tablet_gb_camera
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/number12_cam/state"
    name: motion_outdoor_number12_camera
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/lv_dash_cam/state"
    name: motion_tablet_lv_camera
    payload_on: "on"
    payload_off: "off"

  - platform: mqtt
    state_topic: "blue_iris/bd_dash_cam/state"
    name: motion_tablet_mb_camera
    payload_on: "on"
    payload_off: "off"

  # - platform: template
  #   sensors:
  #     motion_tablet_camera:
  #       value_template: >-
  #         {% if states('binary_sensor.blueiriscam8') %}
  #         {% if is_state('binary_sensor.blueiriscam8', 'on') %}
  #            True
  #         {% elif is_state('binary_sensor.blueiriscam8', 'off') %}
  #            False
  #         {% else %}
  #         {{ states('binary_sensor.blueiriscam8') }}
  #         {% endif %}
  #         {% else %}
  #           False
  #         {% endif %}


  ######################################################
# Flash Door lamp when motion at shed camera and backdoor
######################################################
automation:
  - alias: flash_red_motion_shed
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_active_outside
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.door_lamp
          flash: short
          color_name: Red
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'Somebody is at Front Door'


  - alias: flash_blue_motion_backdoor
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_backdoor
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_active_outside
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.door_lamp
          flash: short
          color_name: Blue
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'Somebody is at Back Door'


  - alias: white_no_motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed
        to: 'off'
      - platform: state
        entity_id: binary_sensor.motion_outdoor_backdoor
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.door_lamp
          color_temp: 154
          brightness: 255

#############################################################################
############3 rest commands to change blue iris profile               #######
#############################################################################
rest_command:
  no_motion:
    url: !secret rest_command_no_motion
  lock_down:
    url: !secret rest_command_lockdown
  sleep:
    url: !secret rest_command_sleep
