homeassistant:
  customize:
    camera.herb:
      friendly_name: Herb
    camera.dawn:
      friendly_name: Dawn

camera:
  # - platform: generic
  #   still_image_url: http://192.168.1.80:81/image/cam2
  #   stream_source: !secret blue_iris_new_stream
  #   name: test
  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam6/video.mjpeg
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    name: Driveway

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam4/video.mjpeg
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    name: Front Door Camera

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam12/video.mjpeg
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    name: Truck

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam11/video.mjpeg
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    name: Yard Shed

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam13/video.mjpeg
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    name: Park Entrance

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam5/video.mjpeg
    name: Swamp
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam8/video.mjpeg
    name: Tablet Cam
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam3/video.mjpeg
    name: Back Door
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/shed/video.mjpeg
    name: Yard
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam7/video.mjpeg
    name: Master Bedroom Cam
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam1/video.mjpeg
    name: Master Bedroom Tablet Cam
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam9/video.mjpeg
    name: Gabbie Cam
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic

  - platform: mjpeg
    mjpeg_url: http://192.168.1.80:81/mjpg/cam10/video.mjpeg
    name: Kids Room Cam
    username: !secret blue_iris_camera_stream_usrname
    password: !secret blue_iris_camera_stream_pass
    authentication: basic
