homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'BroadLink'

    switch.gabbies_tv_power:
      haaska_name: Gabbies Tv
      icon: mdi:television-box
      friendly_name: Gabbies Tv

switch:
  - platform: broadlink
    host: 192.168.1.160
    mac: '34:EA:34:51:32:E1'
    switches:
      gabbies_tv_power:
        friendly_name: "Gabbies Tv"
        command_on: 'JgBwAAABJ5MTEhM3EjgSEhMSEhMSExI3EzcSExI3ExISExITEhMSExI3EjgSNxI4EhMSEhMSEhMSExITEhITEhI4EjcTNxI4EgAFlQABKEoTAAxZAAEnSxIADFkAASdLEgAMWQABKEoSAAxZAAEoShMADQUAAAAAAAAAAA=='
        command_off: 'JgBwAAABJ5MTEhM3EjgSEhMSEhMSExI3EzcSExI3ExISExITEhMSExI3EjgSNxI4EhMSEhMSEhMSExITEhITEhI4EjcTNxI4EgAFlQABKEoTAAxZAAEnSxIADFkAASdLEgAMWQABKEoSAAxZAAEoShMADQUAAAAAAAAAAA=='
