
circadian_lighting:
  interval: 300
  transition: 180
  sunset_time: '18:02:00'
switch:
######### Normal Family room lighting  #########
  - platform: circadian_lighting
    name: Circadian Lamps
    lights_ct:
      - light.lamps
###############  Evening Lights ################
  - platform: circadian_lighting
    name: Circadian Lamps Evening
    max_brightness: 25
    lights_ct:
      - light.living_room_lamp_1
      - light.living_room_lamp_3
      - light.living_room_lamp_4
      - light.living_room_lamp_2
      - light.living_room_lamp_5

automation:
  - alias: circadian_lighting_evening_mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_evening_time
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_away
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id:  switch.circadian_lighting_circadian_lamps
      - service: switch.turn_on
        entity_id:  switch.circadian_lighting_circadian_lamps_evening

  - alias: circadian_lighting_early_morning_mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
      - platform: state
        entity_id: input_boolean.boolean_early_morning
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_away
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id:  switch.circadian_lighting_circadian_lamps_evening

  - alias: circadian_lighting_home_mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_away
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id:  switch.circadian_lighting_circadian_lamps_evening
      - service: switch.turn_on
        entity_id: switch.circadian_lighting_circadian_lamps

  - alias: circadian_lighting_sleep_mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_sleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.boolean_away
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id:  switch.circadian_lighting_circadian_lamps_evening
      - service: switch.turn_off
        entity_id:  switch.circadian_lighting_circadian_lamps
