homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'ecobee'

    sensor.preset_mode:
      icon: mdi:home
    sensor.hvac_fan:
      haaska_hidden: true
      icon: mdi:fan

##### Config for ecobee
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: True

######  ecobee3 Mode Sensors
sensor:
  - platform: template
    sensors:
      operating_mode:
        friendly_name: 'Current Operation'
        value_template: "{{ state_attr('climate.thermostat' , 'hvac_action') }}"
      preset_mode:
        friendly_name: 'Current Mode'
        value_template: "{{ state_attr('climate.thermostat' , 'preset_mode') }}"
      target_temp:
        friendly_name: 'Target Temperature'
        value_template: "{{ state_attr('climate.thermostat' , 'target_temp_high') }}"
        device_class: temperature
        unit_of_measurement: '°F'
      current_temp:
        friendly_name: 'Current Temperature'
        value_template: "{{ state_attr('climate.thermostat' , 'current_temperature') }}"
        device_class: temperature
        unit_of_measurement: '°F'
      hvac_fan:
        friendly_name: 'Hvac Fan'
        value_template: "{{ state_attr('climate.thermostat' , 'fan') }}"
