homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'harmony'
    sensor.remote_entertainment:
      icon: mdi:theater
      friendly_name: Harmony Remote

remote:
  - platform: harmony
    name: Entertainment
    host: 192.168.1.162

sensor:
  - platform: template
    sensors:
      remote_entertainment:
        value_template: '{{ states.remote.entertainment.attributes.current_activity }}'
        friendly_name: 'Harmony Last Activity'

input_select:
  harmony:
    name: Harmony
    options:
      - Select Input
      - PS4
      - XBOX ONE X
      - Netflix
      - Classical Music
      - Amazon
      - Philo
      - Plex
      - Tablo DVR
      - PowerOff
    icon: mdi:monitor

# Harmony input select Automation
automation:
  - alias: Harmony Input Select Automation
    initial_state: on
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.harmony
        from: 'Select Input'
    action:
      - service: remote.turn_on
        entity_id: remote.entertainment
        data_template:
          activity: >
            {% if is_state("input_select.harmony", "PS4") %}
              25501031
            {% elif is_state("input_select.harmony", "XBOX ONE X") %}
              25486501
            {% elif is_state("input_select.harmony", "Netflix") %}
              25498037
            {% elif is_state("input_select.harmony", "Classical Music") %}
              25501845
            {% elif is_state("input_select.harmony", "Amazon") %}
              27189210
            {% elif is_state("input_select.harmony", "Philo") %}
              32645868
            {% elif is_state("input_select.harmony", "Plex") %}
              34744050
            {% elif is_state("input_select.harmony", "Tablo DVR") %}
              35801439
            {% elif is_state("input_select.harmony", "PowerOff") %}
              -1
            {% else %}
              -1
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"
  - alias: Harmony Off
    initial_state: on
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_select.harmony
        to: 'Power Off'
    action:
      - service: remote.turn_off
        entity_id: remote.entertainment
      - service: input_select.select_option
        entity_id: input_select.harmony
        data_template:
          option: "Select Input"
