homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'media_players'
    media_player.blueiris2:
      friendly_name: Plex

# grouped each media player so that the would show correctly
group:
  entertainment_card:
   name: Entertainment Center
   entities:
#     - remote.entertainment
     - sensor.remote_entertainment
     - input_select.harmony
     - sensor.onkyo_source
     - input_select.onkyo
     - input_number.onkyo_volume
     - sensor.roku_living_room_source
     - input_select.roku_living_room_source

  Samsung_tv_media_player_card:
   name: Samsung
   entities:
     - media_player.smart_tv


  media_player_networkpc_card:
    name: Plex
    entities:
      - media_player.networkpc

  media_player_plex_server_card:
    name: Plex Server
    entities:
      - media_player.plex_server_living_room

  media_player_kodi_card:
    name: Kids Room Kodi
    entities:
      - media_player.kodi



######### Cast Devices #################

  media_player_master_bedroom_cast_card:
    name: Master Bedroom Cast
    entities:
      - media_player.master_bedroom_cast
  media_player_onkyo_cast_card:
    name: Onkyo Cast
    entities:
      -  media_player.onkyo_cast
  media_player_ha_speaker_card:
   name: Ha TTS Speaker Cast
   entities:
     - media_player.ha_speaker
  media_player_kids_room_card:
   name: Kids Room Cast
   entities:
     - media_player.kids_room_cast
  media_player_home_group:
    name: Home Group Cast
    entities:
      - media_player.home_group
  media_player_whole_house:
    name: Whole House Cast
    entities:
      - media_player.kids_room_cast
      - media_player.master_bedroom_cast
      - media_player.onkyo_cast

  sensor_plex:
    name: Plex Players
    entities:
      - sensor.plex


media_player:
  - platform: samsungtv
    host: 192.168.1.14
    port: 8001
    name: Smart Tv
  - platform: kodi
    host: 192.168.1.149
    username: !secret media_player_kodi_username
    password: !secret media_player_kodi_password


# cast:
#   media_player:
#   - host: 192.168.1.173
#   - host: 192.168.1.32

sensor:
  - platform: plex
    host: 192.168.1.80
    token: !secret plex_token
