homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'media_players'
    media_player.blueiris2:
      friendly_name: Plex

# grouped each media player so that the would show correctly

media_player:
  - platform: samsungtv
    host: 192.168.1.82
    port: 8001
    name: Smart Tv

# sensor:
#   - platform: plex
#     host: 192.168.1.80
#     token: !secret plex_token
