homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'digital_loggers'

    switch.network_switch_charter_modem:
      friendly_name: Charter Modem
      icon: mdi:ethernet-cable
    switch.network_switch_unifi_router:
      friendly_name: UniFi Router
      icon: mdi:security-network
    switch.network_switch_unifi_switch:
      friendly_name: UniFi Poe Managed Switch
      icon: mdi:switch
    switch.network_switch_blue_iris_server:
      friendly_name: Blue Iris Server
      icon: mdi:server-network
    switch.network_switch_blue_iris_monitor:
      friendly_name: Blue Iris Monitor
      icon: mdi:monitor
    switch.network_switch_home_assistant_server:
      friendly_name: HASS Server
      icon: mdi:server-network
    switch.network_switch_pi_falcon_player:
      friendly_name: Falcon Player
      icon: mdi:server-network

switch:
  - platform: digitalloggers
    host: 192.168.1.40
    password: !secret digital_loggers_pass
    name: Network Switch
    cycletime: 5
