homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Window Sensors'


    binary_sensor.door_window_sensor_kitchen_sink:
      haaska_hidden: true
      friendly_name: Kitchen Sink Window Sensor
      device_class: window
    sensor.kitchen_sink_window_sensor_batt:
      haaska_hidden: true
      friendly_name: Kitchen Sink Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_kitchen_table:
      haaska_hidden: true
      friendly_name: Kitchen Table Window Sensor
      device_class: window
    sensor.kitchen_table_window_sensor_batt:
      haaska_hidden: true
      friendly_name: Kitchen Table Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_dawns_side:
      haaska_hidden: true
      friendly_name: Dawns Side Window Sensor
      device_class: window
    sensor.dawns_side_window_sensor_batt:
      haaska_hidden: true
      friendly_name: Dawns Side Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_herbs_side:
      haaska_hidden: true
      friendly_name: Herbs Side Window Sensor
      device_class: window
    sensor.herbs_side_window_sensor_batt:
      haaska_hidden: true
      friendly_name: Herbs Side Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    sensor.open_window_count:
      haaska_hidden: true
      friendly_name: Open Window Count
      icon: mdi:window-open
      unit_of_measurement: '#'


sensor:
############################### kids room ###############################################################
  - platform: template
    sensors:
      kitchen_sink_window_sensor_batt:
        friendly_name: 'kitchen_sink_window_sensor_batt'
        value_template: "{{ states.binary_sensor.door_window_sensor_kitchen_sink.attributes.battery_level }}"



  - platform: template
    sensors:
      kitchen_table_window_sensor_batt:
        friendly_name: 'Kitchen Table Window Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_kitchen_table.attributes.battery_level }}"
  - platform: template
    sensors:
      dawns_side_window_sensor_batt:
        friendly_name: 'Dawns Side Window Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_dawns_side.attributes.battery_level }}"
  - platform: template
    sensors:
      herbs_side_window_sensor_batt:
        friendly_name: 'Herbs Side Window Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_herbs_side.attributes.battery_level }}"



  - platform: template
    sensors:
      open_window_count:
        entity_id: sensor.time
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | list | count }}
