homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'BroadLink'

smartir:
  update_branch: rc

switch:
  - platform: broadlink
    host: 192.168.1.160
    mac: '34:EA:34:51:32:E1'
  - platform: broadlink
    host: 192.168.1.161
    mac: '34:EA:34:CC:C8:AA'
    switches:
      heater_lasko_power:
        friendly_name: "Bathroom Heater Power"
        command_on: 'JgBqAAABO5cSQxMVEhQTFhIVExQSQxMVERUSFxEWEhUTEhUVERcRFhEWEkMSFRIVEkMUFRFDE0ITFRIWERYSFRIVExQSFRMWERURFxIUFBQSFhIWERYSFRJCFEISFRMWD0UTQhIWEUQ5HRMADQUAAAAAAAAAAAAAAAAAAA=='
        command_off: 'JgBqAAABOZgTFRIVEhUUFBMUEhYRRBMVERUTFREWExQSFRQVEBcRFhIVEkMTFRIWEUMUFBJCE0QRFhJDFRIUExNDEkQRRBRBEhQUFBIWEhYRFhIWERUTFRFDFBURGBBDEkIUQhIVExU6GxMADQUAAAAAAAAAAAAAAAAAAA=='
      heater_lasko_oscillate:
        friendly_name: "Bathroom Heater Oscillate"
        command_on: 'JgBqAAABO5cSQxRBExQUFBIVFBQSQxQUEhQUFBIVExUSFRQUEhQUFBIVE0MSFRMUE0IUFBJDFEISQhQUExUTFBIVExURQxVBExQTFRIVExUSFRQTFBMTQxJDFBQSFBRCEhUTFRIVFEE6GxQADQUAAAAAAAAAAAAAAAAAAA=='
        command_off: 'JgBqAAABO5cTQhMVEhUUFBIVExQTQhUTEhUTFRIVExQTFBMVEhUTFRIVFEETFBQUEkMTFRJCFUETFBMVEhUTFBNCFUESQxQUEhUTFBMUFBQSFRQUEkMTFBNCFEISFRNCE0IUQhIVE0M5GxUADQUAAAAAAAAAAAAAAAAAAA=='

media_player:
  - platform: smartir
    name: Kids Room TV
    unique_id: kids_room_tv
    device_code: 1000
    controller_data: 192.168.1.160
#    controller_send_service: switch.broadlink_send_packet_192_168_1_160
    power_sensor: binary_sensor.kids_tv_on

binary_sensor:
  - platform: template
    sensors:
      kids_tv_on:
        friendly_name: "Kids Tv Is On"
        value_template: >-
          {{ state_attr('switch.wemo_kids_tv_power', 'state_detail') == 'on' }}
