homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'main_ups'
    automation.commerical_power_back_up:
      friendly_name: Power Up Automation
      haaska_hidden: true
    automation.commerical_power_down_nofication:
      friendly_name: Power Out Notify
      haaska_hidden: true
    automation.commerical_power_up_nofication:
      friendly_name: Power Up Notify
      haaska_hidden: true

apcupsd:

sensor:
  - platform: apcupsd
    resources:
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - nompower
      - tonbatt



automation:

  - alias: 'commerical_power_down_nofication'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        to: 'ONBATT'
        from: 'ONLINE'
        for: '00:05:00'
    action:
      - service: notify.pushbullet
        data:
          message: 'Power is out'

  - alias: 'commerical_power_up_nofication'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        to: 'ONLINE'
        from: 'ONBATT'
        for: '00:05:00'
    action:
      - service: notify.pushbullet
        data:
          message: 'Power is up'

############# power up after power outage #####################################
  - alias: 'commerical_power_back_up'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        from: 'ONBATT'
        to: 'ONLINE'
        for: '00:10:00'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.wemo_unifi_shed_switch
          - switch.wemo_unifi_shed_switch
          - switch.wemo_8port_livingroom
          - switch.wemo_driveway_camaera
          - switch.wemo_washing_machine
          - switch.wemo_master_bedroom_mixer
      - service: fan.turn_on
        entity_id:
          - fan.living_room_purifer
          - fan.master_bedroom_purifer
          - fan.kids_bedroom_purifer
