homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Door Sensors'
    binary_sensor.door_window_sensor_master_bedroom_door:
      haaska_hidden: true
      friendly_name: Master Bedroom Door
      device_class: door
    sensor.master_door_sensor_batt:
      haaska_hidden: true
      friendly_name: Master Door Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_master_bath_door:
      haaska_hidden: true
      friendly_name: Master Bath Door
      device_class: door
    sensor.master_bath_sensor_batt:
      haaska_hidden: true
      friendly_name: Master Bath Door Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery

    sensor.open_door_count:
      haaska_hidden: true
      friendly_name: Open Door Count
      icon: mdi:door-open
      unit_of_measurement: '#'

sensor:
  - platform: template
    sensors:
      master_door_sensor_batt:
        friendly_name: 'Back Door Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_master_bedroom_door.attributes.battery_level }}"
  - platform: template
    sensors:
      master_bath_sensor_batt:
        friendly_name: 'Master Bath Door Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_master_bath_door.attributes.battery_level }}"



###### counter for open doors ###################
  - platform: template
    sensors:
      open_door_count:
        entity_id: sensor.time
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | list | count }}
