homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Led strips'

    light.kitchen_under_cabinet:
      friendly_name: Kitchen Under Cabinets
      haaska_hidden: false
    light.kitchen_pantry:
      friendly_name: Pantry Lights
      haaska_hidden: true
    light.john_deere_bookshelf:
      friendly_name: John Deere Bookshelf
      haaska_hidden: true
    light.spice_cabinet:
      friendly_name: Spice Cabinet
      haaska_hidden: true
    input_number.led_animation_speed:
      friendly_name: Kitchen Cabinets Speed
      haaska_hidden: true
    script.led_white:
      friendly_name: Kitchen Led White
      haaska_hidden: false
    script.led_yellow:
      friendly_name: Ktichen Led Yellow
      haaska_hidden: false
    script.led_off:
      friendly_name: Kitchen Cabinets Off
      haaska_hidden: false
    automation.kitchen_lights_off_with_dimmer:
      friendly_name: Kitchen Leds Off
      haaska_hidden: true
    automation.kitchen_lights_on_white_with_dimmer:
      friendly_name: Kitchen Leds White
      haaska_hidden: true


light:
################## Microwave side
  - platform: mqtt
    schema: json
    name: kitchen_under_cabinet
    state_topic: "diy/esps/counter"
    command_topic: "diy/esps/counter/set"
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Blink
      - Flash
      - Rainbow
      - Chase
      - Fire flicker
      - Lightning
      - Breathe

  - platform: mqtt
    schema: json
    name: kitchen_pantry
    state_topic: "diy/esp/led_pantry"
    command_topic: "diy/esp/led_pantry/set"
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Blink
      - Flash
      - Rainbow
      - Chase
      - Fire flicker
      - Lightning
      - Breathe

  - platform: mqtt
    schema: json
    name: john_deere_bookshelf
    state_topic: "diy/esps/johndeere_bookshelf"
    command_topic: "diy/esps/johndeere_bookshelf/set"
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Blink
      - Flash
      - Rainbow
      - Chase
      - Fire flicker
      - Lightning
      - Breathe

  - platform: mqtt
    schema: json
    name: spice_cabinet
    state_topic: "diy/esp/spice_cabinet"
    command_topic: "diy/esp/spice_cabinet/set"
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Blink
      - Flash
      - Rainbow
      - Chase
      - Fire flicker
      - Lightning
      - Breathe

automation:
################  Pantry lights ######################################  
  - alias: Kitchen Pantry Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kitchen_dimmer_test
        to: 'click_2'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_pantry_top
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_pantry_middle
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_pantry_bottom
        to: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
                script.led_pantry_yellow
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
                script.led_pantry_yellow
              {% elif is_state("input_boolean.boolean_sleep", "on") %}
                script.led_pantry_yellow
              {% elif is_state("input_boolean.boolean_early_morning", "on") %}
                script.led_pantry_yellow
              {% elif is_state("input_boolean.boolean_home", "on") %}
                script.led_pantry_white
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
                script.led_pantry_yellow
              {% else %}
                script.led_pantry_white
              {% endif %}

  - alias: Kitchen Pantry Lights Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kitchen_dimmer_test
        to: 'click_3'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_pantry_top
        to: 'off'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_pantry_middle
        to: 'off'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_pantry_bottom
        to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.led_pantry_off

############## Spice Cabinet ##########################################
  - alias: Kitchen Spice Cabinets Lights On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_spice_cabinet
        to: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
                script.led_spice_cabinet_yellow
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
                script.led_spice_cabinet_yellow
              {% elif is_state("input_boolean.boolean_sleep", "on") %}
                script.led_spice_cabinet_yellow
              {% elif is_state("input_boolean.boolean_early_morning", "on") %}
                script.led_spice_cabinet_yellow
              {% elif is_state("input_boolean.boolean_home", "on") %}
                script.led_spice_cabinet_white
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
                script.led_pantry_yellow
              {% else %}
                script.led_pantry_white
              {% endif %}

  - alias: Kitchen spice cabinet Lights Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_spice_cabinet
        to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.led_spice_cabinet_off
############## under cabinet leds  ####################
  - alias: Kitchen UnderCabinet Lights On with Dimmer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kitchen_dimmer_test
        to: 'click_1'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
                script.led_yellow
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
                script.led_yellow
              {% elif is_state("input_boolean.boolean_sleep", "on") %}
                script.led_yellow
              {% elif is_state("input_boolean.boolean_early_morning", "on") %}
                script.led_yellow
              {% elif is_state("input_boolean.boolean_home", "on") %}
                script.led_white
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
                script.led_yellow
              {% else %}
                script.led_white
              {% endif %}

  - alias: Kitchen UnderCabinet Lights Off with Dimmer
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kitchen_dimmer_test
        to: 'click_4'
    action:
      - service: script.turn_on
        entity_id: script.led_off

#############################################################
  - alias: Kitchen Leds off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.boolean_sleep
          - input_boolean.boolean_away
        to: 'on'
    action:
      - service: script.turn_on
        entity_id:
          - script.led_off
          - script.led_john_deeer_bookshelf_off

script:
  led_white:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_under_cabinet
          effect: Solid
          brightness: 255
          rgb_color: [255, 215, 255]

  led_pantry_white:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_pantry
          effect: Solid
          brightness: 255
          rgb_color: [ 255,255,255]

  led_john_deeer_bookshelf:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.john_deere_bookshelf
          effect: Solid
          brightness: 190
          rgb_color: [255, 215, 255]

  led_spice_cabinet_white:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.spice_cabinet
          effect: Solid
          brightness: 190
          rgb_color: [255, 215, 255]

  led_yellow:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_under_cabinet
          effect: Solid
          brightness: 255
          rgb_color: [255,200,0]

  led_pantry_yellow:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_pantry
          effect: Solid
          brightness: 255
          rgb_color: [255,208,71]

  led_spice_cabinet_yellow:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.spice_cabinet
          effect: Solid
          brightness: 255
          rgb_color: [255,208,71]


  led_off:
    sequence:
      - service: light.turn_off
        entity_id: light.kitchen_under_cabinet

  led_pantry_off:
    sequence:
      - service: light.turn_off
        entity_id: light.kitchen_pantry

  led_john_deeer_bookshelf_off:
    sequence:
      - service: light.turn_off
        entity_id: light.john_deere_bookshelf

  led_spice_cabinet_off:
    sequence:
      - service: light.turn_off
        entity_id: light.spice_cabinet
