homeassistant:
  customize:
    script.evening_time:
      friendly_name: Evening Time
      haaska_name: Evening Time
    automation.evening_time_turn_on:
      haaska_hidden: true
      friendly_name: Evening Time Automation


########## Evening Time ##############
automation:
  - alias: evening_time_turn_on
    initial_state: 'on'
    trigger:
      - platform: time
        at: '18:01'
    condition:
      - condition: state
        entity_id: sensor.house_mode_state
        state: 'Home'
    action:
     - service: script.evening_time


script:
#  - alias: Evening Time
    evening_time:
      sequence:
        - service: input_boolean.turn_off
          data:
            entity_id: group.input_boolean_card
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.boolean_evening_time
        - service: light.turn_on
          data:
            entity_id: light.lamps
            color_temp: 426
            brightness: 125
        - service: script.turn_on
          entity_id: script.blinds_halfway
        - service: script.turn_on
          entity_id: script.vas_dashboard
        - service: script.turn_on
          entity_id: script.led_off
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.ha_speaker
            volume_level: '{{ states.input_number.evening_mode_chromecast_lv.state }}'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.master_bedroom_cast
            volume_level: '{{ states.input_number.evening_mode_chromecast_masterbedroom.state }}'
        - service: tts.google_say
          data:
            entity_id: media_player.ha_speaker
            message: 'Grandma Mode is Activated'
        - service: tts.google_say
          data:
            entity_id: media_player.master_bedroom_cast
            message: 'Grandma Mode is Activated'
#  - alias: Navigate Dashboard to Vas
    vas_dashboard:
      sequence:
        - event: hadashboard
          event_data:
            command: navigate
#          timeout: 60
            target: vas
