homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Gabbies Room'
    switch.gabbies_lamp:
      friendly_name: Gabbies Lamp
      haaska_name: Gabbies Lamp
      icon: mdi:lamp
    sensor.gabbie_status:
      friendly_name: Gabbie
      icon: mdi:human-child
      haaska_hidden: true
    input_boolean.boolean_gabbie_home:
      friendly_name: Gabbie Home
      haaska_hidden: true
      icon: mdi:human-child
      persistent: true
    input_boolean.boolean_gabbie_awake:
      friendly_name: Gabbie Awake
      haaska_hidden: true
      icon: mdi:sleep-off
      persistent: true
    input_boolean.boolean_gabbie_sleep:
      friendly_name: Gabbie Sleep
      haaska_hidden: true
      icon: mdi:sleep
      persistent: true
    script.gabbies_bedtime:
      friendly_name: Gabbies Bedtime
      icon: mdi:sleep
      haaska_name: Gabbies Bedtime
    script.gabbies_awake:
      friendly_name: Gabbie Awake
      icon: mdi:sleep-off
      haaska_name: Gabbie Awake
    automation.gabbie_going_sleep:
      friendly_name: Gabbie Going Asleep
      haaska_hidden: true
    automation.gabbie_waking_up:
      friendly_name: Gabbie Waking Up
      haaska_hidden: true
    automation.gabbie_home:
      friendly_name: Gabbie Home
      haaska_hidden: true
    automation.gabbie_not_home:
      friendly_name: Gabbie Gone
      haaska_hidden: true
    automation.gabbie_light_on:
      friendly_name: Gabbies Light On
      haaska_hidden: true
    automation.gabbie_light_off:
      friendly_name: Gabbies Light Off
      haaska_hidden: true

group:
  gabbies_room_card:
   name: Gabbie's Room
   control: hidden
   entities:
     - light.gabbies_light
     - input_boolean.boolean_gabbie_home
     - input_boolean.boolean_gabbie_sleep
     - input_boolean.boolean_gabbie_awake
     - switch.gabbies_tv_power
     - script.gabbies_awake
     - script.gabbies_bedtime
     - automation.gabbie_going_sleep
     - automation.gabbie_waking_up
     - automation.gabbie_home
     - automation.gabbie_not_home
     - automation.gabbie_light_on
     - automation.gabbie_light_off
     - group.gabbies_blinds_card


input_boolean:
  boolean_gabbie_home:
    initial: off
  boolean_gabbie_sleep:
    initial: off
  boolean_gabbie_awake:
    initial: off

sensor:
  - platform: template
    sensors:
      gabbie_status:
        value_template: '{% if is_state("input_boolean.boolean_gabbie_home", "on") %}Home{% else %}Gone{% endif %}'

automation:
  - alias: 'gabbie_home'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_home
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Welcome Home Gabbie'
  - alias: 'gabbie_not_home'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_home
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
       - service: tts.google_say
         data:
           entity_id: media_player.ha_speaker
           message: 'Goodbye Gabbie'
  - alias: 'gabbie_going_sleep'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_sleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
       - service: tts.google_say
         data:
           entity_id: media_player.ha_speaker
           message: 'Goodnight Gabbie'
  - alias: 'gabbie_waking_up'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_awake
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
       - service: tts.google_say
         data:
           entity_id: media_player.ha_speaker
           message: 'Goodmorning Gabbie'

  - alias: 'gabbie_light_on'
    trigger:
      - platform: state
        entity_id: binary_sensor.gabbies_room_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_gabbie_awake
        state: 'on'
    action:
       - service: light.turn_on
         data_template:
           entity_id: light.gabbies_light
           brightness_pct: >-
             {% if is_state("input_boolean.boolean_evening_time", "on") %}
             {{ states('input_number.evening_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_movie_time", "on") %}
             {{ states('input_number.movie_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_sleep", "on") %}
             {{ states('input_number.sleep_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_early_morning", "on") %}
             {{ states('input_number.earlymorning_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_home", "on") %}
             {{ states('input_number.home_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_nap_time", "on") %}
             {{ states('input_number.nap_mode_brightness_value') | int }}
             {% else %}
               100
             {% endif %}

  - alias: 'gabbie_light_off'
    trigger:
      - platform: state
        entity_id: binary_sensor.gabbies_room_motion
        to: 'off'
        for: '00:05:00'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_gabbie_awake
        state: 'on'
    action:
       - service: light.turn_off
         entity_id: light.gabbies_light


script:
  gabbies_bedtime:
    sequence:
      - service: light.turn_on
        entity_id: light.gabbies_light
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_gabbie_sleep
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_gabbie_awake
      - service: script.turn_on
        entity_id: script.gabbies_blinds_closed
      - delay: '00:05:00'
      - service: light.turn_off
        data:
          entity_id: light.gabbies_light
          transition: 45
  gabbies_awake:
    sequence:
      - service: light.turn_on
        entity_id: light.gabbies_light
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_gabbie_sleep
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_gabbie_awake
      - service: light.turn_off
        data:
          entity_id: light.gabbies_light
          transition: 180
