homeassistant:
  customize:
    sensor.dawn:
      hasska_hidden: true
      entity_picture: /local/queen.jpeg
    sensor.herb:
      hasska_hidden: true
      entity_picture: /local/king.jpeg
    sensor.mom:
      friendly_name: Mom
      haaska_hidden: true
      icon: mdi:account
    sensor.tristan:
      friendly_name: Tristan
      haaska_hidden: true
      icon: mdi:account

owntracks:
  max_gps_accuracy: 200
  mqtt_topic: "owntracks/#"
# geo locate for device trackers
sensor:
  - platform: google_geocode
    name: Dawn
    api_key: !secret family_geo_locate
    origin: device_tracker.dawn_baby
    scan_interval: 30
#    options: full
  - platform: google_geocode
    name: Herb
    api_key: !secret family_geo_locate
    origin: device_tracker.lsp_herb
    scan_interval: 30
      #    options: both
  - platform: google_geocode
    name: Mom
    api_key: !secret family_geo_locate
    origin: device_tracker.homeassistant_mom
    scan_interval: 90

  - platform: google_geocode
    name: Tristan
    api_key: !secret family_geo_locate
    origin: device_tracker.tristan_tw
    scan_interval: 90
