homeassistant:
  customize:
    sensor.days_to_next_appointment:
      icon: mdi:calendar-clock
    sensor.next_appt_description:
      icon: mdi:note
    sensor.next_appt_message:
      icon: mdi:note
    sensor.next_appt_date_time:
      icon: mdi:calendar-clock
    calendar.main_calender:
      friendly_name: Our Calender
      icon: mdi:calendar-clock
    calendar.holidays_in_united_states:
      friendly_name: Holidays Binary
      icon: mdi:calendar-clock
    sensor.days_to_next_holiday:
      icon: mdi:calendar-clock
    sensor.next_holiday:
      friendly_name: Holiday
      icon: mdi:emoticon-happy
    sensor.next_holiday_date_time:
      icon: mdi:calendar-clock
    sensor.next_birthday:
      icon: mdi:cake-variant
    sensor.days_to_next_birthday:
      icon: mdi:calendar-clock
    sensor.next_birthday_date_time:
      icon: mdi:calendar-clock

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sensor:

######################## Holidays #########################################

  - platform: template
    sensors:
      next_holiday:
        friendly_name: "Next Holiday"
        value_template: "{{ states.calendar.holidays_in_united_states.attributes.message }}"

  - platform: template
    sensors:
      next_holiday_date_time:
        friendly_name: "Next Holiday"
        value_template: "{{ as_timestamp(states.calendar.holidays_in_united_states.attributes.start_time) | timestamp_custom('%D %-I:%M %P') }}"

  - platform: template
    sensors:
      days_to_next_holiday:
        friendly_name: "Days to Next Holiday"
        value_template: >-
              {% set year = states.sensor.date.state.split('-')[0] %}
              {% set month = states.sensor.date.state.split('-')[1] %}
              {% set date = states.sensor.date.state.split('-')[2] %}
              {%- set Month = states.calendar.holidays_in_united_states.attributes.start_time.split('-')[1] -%}
              {%- set DayDate = states.calendar.holidays_in_united_states.attributes.start_time.split('-')[2] -%}
              {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ Month ~ '-' ~ DayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
              {%- if numOfDays < 0 -%}
                {{ numOfDays + 365 }}
              {%- else -%}
                {{ numOfDays }}
              {%- endif -%}

######################### Birthdays ####################################

  - platform: template
    sensors:
      next_birthday_date_time:
        friendly_name: "Next Birthday Date Time"
        value_template: "{{ as_timestamp(states.calendar.contacts.attributes.start_time) | timestamp_custom('%D %-I:%M %P') }}"

  - platform: template
    sensors:
      next_birthday:
        friendly_name: "Next Birthday"
        value_template: "{{ states.calendar.contacts.attributes.message }}"

  - platform: template
    sensors:
      days_to_next_birthday:
        friendly_name: "Days to Next Birthday"
        value_template: >-
              {% set year = states.sensor.date.state.split('-')[0] %}
              {% set month = states.sensor.date.state.split('-')[1] %}
              {% set date = states.sensor.date.state.split('-')[2] %}
              {%- set Month = states.calendar.contacts.attributes.start_time.split('-')[1] -%}
              {%- set DayDate = states.calendar.contacts.attributes.start_time.split('-')[2] -%}
              {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ Month ~ '-' ~ DayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
              {%- if numOfDays < 0 -%}
                {{ numOfDays + 365 }}
              {%- else -%}
                {{ numOfDays }}
              {%- endif -%}

################# Appontments ####################################

  - platform: template
    sensors:
      next_appt_date_time:
        friendly_name: "Next Appt Date Time"
        value_template: "{{ as_timestamp(states.calendar.main_calender.attributes.start_time) | timestamp_custom('%D %-I:%M %P') }}"

  - platform: template
    sensors:
      next_appt_message:
        friendly_name: "Next Appt Type"
        value_template: "{{ states.calendar.main_calender.attributes.message }}"

  - platform: template
    sensors:
      next_appt_description:
        friendly_name: "Next Appt Description"
        value_template: "{{ states.calendar.main_calender.attributes.description }}"

  - platform: template
    sensors:
      days_to_next_appointment:
        friendly_name: "Days to Next Appointment"
        value_template: >-
              {% set year = states.sensor.date.state.split('-')[0] %}
              {% set month = states.sensor.date.state.split('-')[1] %}
              {% set date = states.sensor.date.state.split('-')[2] %}
              {%- set Month = states.calendar.main_calender.attributes.start_time.split('-')[1] -%}
              {%- set DayDate = states.calendar.main_calender.attributes.start_time.split('-')[2] -%}
              {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ Month ~ '-' ~ DayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
              {%- if numOfDays < 0 -%}
                {{ numOfDays + 365 }}
              {%- else -%}
                {{ numOfDays }}
              {%- endif -%}

automation:

########################## Birthdays #######################################

  - alias: Birthday Countdown 30 Days
    initial_state: 'on'
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ states.sensor.days_to_next_birthday.state | int > 0 and states.sensor.days_to_next_birthday.state | int < 30 }}"
    action:
      - delay: '00:01:00'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'BIRTHDAY COUNTDOWN {{states.sensor.next_birthday.state}} is {{states.sensor.days_to_next_birthday.state}} days away'

  - alias: Random Birthday Wishes
    initial_state: 'on'
    hide_entity: false
    trigger:
      platform: time_pattern
      hours: '/1'
      minutes: 3
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: calendar.contacts
          state: 'on'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: !include ../intent_templates/birthday_wishes.yaml

####### Holiday Announcment ################

  - alias: Holiday Countdown 7 Days
    initial_state: 'on'
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ states.sensor.days_to_next_holiday.state | int > 0 and states.sensor.days_to_next_holiday.state | int < 8 }}"
    action:
      - delay: '00:01:00'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'Holiday COUNTDOWN {{states.sensor.next_holiday.state}} is {{states.sensor.days_to_next_holiday.state}} days away'

  - alias: Holiday
    initial_state: 'on'
    hide_entity: false
    trigger:
      platform: time_pattern
      hours: '/1'
      minutes: 3
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: calendar.holidays_in_united_states
          state: 'on'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'Today is {{ states.calendar.holidays_in_united_states.attributes.message }}'

##### appointment Announcment   ###################

  - alias: Dr Appointment Reminder 3 days
    initial_state: 'on'
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ states.sensor.days_to_next_appointment.state | int > 0 and states.sensor.days_to_next_appointment.state | int < 4 }}"
      - condition: template
        value_template: "{{ states.sensor.days_to_next_appointment.state != 'Unknown' }}"
      - condition: template
        value_template: "{{ states.calendar.main_calender.attributes.description != 'None' }}"
    action:
      - delay: '00:01:15'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: >-
            Appointment Reminder {{ states.calendar.main_calender.attributes.message }}
            with {{ states.calendar.main_calender.attributes.description }} is
            {{ states.sensor.days_to_next_appointment.state }} days away
      - service: notify.pushbullet
        data_template:
          message: >-
            Appointment Reminder {{ states.calendar.main_calender.attributes.message }}
            with {{ states.calendar.main_calender.attributes.description }} is
            {{states.sensor.days_to_next_appointment.state}} days away
      - service: notify.chrome_push
        data_template:
          title: "Appointment Reminder"
          message: >-
            Appointment Reminder {{ states.calendar.main_calender.attributes.message }}
            with {{ states.calendar.main_calender.attributes.description }} is
            {{states.sensor.days_to_next_appointment.state}} days away

  - alias: Dr Appontments
    initial_state: 'on'
    hide_entity: false
    trigger:
      platform: state
      entity_id: input_boolean.boolean_home
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        # - condition: template
        #   value_template: "{{ states.sensor.days_to_next_appointment.state | int == 0 }}"
        # - condition: template
        #   value_template: "{{ states.calendar.main_calender.attributes is defined }}"
        - condition: template
          value_template: "{{ state_attr('calendar.main', 'description') != None }}"
        # - condition: template
        #   value_template: "{{ state_attr('calendar.main', 'start_time') != '' }}"
    action:
      - delay: '00:01:30'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: >-
            Dr appointment today {{ states.calendar.main_calender.attributes.description }}
            at {{ as_timestamp(states.calendar.main_calender.attributes.start_time) | timestamp_custom('%-I:%M %P') }}
      - service: notify.pushbullet
        data_template:
          message: >-
            Appointment Today {{ states.calendar.main_calender.attributes.message }}
            with {{ states.calendar.main_calender.attributes.description }}
            at {{ as_timestamp(states.calendar.main_calender.attributes.start_time) | timestamp_custom('%-I:%M %P') }}
      - service: notify.chrome_push
        data_template:
          title: "Appointment Reminder"
          message: >-
            Appointment Today {{ states.calendar.main_calender.attributes.message }}
            with {{ states.calendar.main_calender.attributes.description }} at
            {{ as_timestamp(states.calendar.main_calender.attributes.start_time) | timestamp_custom('%-I:%M %P') }}
