homeassistant:
  customize:
    automation.Ha_Start:
      friendly_name: Ha Start
      haaska_hidden: true
    input_boolean.ha_start:
      friendly_name: Ha Restart in Process
      haaska_hidden: true

input_boolean:
  ha_start:
    initial: off

automation:
  - alias: Ha Start
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: automation.turn_off
        entity_id: automation.notify_device_status
      - service: input_boolean.turn_on
        entity_id: input_boolean.ha_start
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.ha_speaker
          volume_level: '.80'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.master_bedroom_cast
          volume_level: '.40'
      - delay: '00:00:20'
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Home assistant is up Volume Set for Living Room'
      - service: tts.google_say
        data:
          entity_id: media_player.master_bedroom_cast
          message: 'Home assistant is up Volume Set for Master Bedroom'
      - delay: '00:05:00'
      - service: automation.turn_on
        entity_id: automation.notify_device_status
      - service: input_boolean.turn_off
        entity_id: input_boolean.ha_start
