homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Kids Bathroom Room'
    sensor.kids_bathroom_dimmer_battery:
      icon: mdi:battery
      friendly_name: Kids Bathroom Dimmer
    sensor.kids_bathroom_dimmer_last_update:
      icon: mdi:clock
    sensor.kids_bathroom_dimmer_state:
      icon: mdi:remote
    sensor.kids_motion_sensor_batt:
      icon: mdi:battery
      unit_of_measurement: '%'
    sensor.humidity_kids_bathroom:
      friendly_name: Kids Bathroom Humidity
      haaska_hidden: true
    sensor.temperature_kids_bathroom:
      friendly_name: Kids Bathroom Temperature
      haaska_hidden: true
    binary_sensor.motion_sensor_kids_bathroom:
      haaska_hidden: true
    sensor.kids_humidity_sensor_batt:
      haaska_hidden: true
      friendly_name: Kids Bathroom Humidity Sensor
      unit_of_measurement: '%'
      icon: mdi:battery
    sensor.illumination_kids_bathroom:
      friendly_name: Kids Bathroom Lux
      haaska_hidden: true
      unit_of_measurement: 'Lux'
    automation.motion_kids_bathroom_home_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_evening_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_home_mode_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_sleep_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_sleep_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.kids_bath_shower_time_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.kids_bath_light_left_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.kids_humidity_fan_on:
      haaska_hidden: true
    automation.kids_humidity_fan_off:
      haaska_hidden: true
    script.kids_shower_time_on:
      friendly_name: Kids Shower Time Script
      haaska_hidden: true
    script.kids_shower_time_off:
      friendly_name: Kids Finished Shower Script
      haaska_hidden: true
    switch.kids_shower_time:
      friendly_name: Kids Shower Time
      haaska_hidden: false
      haaska_name: Kids Shower TIme
    light.kids_bathroom:
      persistence: false
    light.kids_bathroom_vanity:
      persistence: false
    switch.wemo_kids_bath_fan:
      friendly_name: Kids Bath Humidity Fan
      icon: mdi:fan

group:
  kids_bath_card:
     control: hidden
     name: Kids Bath
     entities:
      - light.kids_bathroom
      - light.kids_bathroom_vanity
      - switch.wemo_kids_bath_fan
      - switch.kids_bathroom_scent
      - sensor.temperature_kids_bathroom
      - sensor.pressure_kids_bathroom
      - sensor.humidity_kids_bathroom
      - binary_sensor.motion_sensor_kids_bathroom
      - sensor.illumination_kids_bathroom
      - sensor.kids_motion_sensor_batt
      - sensor.kids_humidity_sensor_batt
      - sensor.kids_bathroom_dimmer_state
      - sensor.kids_bathroom_dimmer_last_update
      - sensor.kids_bathroom_dimmer_battery
      - script.kids_shower_time_on
      - script.kids_shower_time_off
      - switch.kids_shower_time
      - automation.kids_bath_light_left_on
      - automation.kids_bath_shower_time_off
      - automation.kids_bath_shower_time_on
      - automation.motion_kids_bathroom_home_mode_off
      - automation.motion_kids_bathroom_home_mode_on
      - automation.motion_kids_bathroom_evening_mode_on
      - automation.motion_kids_bathroom_sleep_off
      - automation.motion_kids_bathroom_sleep_on


sensor:
      ######## Kids Bathroom
  - platform: rest
    resource: !secret dimmer_rest_27
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'kids_bathroom_dimmer_battery'
  - platform: rest
    resource: !secret dimmer_rest_27
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 1
    name: 'Kids Bathroom Dimmer State'
  - platform: template
    sensors:
      kids_bathroom_dimmer_state:
        friendly_name: 'Kids Bath Dimmer Last Button Push'
        value_template: >-
                      {% if states('sensor.kids_bathroom_dimmer_state_2')[0] == "1" %}
                        On
                      {% elif states('sensor.kids_bathroom_dimmer_state_2')[0] == "4" %}
                        Off
                      {% else %}
                        None
                      {% endif %}
  - platform: rest
    resource: !secret dimmer_rest_27
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'Kids Bathroom Dimmer Last Update'
  - platform: template
    sensors:
      kids_bathroom_dimmer_last_update:
        friendly_name: 'Kids Bathroom Last Used'
        value_template: >-
          {{ as_timestamp(strptime(states('sensor.kids_bathroom_dimmer_last_update_2')[:19], '%Y-%m-%dT%X'))|timestamp_custom('%a, %B %d') }}

  - platform: template
    sensors:
      kids_motion_sensor_batt:
        friendly_name: 'Kids Bathroom Motion Sensor'
        value_template: "{{ states.binary_sensor.motion_sensor_kids_bathroom.attributes.battery_level }}"
  - platform: template
    sensors:
      kids_humidity_sensor_batt:
        friendly_name: 'Kids Bathroom Humidity Sensor Battery Level'
        value_template: "{{ states.sensor.humidity_kids_bathroom.attributes.battery_level }}"

automation:
  - alias: Motion Kids Bathroom Home Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_kids_bathroom
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 154
          brightness: 255

  - alias: Motion Kids Bathroom Evening Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_kids_bathroom
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 392
          brightness: 74

  - alias: Motion Kids Bathroom Home Mode off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'off'
        for:
          minutes: 3
      - platform: state
        entity_id: binary_sensor.motion_sensor_kids_bathroom
        to: 'off'
        for:
          minutes: 3
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: light.turn_off
        entity_id: light.kids_bathroom

  - alias: Motion Kids Bathroom Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_kids_bathroom
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 426
          brightness: 50

  - alias: Motion Kids Bathroom Sleep Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.motion_sensor_kids_bathroom
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.kids_bathroom

  - alias: Kids Bath Shower Time On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kids_bathroom_dimmer_state
        to: 'On'
    action:
      - service: script.turn_on
        entity_id: script.kids_shower_time_on

  - alias: Kids Bath Shower Time Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kids_bathroom_dimmer_state
        to: 'Off'
    action:
      - service: script.turn_on
        entity_id: script.kids_shower_time_off

  - alias: Kids Bath light left on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.kids_bathroom_vanity
        to: 'on'
        for:
          hours: 1
          minutes: 00
          seconds: 00
    action:
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.kids_bathroom_vanity
      - service: light.turn_off
        entity_id: light.kids_bathroom
###############################################################################
###  vent fan if humidity is over 60 control                            #######
###############################################################################
  - alias: Kids Humidity Fan On
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.sensor.humidity_kids_bathroom.state > states.input_number.target_humidity_kids_bathroom.state }}'
    action:
      - service: switch.turn_on
        entity_id: switch.wemo_kids_bath_fan
  - alias: Kids Humidity Fan Off
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.sensor.humidity_kids_bathroom.state < states.input_number.target_humidity_kids_bathroom.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.wemo_kids_bath_fan


script:
  kids_shower_time_on:
    sequence:
      - delay: '00:00:05'
      - service: automation.turn_off
        entity_id: automation.motion_kids_bathroom_home_mode_off
      - service: automation.turn_off
        entity_id: automation.motion_kids_bathroom_sleep_off
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom_vanity
          color_temp: 154
          brightness: 255
      # - service: switch.turn_on
      #   entity_id: switch.wemo_kids_bath_fan
  kids_shower_time_off:
    sequence:
      - delay: '00:00:05'
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_home_mode_off
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_sleep_off
      - service: light.turn_off
        entity_id: light.kids_bathroom_vanity
      - service: homeassistant.turn_off
        entity_id: light.kids_bathroom
      # - service: switch.turn_off
      #   entity_id: switch.wemo_kids_bath_fan


switch:
  - platform: template
    switches:
      kids_shower_time:
        value_template: "{{ is_state('light.kids_bathroom_vanity', 'on') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.kids_shower_time_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.kids_shower_time_off
