homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Kids Bathroom Room'
    ############ DIMMERS #################
    binary_sensor.kids_bathroom_motion:
      haaska_hidden: true
      device_class: motion
      friendly_name: Kids Bathroom Motion
    sensor.kids_bathroom_temperature:
      haaska_hidden: true
    sensor.kids_bathroom_dimmer_battery:
      icon: mdi:battery
    sensor.kids_bathroom_dimmer_last_update:
      icon: mdi:clock
    sensor.kids_bathroom_dimmer_state:
      icon: mdi:remote
    sensor.motion_sensor_kids_bathroom_battery:
      icon: mdi:battery
    sensor.kids_bathroom_motion_sensor_lux:
      friendly_name: Kids Bathroom Light Level
      icon: mdi:theme-light-dark
    automation.motion_kids_bathroom_home_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_evening_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_home_mode_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_sleep_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_kids_bathroom_sleep_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.kids_bath_shower_time_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.kids_bath_light_left_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    script.kids_shower_time_on:
      friendly_name: Kids Shower Time Script
      haaska_hidden: true
    script.kids_shower_time_off:
      friendly_name: Kids Finished Shower Script
      haaska_hidden: true
    switch.kids_shower_time:
      friendly_name: Kids Shower Time
      haaska_hidden: false
      haaska_name: Kids Shower TIme
    light.kids_bathroom:
      persistence: false
    light.kids_bathroom_vanity:
      persistence: false
    switch.wemo_kids_bath_fan:
      friendly_name: Kids Bath Humidity Fan
      icon: mdi:fan
      

binary_sensor:
  - platform: rest
    resource: !secret MS_rest_30
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: kids_bathroom_motion
sensor:
      ######## Kids Bathroom
  - platform: rest
    resource: !secret dimmer_rest_27
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Kids Bathroom Dimmer Battery'
  - platform: rest
    resource: !secret dimmer_rest_27
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 1
    name: 'Kids Bathroom Dimmer State'
  - platform: template
    sensors:
      kids_bathroom_dimmer_state:
        friendly_name: 'Kids Bath Dimmer Last Button Push'
        value_template: >-
                      {% if states('sensor.kids_bathroom_dimmer_state_2')[0] == "1" %}
                        On
                      {% elif states('sensor.kids_bathroom_dimmer_state_2')[0] == "4" %}
                        Off
                      {% else %}
                        None
                      {% endif %}
  - platform: rest
    resource: !secret dimmer_rest_27
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'Kids Bathroom Dimmer Last Update'
  - platform: template
    sensors:
      kids_bathroom_dimmer_last_update:
        friendly_name: 'Kids Bathroom Last Used'
        value_template: >-
          {{ as_timestamp(strptime(states('sensor.kids_bathroom_dimmer_last_update_2')[:19], '%Y-%m-%dT%X'))|timestamp_custom('%a, %B %d') }}
  - platform: rest
    resource: !secret MS_rest_29
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Kids Bathroom Temperature'
  - platform: rest
    resource: !secret MS_rest_30
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Kids Bathroom Battery'
  - platform: rest
    resource: !secret MS_rest_31
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    scan_interval: 5
    name: 'Kids Bathroom Motion Sensor Lux'

automation:
  - alias: Motion Kids Bathroom Home Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 154
          brightness: 255

  - alias: Motion Kids Bathroom Evening Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 392
          brightness: 74

  - alias: Motion Kids Bathroom Home Mode off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'off'
        for:
          minutes: 3
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: light.turn_off
        entity_id: light.kids_bathroom

  - alias: Motion Kids Bathroom Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 426
          brightness: 50

  - alias: Motion Kids Bathroom Sleep Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_motion
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.kids_bathroom

  - alias: Kids Bath Shower Time On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kids_bathroom_dimmer_state
        to: 'On'
    action:
      - service: script.turn_on
        entity_id: script.kids_shower_time_on

  - alias: Kids Bath Shower Time Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kids_bathroom_dimmer_state
        to: 'Off'
    action:
      - service: script.turn_on
        entity_id: script.kids_shower_time_off

  - alias: Kids Bath light left on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.kids_bathroom_vanity
        to: 'on'
        for:
          hours: 1
          minutes: 00
          seconds: 00
    action:
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.kids_bathroom_vanity
      - service: light.turn_off
        entity_id: light.kids_bathroom

script:
  kids_shower_time_on:
    sequence:
      - delay: '00:00:05'
      - service: automation.turn_off
        entity_id: automation.motion_kids_bathroom_home_mode_off
      - service: automation.turn_off
        entity_id: automation.motion_kids_bathroom_sleep_off
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.kids_bathroom_vanity
          color_temp: 154
          brightness: 255
      - service: switch.turn_on
        entity_id: switch.wemo_kids_bath_fan
  kids_shower_time_off:
    sequence:
      - delay: '00:00:05'
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_home_mode_off
      - service: automation.turn_on
        entity_id: automation.motion_kids_bathroom_sleep_off
      - service: light.turn_off
        entity_id: light.kids_bathroom_vanity
      - service: homeassistant.turn_off
        entity_id: light.kids_bathroom
      - service: switch.turn_off
        entity_id: switch.wemo_kids_bath_fan


switch:
  - platform: template
    switches:
      kids_shower_time:
        value_template: "{{ is_state('light.kids_bathroom_vanity', 'on') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.kids_shower_time_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.kids_shower_time_off
