homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'laundry Room'
    binary_sensor.laundry_room_motion:
      friendly_name: Laundry Room Motion
      device_class: motion
    sensor.motion_sensor_laundry_battery:
      icon: mdi:battery
    sensor.motion_sensor_laundry_lux:
      friendly_name: Laundry Room Light Level
      icon: mdi:theme-light-dark

sensor:
  - platform: rest
    resource: !secret MS_rest_19
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Laundry Temperature'

  - platform: rest
    resource: !secret MS_rest_20
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Laundry Battery'

  - platform: rest
    resource: !secret MS_rest_21
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    scan_interval: 5
    name: 'Motion Sensor Laundry Lux'



binary_sensor:
  - platform: rest
    resource: !secret MS_rest_20
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: laundry_room_motion

automation:
  - alias: Laundry Motion HomeMode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.motion_sensor_laundry_lux
        below: '8000'
    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          color_temp: 154
          brightness: 255

  - alias: Laundry Motion not HomeMode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          color_temp: 154
          brightness: 125

  - alias: Laundry Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'off'
        for: '00:01:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.laundry_room
          transition: 30
