homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'mail_info'
    sensor.usps_mail:
      friendly_name: Mail
      icon: mdi:mailbox
    sensor.usps_packages:
      icon: mdi:package-variant
    sensor.deliveries_today:
      icon: mdi:package-variant
    sensor.packages_in_transit:
      icon: mdi:truck-fast
    sensor.fedex:
      icon: mdi:truck-fast
    camera.camera_mail:
      friendly_name: Mail Scan's

group:
  mailscan_card:
   name: Mail Scans
   entities:
    - camera.camera_mail

  usps_mail_card:
   name: Mail
   entities:
     - sensor.usps_mail
     - sensor.usps_packages
     - sensor.packages_in_transit
     - sensor.deliveries_today
     - sensor.fedex
     - sensor.ups

############### Mail Sensor   ###############################
sensor:

  - platform: mqtt
    name: 'USPS Mail'
    state_topic: '/usps/mails'
    value_template: "{{ value }}"

  - platform: mqtt
    name: USPS Packages
    state_topic: '/usps/packages'
    value_template: "{{ value }}"

#  - platform: usps
#    username: !secret usps_username
#    password: !secret usps_password
#    scan_interval: 1800
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password
    scan_interval: 1800
  - platform: fedex
    username: !secret fedex_username
    password: !secret fedex_password
    scan_interval: 1800
  - platform: template
    sensors:
      packages_in_transit:
        friendly_name: "Packages in Transit"
        value_template: >
          {% macro in_transit(sensor) %}
            {{sensor.state|int - delivered(sensor)|int}}
          {% endmacro %}
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int  + in_transit(states.sensor.fedex)|int}}
      deliveries_today:
        friendly_name: "Today's Deliveries"
        value_template: >
          {% macro delivered(sensor) %}
            {% if 'out_for_delivery' in sensor.attributes %}
              {{sensor.attributes.out_for_delivery}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{delivered(states.sensor.usps_mail_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}
############################################################

automation:
  - alias: Tell me I got Mail
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.usps_mail
        above: 0
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'You Have Mail Today Check Dashboard'
      - service: shell_command.lv_room_mail ## In dashboard package
      - delay: '00:05:00'
      - service: shell_command.lv_room_vas    # in dashboard package

  - alias: Tell me I got Packages
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.mail_packages
        above: 0
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'You Have a Usps Package On the Way Check Dashboard'
camera:
  - platform: generic
    name: Camera Mail
    still_image_url: !secret mail_scan_ip
