homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'mail_info'
    sensor.usps_mail:
      friendly_name: Mail
      icon: mdi:mailbox
    sensor.usps_packages:
      icon: mdi:package-variant
    sensor.deliveries_today:
      icon: mdi:package-variant
    sensor.packages_in_transit:
      icon: mdi:truck-fast
    sensor.fedex:
      icon: mdi:truck-fast
    camera.camera_mail:
      friendly_name: Mail Scan's

############### Mail Sensor   ###############################
sensor:
  - platform: mqtt
    name: 'USPS Mail'
    state_topic: '/usps/mails'
    value_template: "{{ value }}"
  - platform: mqtt
    name: 'USPS Packages'
    state_topic: '/usps/packages'
    value_template: "{{ value }}"
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password
    scan_interval: 1800

automation:
  - alias: Tell me I got Mail
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.usps_mail
        above: 0
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'You Have Mail Today Check Dashboard'
      - service: shell_command.lv_room_mail ## In dashboard package
      - delay: '00:05:00'
      - service: shell_command.lv_room_vas    # in dashboard package

  - alias: Tell me I got Packages
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.usps_packages
        above: 0
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'You Have a Usps Package On the Way Check Dashboard'
camera:
  - platform: generic
    name: Camera Mail
    still_image_url: !secret mail_scan_ip
