homeassistant:
  customize:
    media_player.blueiris2:
      friendly_name: Plex

# grouped each media player so that the would show correctly
group:
  Samsung_tv_media_player_card:
   name: Samsung
   entities:
     - media_player.smart_tv
  stereo_avr_card:
   name: stereo Amp
   entities:
     - media_player.stereo
  stereo_avr_card_zone_2:
   name: stereo Amp
   entities:
     - media_player.stereo_zone_2
  stereo_avr_card_zone_3:
   name: stereo Amp
   entities:
     - media_player.stereo_zone_3
  ruths_roku_media_player_card:
   name: Ruths Roku
   entities:
     - media_player.ruths_roku
  media_player_ha_speaker_card:
   name: Ha TTS Speaker
   entities:
     - media_player.ha_speaker
  media_player_networkpc_card:
    name: Plex
    entities:
      - media_player.networkpc
  media_player_living_room_card:
    name: Living Room Roku
    entities:
      - media_player.living_room
  media_player_plex_server_card:
    name: Plex Server
    entities:
      - media_player.plex_server_living_room
  media_player_master_bedroom_cast_card:
    name: Master Bedroom Cast
    entities:
      - media_player.master_bedroom_cast

media_player:
  # - platform: kodi
  #   name: Ha Speaker
  #   host: 192.168.1.154
  #   port: 8888
  #   username: !secret media_player_kodi_username
  #   password: !secret media_player_kodi_password

  - platform: samsungtv
    host: 192.168.1.14
    port: 8001
    name: Smart Tv

  # - platform: plex
  #   entity_namespace: 'plex_server'
  #   include_non_clients: true
  #   IP_ADDRESS: 192.168.1.80

  - platform: onkyo
    host: 192.168.1.81
    name: Stereo
    sources:
      dvd: 'Blue Iris'
      game: 'PS4'
      pc: 'Kodi'
      cd: 'PI'
      tv-cd: 'TV'
      tuner: 'Radio'
      net: 'Net'

  # - platform: roku
  #   host: 192.168.1.142

  - platform: roku
    host: 192.168.1.143

  - platform: cast
    host: 192.168.1.173
    name: master_bedroom_cast

  - platform: cast
    host: 192.168.1.32
    name: Ha Speaker
