
sensor:
  - platform: min_max
    type: mean
    name: House Avg Temperature
    entity_ids:
      - sensor.master_bath_temp
      - sensor.hallway_temperature
      - sensor.kids_room_temperature  #Ecobee sensor
      - sensor.master_bedroom_temperature
      - sensor.living_room_temperature #Ecobee sensor
      - sensor.thermostat_temperature #Ecobee thermostat
      - sensor.ha_temperature
      - sensor.temperature_kids_bathroom # Xiaomi humidity temp sensor
      - sensor.living_room_purifer_temp #Xiaomi Purifer 2s
      - sensor.master_bdrm_purifer_temp #Xiaomi Purifer 2s
      - sensor.kids_bdrm_purifer_temp #Xiaomi Purifer 2s

  - platform: min_max
    type: mean
    name: House Avg Humidity
    entity_ids:
      - sensor.master_bath_humidity
      - sensor.thermostat_humidity
      - sensor.ha_humidity
      - sensor.humidity_kids_bathroom # Xiaomi humidity temp senso
      - sensor.humidity_master_bathroom # Xiaomi humidity temp senso
      - sensor.living_room_purifer_humd #Xiaomi Purifer 2s
      - sensor.master_bdrm_purifer_humd #Xiaomi Purifer 2s
      - sensor.kids_bdrm_purifer_humd #Xiaomi Purifer 2s
