group:
  avg_temp_card:
   name: Average Temperature
   entities:
     - sensor.house_avg_temperature  # added to ecobee package only
     - sensor.house_avg_humidity # added to ecobee package only

sensor:
  - platform: min_max
    type: mean
    name: House Avg Temperature
    entity_ids:
      - sensor.hallway_temperature
      - sensor.gabbies_room_temperature  #Ecobee sensor
      - sensor.master_bedroom_temperature
      - sensor.living_room_temperature #Ecobee sensor
      - sensor.thermostat_temperature #Ecobee thermostat
      - sensor.ha_temperature
      - sensor.temperature_kids_bathroom # Xiaomi humidity temp sensor
      - sensor.living_room_purifer_temp #Xiaomi Purifer 2s
      - sensor.master_bdrm_purifer_temp #Xiaomi Purifer 2s

  - platform: min_max
    type: mean
    name: House Avg Humidity
    entity_ids:
      - sensor.thermostat_humidity
      - sensor.ha_humidity
      - sensor.humidity_kids_bathroom # Xiaomi humidity temp senso
      - sensor.humidity_master_bathroom # Xiaomi humidity temp senso
      - sensor.living_room_purifer_humd #Xiaomi Purifer 2s
      - sensor.master_bdrm_purifer_humd #Xiaomi Purifer 2s
