group:
  avg_temp_card:
   name: Average Temperature
   entities:
     - sensor.house_avg_temperature  # added to ecobee package only
     - sensor.house_avg_humidity # added to ecobee package only

sensor:
  - platform: min_max
    type: mean
    name: House Avg Temperature
    entity_ids:
      - sensor.kitchen_temperature
      - sensor.hallway_temperature
      - sensor.laundry_temperature
      - sensor.kids_hallway_temperature
      - sensor.master_temperature
#      - sensor.bathroom_temperature       #old hue in master bathroom
      - sensor.gabbies_room_temperature
      - sensor.master_bedroom_temperature
      - sensor.living_room_temperature
      - sensor.ruths_room_temperature
      - sensor.thermostat_temperature
      - sensor.ha_temperature
      - sensor.temperature_kids_bathroom
      - sensor.temperature_master_bathroom
      - sensor.living_room_purifer_temp

  - platform: min_max
    type: mean
    name: House Avg Humidity
    entity_ids:
      - sensor.thermostat_humidity
      - sensor.ha_humidity
      - sensor.humidity_kids_bathroom
      - sensor.humidity_master_bathroom
      - sensor.living_room_purifer_humd
