homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'main_home'

    input_boolean.boolean_home:
      friendly_name: Home
      hasska_hidden: true

    input_number.home_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.home_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.home_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.home_mode_chromecast_lv:
      friendly_name: Chrome Cast Living Room Value
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.home_mode_chromecast_masterbedroom:
      friendly_name: Chrome Cast Master Bedroom
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true

#########################################################################################
#                                                                                   #####
#                   Home Mode                                                       #####
#                                                                                   #####
#########################################################################################
input_boolean:
  boolean_home:
    initial: on

input_number:
  home_mode_brightness_value:
    name: Home Mode Brightness
    initial: 100
    min: 0
    max: 100
    step: 1
  home_mode_color_temp_value:
    name: Home Mode Color Temp
    initial: 154
    min: 154
    max: 426
    step: 1
  home_mode_transition_value:
    name: Home Mode Transition
    initial: 10
    min: 1
    max: 90
    step: 1
  home_mode_chromecast_lv:
    name: Home Mode TTS Living Room
    initial: .80
    min: 0
    max: 1
    step: .1
  home_mode_chromecast_masterbedroom:
    name: Home Mode TTS Master Bedroom
    initial: .40
    min: 0
    max: 1
    step: .1

#### used mostly for tasker when wife gets home
automation:
  - alias: 'turn_on_home_mode_auto_tasker'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.home_mode

script:
  home_mode:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_main_modes_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_home
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.boolean_active_outside
      - service: automation.turn_on
        data:
          entity_id: automation.motion_master_bedroom
      - service: climate.set_away_mode
        data:
          entity_id: climate.thermostat
          away_mode: 'off'
      - service: climate.set_hold_mode
        data:
          entity_id: climate.thermostat
          hold_mode: "home"
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
      - delay: '00:00:05'
      - service: wink.refresh_state_from_wink
      - service: rest_command.no_motion
      - service: rest_command.no_motion
      - service: switch.turn_on
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:01'
      - service: light.turn_on
        data_template:
          entity_id:
            - light.lamps
            - light.kitchen
            - light.master_hallway
            - light.kids_hallway
          color_temp: "{{ states('input_number.home_mode_color_temp_value') | int }}"
          brightness_pct: "{{ states('input_number.home_mode_brightness_value') | int }}"
      - delay: '00:00:01'
      - service: light.turn_off
        entity_id:
          - light.master_hallway
          - light.kitchen
          - light.kids_hallway
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.ha_speaker
          volume_level: '{{ states.input_number.home_mode_chromecast_lv.state }}'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.master_bedroom_cast
          volume_level: '{{ states.input_number.home_mode_chromecast_masterbedroom.state }}'
      - delay: '00:00:20'
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Home Mode is Set Volume Set for Living Room'
      - service: tts.google_say
        data:
          entity_id: media_player.master_bedroom_cast
          message: 'Home Mode Set Volume Set for Master Bedroom'
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Home Mode is Activated'
      - service: light.turn_off
        entity_id: light.gateway_light_xiaomi_lv
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_extra_work_day
