homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'daytime_sleep'

    input_boolean.boolean_day_time_sleep:
      friendly_name: Day Time Sleep
      hasska_hidden: true

    script.daytime_sleep_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: false
      friendly_name: Daytime Sleep On
      icon: mdi:sleep
    script.daytime_sleep_mode_off:
      haaska_hidden: true
      hidden: false
      persistence: false
      friendly_name: Daytime Sleep Off
      icon: mdi:sleep
    switch.daytime_sleep:
      haaska_hidden: false
      hidden: false
      persistence: false
      friendly_name: Daytime Sleep
      haaska_name: Bed Early
      icon: mdi:sleep

input_boolean:
  boolean_day_time_sleep:
    initial: off

script:
  daytime_sleep_mode_on:
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_day_time_sleep
      - service: light.turn_off
        entity_id: light.master
      - service: light.turn_on
        data:
          entity_id: light.master_table_lamps
          brightness_pct: 50
      - service: light.turn_off
        data:
          entity_id: light.master_table_lamps
          transition: 90
      - service: switch.turn_on
        entity_id: switch.dawn_night
      - service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_fan
          speed: "high"
      - service: switch.turn_off
        entity_id: switch.master_bedroom_mixer

  daytime_sleep_mode_off:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.boolean_day_time_sleep
      - service: switch.turn_on
        entity_id: switch.master_bedroom_mixer

switch:
  - platform: template
    switches:
      daytime_sleep:
        value_template: "{{ is_state('input_boolean.boolean_day_time_sleep', 'on') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.daytime_sleep_mode_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.daytime_sleep_mode_off
