homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'modes_house'

    sensor.house_mode_state:
      friendly_name: House Mode
      hasska_hidden: true
      icon: mdi:home
    sensor.sub_mode_state:
      friendly_name: Sub House Mode
      hasska_hidden: true
      icon: mdi:home
    sensor.privacy_mode_state:
      friendly_name: Privacy Mode
      hasska_hidden: true
      icon: mdi:home
    binary_sensor.workday_sensor:
      friendly_name: Work Today
      haaska_hidden: true

group:
  input_boolean_main_modes_card:
    name: Input Boolean House Mode
    control: hidden
    entities:
      - input_boolean.boolean_home
      - input_boolean.boolean_away
      - input_boolean.boolean_early_morning
      - input_boolean.boolean_sleep
      - input_boolean.boolean_evening_time
      - input_boolean.boolean_nap_time
      - input_boolean.boolean_movie_time

  input_boolean_sub_modes_card:
    name: Input Boolean Sub House Mode
    control: hidden
    entities:
      - input_boolean.boolean_privacy
      - input_boolean.boolean_kids_home
      - input_boolean.boolean_day_time_sleep
      - input_boolean.boolean_privacy
      - input_boolean.boolean_kids_home
      - input_boolean.boolean_active_outside
      - input_boolean.boolean_kids_shower_time
      - input_boolean.boolean_shower_time
      - input_boolean.boolean_play_xbox

  House_mode:
   name: Home Mode
   control: hidden
   entities:
     - sensor.house_mode_state
     - sensor.sub_mode_state
     - sensor.kids_room_mode
     - sensor.privacy_mode_state
     - input_boolean.boolean_kids_home
     - binary_sensor.workday_sensor

sensor:
  - platform: template
    sensors:
      house_mode_state:
        value_template: >-
          {% if states('input_boolean.boolean_home') == 'on' %}
              Home
          {% elif states('input_boolean.boolean_away') == 'on' %}
              Away
          {% elif states('input_boolean.boolean_sleep') == 'on' %}
              Sleep
          {% elif states('input_boolean.boolean_evening_time') == 'on' %}
              Evening Time
          {% elif states('input_boolean.boolean_nap_time') == 'on' %}
              Nap Time
          {% elif states('input_boolean.boolean_movie_time') == 'on' %}
              Movie Time
          {% else %}
              None
          {% endif %}

  - platform: template
    sensors:
      sub_mode_state:
        value_template: >-
          {% if states('input_boolean.boolean_shower_time') == 'on' %}
              Shower Time
          {% elif states('input_boolean.boolean_early_morning') == 'on' %}
              Early Morning
          {% elif states('input_boolean.boolean_kids_shower_time') == 'on' %}
              Kids Shower Time
          {% elif states('input_boolean.boolean_getting_dressed') == 'on' %}
              Getting Dressed
          {% elif states('input_boolean.boolean_active_outside') == 'on' %}
              Active Outside
          {% elif states('input_boolean.boolean_day_time_sleep') == 'on' %}
              Day Time Sleep
          {% elif states('input_boolean.boolean_kids_home') == 'on' %}
              Armed Kids Home
          {% elif states('input_boolean.boolean_play_xbox') == 'on' %}
              Playing Xbox
          {% elif states('input_boolean.boolean_play_ps4') == 'on' %}
              Playing PS4
          {% else %}
              N/A
          {% endif %}

  - platform: template
    sensors:
      privacy_mode_state:
        value_template: >-
          {% if states('input_boolean.boolean_privacy') == 'on' %}
              On
          {% else %}
              Off
          {% endif %}
