homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'mode_main_nap'
            
    script.nap_time:
      friendly_name: Nap
      icon: mdi:sleep

#########################################################################################
#                                                                                   #####
#                  Nap Time Mode                                                    #####
#                                                                                   #####
#########################################################################################
script:
  nap_time:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_main_modes_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_nap_time
      - service: climate.set_hold_mode
        data:
          entity_id: climate.thermostat
          hold_mode: "sleep"
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Nap Time'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.stereo
          volume_level: '.99'
      - service: switch.turn_off
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:05'
      - service: light.turn_off
        data:
          entity_id: light.lamps
      - service: light.turn_on
        data:
          entity_id: light.dawns_lamp
          color_temp: 426
          brightness: 125
      - service: light.turn_off
        data:
          entity_id: light.kitchen
      - service: light.turn_off
        data:
          entity_id: light.master_hallway
      - service: light.turn_off
        data:
          entity_id: light.bathroom
      - service: light.turn_off
        data:
          entity_id: light.master
