homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'modes_main_sleep'

    input_boolean.boolean_sleep:
      friendly_name: Sleep
      hasska_hidden: true

    input_number.sleep_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.sleep_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.sleep_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.onkyo_volume_sleepmode:
      friendly_name: Onkyo Volume Early Morning
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.sleep_mode_chromecast_livingroom:
      friendly_name: Chrome Cast LV Volume Early Morning
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true

    script.lamps_on:
      friendly_name: Sleep
      icon: mdi:sleep
      haaska_name: Sleep

#########################################################################################
#                                                                                   #####
#                   Sleep Mode                                                      #####
#                                                                                   #####
#########################################################################################

input_boolean:
  boolean_sleep:
    initial: off

input_number:
  sleep_mode_brightness_value:
    name: Sleep Mode Brightness
    initial: 20
    min: 0
    max: 100
    step: 1
  sleep_mode_color_temp_value:
    name: Sleep Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
  sleep_mode_transition_value:
    name: Sleep Mode Transition
    initial: 30
    min: 1
    max: 90
    step: 1
  sleep_mode_chromecast_livingroom:
    name: Early Morning Chrome Cast living room
    initial: .3
    min: 0
    max: 1
    step: .1
  onkyo_volume_sleepmode:
    name: Onkyo Volume
    initial: .6
    min: 0
    max: 1.75
    step: .1
      
script:
  lamps_on:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_main_modes_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_sleep
      - delay: '00:00:03'
      - service: climate.set_hold_mode
        data:
          entity_id: climate.thermostat
          hold_mode: "sleep"
      - delay: '00:00:02'
      - service: remote.turn_off
        data:
          entity_id: remote.entertainment
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Good Night'
      - service: fan.turn_off
        data:
          entity_id: fan.living_room_fan
      - service: light.turn_on
        data:
          entity_id: light.master_hallway
          color_temp: 426
          brightness: 125
      - service: light.turn_on
        data:
          entity_id: light.master_table_lamps
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 426
          brightness: 125
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_sleep_on
      - service: switch.turn_off
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:10'
      - service: light.turn_off
        data:
          entity_id: light.lamps
      - service: light.turn_on
        data:
          entity_id: light.dawns_lamp
          color_temp: 426
          brightness: 125
      - delay: '00:00:10'
      - service: script.turn_on
        entity_id: script.led_off
      - delay: '00:00:10'
      - wait_template: "{{ states.binary_sensor.hallway_motion.state == 'off' }}"
      - service: light.turn_off
        data:
          entity_id: light.master_hallway
      - delay: '00:01:15'
#      - wait_template: "{{ states.binary_sensor.motion_sensor_master_bath.state == 'off' }}"
      - wait_template: "{{ states.binary_sensor.master_motion.state == 'off' }}"
      - service: light.turn_off
        data:
          entity_id: light.bathroom
      - delay: '00:00:45'
      - wait_template: "{{ states.binary_sensor.master_motion.state == 'off' }}"
      - service: light.turn_off
        data:
          entity_id: light.master_table_lamps
          transition: 45
      - service: rest_command.sleep
      - service: rest_command.sleep
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on

# rest_command changes profile on blue iris
