homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'daytime_sleep'

    script.daytime_sleep_mode:
      haaska_hidden: false
      hidden: false
      persistence: false
      friendly_name: Daytime Sleep
      haaska_name: Daytime Sleep
      icon: mdi:sleep

script:
  daytime_sleep_mode:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.master
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_day_time_sleep
      - service: automation.turn_off
        data:
          entity_id: automation.motion_master_bedroom
      - delay: '00:02:00'
      - service: light.turn_off
        data:
          entity_id: light.master
      - service: light.turn_off
        data:
          entity_id: light.master_table_lamps
