homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'mode_main_evening_time'

    input_boolean.boolean_evening_time:
      friendly_name: Evening Time
      hasska_hidden: true

    input_number.evening_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.evening_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
#    input_number.evening_mode_transition_value:
    input_number.evening_time_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.evening_time_off:
      friendly_name: Light Turn Off Timer
      persistent: true
    input_number.evening_mode_chromecast_lv:
      friendly_name: Chrome Cast Living Room Value
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.evening_mode_chromecast_masterbedroom:
      friendly_name: Chrome Cast Master Bedroom
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true

    script.evening_time:
      friendly_name: Evening Time
      haaska_name: Evening Time
    automation.evening_time_turn_on:
      haaska_hidden: true
      friendly_name: Evening Time Automation

input_boolean:
  boolean_evening_time:
    initial: off

input_number:
  evening_mode_brightness_value:
    name: Evening Mode Brightness
    initial: 50
    min: 0
    max: 100
    step: 1
  evening_mode_color_temp_value:
    name: Evening Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
#  evening_mode_transition_value:
  evening_time_mode_transition_value:
    name: Evening Mode Transition
    initial: 15
    min: 0
    max: 90
    step: 1
  evening_time_off:
    name: Evening Mode Timer
    initial: 3
    min: 1
    max: 15
    step: 1
  evening_mode_chromecast_lv:
    name: Evening Time TTS Living Room
    initial: .60
    min: 0
    max: 1
    step: .1
  evening_mode_chromecast_masterbedroom:
    name: Evening Time Mode TTS Master Bedroom
    initial: .30
    min: 0
    max: 1
    step: .1
########## Evening Time ##############
automation:
  - alias: evening_time_turn_on
    initial_state: 'on'
    trigger:
      - platform: time
        at: '18:01:00'
    condition:
      - condition: state
        entity_id: sensor.house_mode_state
        state: 'Home'
    action:
     - service: script.evening_time


script:
#  - alias: Evening Time
    evening_time:
      sequence:
        - service: input_boolean.turn_off
          data:
            entity_id: group.input_boolean_main_modes_card
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.boolean_evening_time
        - service: light.turn_on
          data:
            entity_id: light.lamps
            color_temp: 426
            brightness: 125
        - service: light.turn_off
          entity_id:
            - light.living_room_lamp_1
            - light.living_room_lamp_3
            - light.living_room_lamp_4
        - service: script.turn_on
          entity_id: script.blinds_halfway
        - service: script.turn_on
          entity_id: script.vas_dashboard
        - service: script.turn_on
          entity_id: script.led_john_deeer_bookshelf_off                
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.ha_speaker
            volume_level: '{{ states.input_number.evening_mode_chromecast_lv.state }}'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.master_bedroom_cast
            volume_level: '{{ states.input_number.evening_mode_chromecast_masterbedroom.state }}'
        - service: tts.google_say
          data:
            entity_id: media_player.ha_speaker
            message: 'Grandma Mode is Activated'
        - service: tts.google_say
          data:
            entity_id: media_player.master_bedroom_cast
            message: 'Grandma Mode is Activated'
        - service: light.turn_on
          entity_id: light.gateway_light_xiaomi_lv
#  - alias: Navigate Dashboard to Vas
    vas_dashboard:
      sequence:
        - event: hadashboard
          event_data:
            command: navigate
#          timeout: 60
            target: vas
