homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'mode_main_nap'

    input_boolean.boolean_nap_time:
      friendly_name: Nap Time
      hasska_hidden: true

    input_number.nap_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.nap_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.nap_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true

    script.nap_time:
      friendly_name: Nap
      icon: mdi:sleep

#########################################################################################
#                                                                                   #####
#                  Nap Time Mode                                                    #####
#                                                                                   #####
#########################################################################################
input_boolean:
  boolean_nap_time:
    initial: off

input_number:
  nap_mode_brightness_value:
    name: Nap Mode Brightness
    initial: 60
    min: 0
    max: 100
    step: 1
  nap_mode_color_temp_value:
    name: Nap Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
  nap_mode_transition_value:
    name: Nap Mode Transition
    initial: 20
    min: 1
    max: 90
    step: 1

script:
  nap_time:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_main_modes_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_nap_time
      - service: climate.set_hold_mode
        data:
          entity_id: climate.thermostat
          hold_mode: "sleep"
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Nap Time'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.stereo
          volume_level: '.25'
      - service: switch.turn_off
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:05'
      - service: light.turn_off
        data:
          entity_id: light.lamps
      - service: light.turn_on
        data:
          entity_id: light.dawns_lamp
          color_temp: 426
          brightness: 125
      - service: light.turn_off
        data:
          entity_id:
            - light.kitchen
            - light.master_hallway
            - light.bathroom
