homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'network_unifi_poe'
    switch.backdoor:
      friendly_name: Back Door Camera
      icon: mdi:cctv

group:
  unifi_poe_card:
   name: Unifi Poe Switches
   control: hidden
   entities:
     - switch.backdoor
