homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Master Bedroom'
    automation.motion_master_lights_on:
      haaska_hidden: true
      hidden: false
      persistence: true
      friendly_name: Master Lights On
    automation.motion_master_bedroom_motion_off:
      haaska_hidden: true
      hidden: false
      persistence: true
      friendly_name: Master Bedroom Automate Off
    automation.master_bedroom_home_mode:
      haaska_hidden: true
      hidden: false
      persistence: true
      friendly_name: Master Bedroom Home Mode
    binary_sensor.master_motion:
      friendly_name: Master Motion Sensor
      device_class: motion
    sensor.motion_sensor_master_battery:
      icon: mdi:battery
      friendly_name: Master Motion Sensor
      unit_of_measurement: '%'
    sensor.dawns_controller_wifi_signal:
      icon: mdi:signal
    sensor.illumination_master_bedroom:
      friendly_name: Master Bedroom Light Level
      icon: mdi:theme-light-dark
    light.dawns_bedside_lamp:
      friendly_name: Dawns Side
    light.herbs_bedside_lamp:
      friendly_name: Herbs Side
    switch.dawn_night:
      friendly_name: Dawns controls Night
      haaska_name: Bedroom Fan
      icon: mdi:fan
    light.master_bedroom_fan:
      friendly_name: Master Bedroom Main Light
      haaska_name: Main Light
      icon: mdi:lightbulb

sensor:
  - platform: template
    sensors:
      motion_sensor_master_battery:
        friendly_name: 'Master Bedroom Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.master_motion', 'battery_level') }}"
  - platform: template
    sensors:
      master_bath_motion_sensor_batt:
        friendly_name: 'Master Bathroom Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.motion_sensor_master_bath', 'battery_level') }}"
  - platform: template
    sensors:
      master_humidity_sensor_batt:
        friendly_name: 'Master Bathroom Humidity Sensor Battery Level'
        value_template: "{{ state_attr('sensor.humidity_master_bathroom', 'battery_level') }}"
  - platform: mqtt
    state_topic: "dawns/Wifi Connect/wifi"
    unit_of_measurement: 'dbm'
    name: Dawns Controller Wifi Signal

switch:
  - platform: mqtt
    name: "dawn_night"
    state_topic: "dawns/relay1/state"
    command_topic: "dawns/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

#######################################################################################################
#####    When home mode set on ecobee then master light turns on in bedroom (not while sleeping  ######
#####    ie house is in sleep mode                                                               ######
#####    use case app only allows set times and we go to bed at diff times                       ######
#######################################################################################################

automation:
  - alias: motion_master_lights_on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'off'
      - condition: state
        entity_id: input_boolean.boolean_day_time_sleep
        state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.master_table_lamps
          color_temp: >-
             {% if is_state("input_boolean.boolean_evening_time", "on") %}
             {{ states('input_number.evening_mode_color_temp_value') | int }}
             {% elif is_state("input_boolean.boolean_movie_time", "on") %}
             {{ states('input_number.movie_mode_color_temp_value') | int }}
             {% elif is_state("input_boolean.boolean_home", "on") %}
             {{ states('input_number.home_mode_color_temp_value') | int }}
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
              {{ states('input_number.nap_mode_color_temp_value') | int }}
             {% else %}
               180
             {% endif %}
          brightness_pct: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
              {{ states('input_number.evening_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
              {{ states('input_number.movie_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_home", "on") %}
              {{ states('input_number.home_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
              {{ states('input_number.nap_mode_brightness_value') | int }}
              {% else %}
                100
              {% endif %}
      - service: light.turn_on
        data_template:
          entity_id:
            - light.master_bedroom_fan
          brightness: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
               100
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
               100
              {% elif is_state("input_boolean.boolean_home", "on") %}
               254
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
               100
              {% else %}
               254
              {% endif %}

  - alias: Motion Master Bedroom Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'off'
        for: '00:03:00'
    action:
      - service: light.turn_off
        entity_id:
          - light.master_table_lamps
          - light.master_bedroom_fan

  - alias: Master Bedroom Sleep mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_sleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.boolean_day_time_sleep
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.dawn_night
      - service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_fan
          speed: "high"

  - alias: Master Bedroom Home mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.dawn_night
      - service: switch.turn_on
        entity_id: switch.wemo_master_bedroom_mixer
      - service: fan.turn_off
        data:
          entity_id: fan.master_bedroom_fan
