##### I use this for a group view with entities are in different packages....If in one package group
##### view is in there
homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'room_room_groups'

group:
 livingroom_card:
    control: hidden
    name: Living Room
    entities:
     - light.lamps
     - light.herbs_lamp
     - light.dawns_lamp
     - light.door_lamp
     - fan.living_room_fan
     - script.living_room_fan_auto
     - sensor.fan_speed
     - binary_sensor.gang
     - script.refresh_wink
     - automation.fan_low_with_hvac_automation
     - automation.fan_medium_with_hvac_automation
     - automation.reenable_fan_automation
     - switch.fan_override
     - automation.evening_time_turn_on
     - light.light_bulb
     - automation.evening_time
     - script.evening_time
     - script.movie_time
     - automation.back_to_white_after_motion
     - automation.back_to_yellow_dim_after_motion
     - script.nap_time
     - script.front_cam_dashboard
     - script.vas_dashboard
     - switch.dawns_scent
     - binary_sensor.door_window_sensor_front_door
     - sensor.front_door_sensor_batt
     - binary_sensor.door_window_sensor_livingroom_front
     - sensor.livingroom_front_window_sensor_batt

 carport_lights_card:
    control: hidden
    name: Carport
    entities:
      - light.carport
      - light.front_steps
      - light.rear_steps
      - automation.porch_lights_on
      - automation.porch_lights_off
      - automation.front_carport_bright_and_white_on_motion
      - automation.front_back_to_yellow_dim_after_Motion
      - script.front_bright_outside
      - script.front_normal_outside



 laundry_room_card:
   control: hidden
   name: Laundry Room
   entities:
      - binary_sensor.door_window_sensor_back_door
      - light.laundry_room
      - binary_sensor.laundry_room_motion
      - sensor.motion_sensor_laundry_battery
      - sensor.laundry_temperature
      - sensor.motion_sensor_laundry_lux
      - automation.laundry_motion_homeMode
      - automation.laundry_motion_not_homeMode
      - automation.laundry_motion_off
      - switch.wemo_washing_machine
      - sensor.washing_machine_watts
      - sensor.washing_machine_power_up
      - sensor.washing_machine_power_down
      - input_boolean.stopwatch
      - input_boolean.dummy
      - input_boolean.washer_switch
      - sensor.stopwatch
      - sensor.washer_status
      - automation.washer_start
      - automation.washer_done
      - automation.stopwatch_start
      - automation.stopwatch_stop
      - automation.stopwatch_update

 master_hallway_card:
   control: hidden
   name: Master Hallway
   entities:
     - light.master_hallway
     - sensor.motion_sensor_hallway_battery
     - binary_sensor.hallway_motion
     - sensor.hallway_temperature
     - sensor.master_hallway_motion_sensor_lux
     - automation.motion_master_hallway_motion_on
     - automation.motion_master_hallway_motion_off

 kids_hallway_card:
   control: hidden
   name: Kids Hallway
   entities:
     - light.kids_hallway
     - sensor.motion_sensor_hallway_battery
     - binary_sensor.kids_hallway_motion
     - sensor.kids_hallway_temperature
     - sensor.kids_hallway_motion_sensor_lux
     - automation.motion_kids_hallway_motion_on
     - automation.motion_kids_hallway_motion_off

 ruths_room_card:
   control: hidden
   name: Ruths Room
   entities:
     - group.ruths_blinds_card
     - binary_sensor.door_window_sensor_ruths_room
     - sensor.ruths_window_sensor_batt
