homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'living_room'
    sensor.front_blinds_controller_wifi_signal:
      icon: mdi:signal
      haaska_hidden: true
    sensor.couch_blinds_controller_wifi_signal:
      icon: mdi:signal
      friendly_name: Couch Blinds WIFI
      haaska_hidden: true
    binary_sensor.door_window_sensor_front_door:
      haaska_hidden: true
      friendly_name: Front Door
      device_class: door
    sensor.front_door_sensor_batt:
      haaska_hidden: true
      friendly_name: Front Door Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_livingroom_front:
      haaska_hidden: true
      friendly_name: LV Front Window Sensor
      device_class: window
    sensor.livingroom_front_window_sensor_batt:
      haaska_hidden: true
      friendly_name: LV Front Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_lv_window_dawn:
      haaska_hidden: true
      friendly_name: LV Rear Dawns Side Window
      device_class: window
    sensor.door_window_sensor_lv_window_dawn_batt:
      haaska_hidden: true
      friendly_name: LV Rear Dawns Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.door_window_sensor_lv_window_herb:
      haaska_hidden: true
      friendly_name: LV Rear Herbs Side Window
      device_class: window
    sensor.door_window_sensor_lv_window_herb_batt:
      haaska_hidden: true
      friendly_name: LV Rear Herbs Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery

light:
  - platform: group
    name: Living Room Pedestal Lamps
    entities:
      - light.living_room_lamp_1
      - light.living_room_lamp_3
      - light.living_room_lamp_4
      - light.living_room_lamp_2
      - light.living_room_lamp_5

sensor:
  - platform: template
    sensors:
      livingroom_front_window_sensor_batt:
        friendly_name: 'Living Room Front Window Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_livingroom_front.attributes.battery_level }}"

  - platform: template
    sensors:
      door_window_sensor_lv_window_dawn_batt:
        value_template: "{{ states.binary_sensor.door_window_sensor_livingroom_front.attributes.battery_level }}"

  - platform: template
    sensors:
      door_window_sensor_lv_window_herb_batt:
        value_template: "{{ states.binary_sensor.door_window_sensor_livingroom_front.attributes.battery_level }}"

  - platform: template
    sensors:
      front_door_sensor_batt:
        friendly_name: 'Front Door Sensor Battery'
        value_template: "{{ state_attr('binary_sensor.door_window_sensor_front_door', 'battery_level') }}"

  - platform: template
    sensors:
      lv_room_rear_blinds_state:
        friendly_name: 'Couch Blinds Status'
        value_template: "{{ states('input_select.lv_room_rear_blinds_status') }}"
  - platform: template
    sensors:
      lv_room_front_blinds_state:
        friendly_name: 'Front Blinds Status'
        value_template: "{{ states('input_select.lv_room_front_blinds_status') }}"
  - platform: mqtt
    state_topic: "esp_couch_blinds/couch_blinds_wifi/wifi"
    unit_of_measurement: 'dbm'
    name: Couch Blinds Controller Wifi Signal

  - platform: mqtt
    state_topic: "lv_room_blindstv_cntlr/lv_front_wifi/wifi"
    unit_of_measurement: 'dbm'
    name: Front Blinds Controller Wifi Signal

automation:
  - alias: Motion Turn on Living Room light Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_tablet_lv_camera
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_indoor_frontdoor
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_lamp_5
          color_temp: 426
          brightness: 50

  - alias: Motion Turn off Living Room light Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_indoor_frontdoor
        to: 'off'
        for: '00:05:00'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.living_room_lamp_5

  - alias: living_room_dimmer_on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_dimmer
        to: 'on'
      - platform: template
        value_template: "{{ state_attr('binary_sensor.living_room_dimmer', 'level') != state_attr('light.lamps', 'brightness') }}"
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.living_room_dimmer
        state: 'on'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: >-
             {% if is_state("input_boolean.boolean_evening_time", "on") %}
               switch.circadian_lighting_circadian_lamps_evening
             {% elif is_state("input_boolean.boolean_home", "on") %}
               switch.circadian_lighting_circadian_lamps
             {% else %}
              switch.circadian_lighting_circadian_lamps
             {% endif %}
      - service: light.turn_on
        entity_id:
          - light.living_room_pedestal_lamps
          - light.lamps
          - light.living_room_main
        data_template:
          brightness: "{{ state_attr('binary_sensor.living_room_dimmer', 'level')}}"

  - alias: living_room_dimmer_off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_dimmer
        to: 'off'
    action:
      - service: switch.turn_on
        data_template:
          entity_id: >-
               {% if is_state("input_boolean.boolean_evening_time", "on") %}
                 switch.circadian_lighting_circadian_lamps_evening
               {% elif is_state("input_boolean.boolean_home", "on") %}
                 switch.circadian_lighting_circadian_lamps
               {% else %}
                switch.circadian_lighting_circadian_lamps
               {% endif %}
      - service: light.turn_off
        entity_id:
          - light.living_room_main
      - service: light.turn_on
        entity_id:
          - light.living_room_pedestal_lamps
          - light.lamps
