homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Master Bathroom'
    automation.master_bath_light_left_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_home_mode_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_home_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_evening_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_sleep_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_sleep_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.master_bath_humidity_fan_on:
      friendly_name: Master Vent On
      haaska_hidden: true
    automation.master_bath_humidity_fan_off:
      friendly_name: Master Vent Off
      haaska_hidden: true
    sensor.master_bathroom_dimmer_state:
      icon: mdi:remote
      haaska_hidden: true
      persistence: false
    sensor.master_bathroom_dimmer_last_update:
      icon: mdi:clock
    sensor.master_bathroom_dimmer_battery:
      icon: mdi:battery
      friendly_name: Master Bath Dimmer
    binary_sensor.bathroom_motion:
      friendly_name: Bathroom Motion
      device_class: motion
    sensor.motion_sensor_bathroom_battery:
      icon: mdi:battery
    sensor.bathroom_temperature:
      friendly_name: Master Bath Temperature
    switch.master_bath_heater:
      friendly_name: Master Bath Heater
      haaska_name: Master Bath Heater
      haaska_hidden: false
    light.bathroom:
      persistence: false
######## Xiaomi ################
    sensor.humidity_master_bathroom:
      friendly_name: Master Bathroom Humidity
      haaska_hidden: true
    sensor.temperature_master_bathroom:
      friendly_name: Master Bathroom Temperature
      haaska_hidden: true
    sensor.master_humidity_sensor_batt:
      haaska_hidden: true
      friendly_name: Master Bathroom Humidity Sensor
      unit_of_measurement: '%'
      icon: mdi:battery
    binary_sensor.motion_sensor_master_bath:
      haaska_hidden: true
      friendly_name: Master Bath Motion
    sensor.illumination_master_bath:
      haaska_hidden: true
      friendly_name: Master Bath Lux
      icon: mdi:theme-light-dark
    sensor.master_bath_motion_sensor_batt:
      icon: mdi:battery
      unit_of_measurement: '%'
    switch.heater_lasko_power:
      haaska_name: Master Bathroom Heater Power
      icon: mdi:power
    switch.heater_lasko_oscillate:
      haaska_name: Bathroom heater Oscillate
      icon: mdi:rotate-3d
    script.bath_heater_on:
      friendly_name: Master Bath Heater On
    script.bath_heater_off:
      friendly_name: Master Bath Heater Off

automation:
  - alias: Motion Bathroom Home Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 154
          brightness: 255

  - alias: Motion Bathroom Evening Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 392
          brightness: 74

  - alias: Motion Bathroom Home Mode off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'off'
        for:
          minutes: 7
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: light.turn_off
        entity_id: light.bathroom

  - alias: Motion Bathroom Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 426
          brightness: 50

  - alias: Motion Bathroom Sleep Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bathroom

  - alias: Master Bath light left on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.bathroom_vanity
        to: 'on'
        for:
          hours: 1
          minutes: 00
          seconds: 00
    action:
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom
###############################################################################
###  vent fan if humidity is over 60 control                            #######
###############################################################################
  - alias: Master Bath Humidity Fan On
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.sensor.humidity_master_bathroom.state > states.input_number.target_humidity_master_bathroom.state }}'
    action:
      - service: switch.turn_on
        entity_id: switch.wemo_master_bath_fan
  - alias: Master Bath Humidity Fan Off
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.sensor.humidity_master_bathroom.state < states.input_number.target_humidity_master_bathroom.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.wemo_master_bath_fan

  - alias: master bath heater state on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.heater_lasko_power
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.heater_lasko_power

  - alias: master bath heater state off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.heater_lasko_power
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.heater_lasko_power

script:
  bath_heater_on:
    sequence:
      - service: switch.turn_on
        entity_id: switch.heater_lasko_power
      - delay: '00:00:05'
      - service: switch.turn_on
        entity_id: switch.heater_lasko_oscillate

  bath_heater_off:
    sequence:
      - service: switch.turn_off
        entity_id: switch.heater_lasko_oscillate
      - delay: '00:00:05'
      - service: switch.turn_off
        entity_id: switch.heater_lasko_power

switch:
  - platform: template
    switches:
      master_bath_heater:
        value_template: "{{ is_state('switch.master_bath_heater', 'On') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.bath_heater_on      #in master_bathroom_broadlink_climate package
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.bath_heater_off      #in master_bathroom_broadlink_climate package
