homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Master Hallway'
    light.master_hallway_1:
      haaska_hidden: true     #hide single bulb its referred to as room name
    sensor.motion_sensor_hallway_battery:
      icon: mdi:battery
      friendly_name: Master Hallway Motion Sensor
    binary_sensor.hallway_motion:
      friendly_name: Hallway Motion
      device_class: motion
    sensor.master_hallway_motion_sensor_lux:
      friendly_name: Master Hallway Light Level
      icon: mdi:theme-light-dark

group:
  master_hallway_card:
    control: hidden
    name: Master Hallway
    entities:
      - light.master_hallway
      - sensor.motion_sensor_hallway_battery
      - binary_sensor.hallway_motion
      - sensor.hallway_temperature
      - sensor.master_hallway_motion_sensor_lux
      - automation.motion_master_hallway_motion_on
      - automation.motion_master_hallway_motion_off

sensor:
  - platform: rest
    resource: !secret MS_rest_11
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Hallway Battery'

  - platform: rest
    resource: !secret MS_rest_11
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Hallway Temperature'

  - platform: rest
    resource: !secret MS_rest_13
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    scan_interval: 5
    name: 'Master Hallway Motion Sensor Lux'


binary_sensor:
  - platform: rest
    resource: !secret MS_rest_12
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: hallway_motion

automation:
  - alias: Motion Master Hallway Motion On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.master_hallway_motion_sensor_lux
        below: '10000'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.master_hallway
          color_temp: >-
            {% if is_state("input_boolean.boolean_evening_time", "on") %}
            {{ states('input_number.evening_mode_color_temp_value') | int }}
            {% elif is_state("input_boolean.boolean_movie_time", "on") %}
            {{ states('input_number.movie_mode_color_temp_value') | int }}
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
            {{ states('input_number.sleep_mode_color_temp_value') | int }}
            {% elif is_state("input_boolean.boolean_early_morning", "on") %}
            {{ states('input_number.earlymorning_mode_color_temp_value') | int }}
            {% elif is_state("input_boolean.boolean_home", "on") %}
            {{ states('input_number.home_mode_color_temp_value') | int }}
            {% elif is_state("input_boolean.boolean_nap_time", "on") %}
            {{ states('input_number.nap_mode_color_temp_value') | int }}
            {% else %}
             180
            {% endif %}
          brightness_pct: >-
            {% if is_state("input_boolean.boolean_evening_time", "on") %}
            {{ states('input_number.evening_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_movie_time", "on") %}
            {{ states('input_number.movie_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
            {{ states('input_number.sleep_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_early_morning", "on") %}
            {{ states('input_number.earlymorning_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_home", "on") %}
            {{ states('input_number.home_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_nap_time", "on") %}
            {{ states('input_number.nap_mode_brightness_value') | int }}
            {% else %}
              100
            {% endif %}

  - alias: Motion Master Hallway Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: 'off'
        for: '00:01:00'
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.master_hallway
          transition: >-
            {% if is_state("input_boolean.boolean_evening_time", "on") %}
            {{ states('input_number.evening_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_movie_time", "on") %}
            {{ states('input_number.movie_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
            {{ states('input_number.sleep_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_early_morning", "on") %}
            {{ states('input_number.earlymorning_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_home", "on") %}
            {{ states('input_number.home_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_nap_time", "on") %}
            {{ states('input_number.nap_mode_transition_value') | int }}
            {% else %}
              15
            {% endif %}
