homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'kids_room_sensor_watchdog'

input_boolean:
  boolean_kids_sensor_watchdog:
    initial: off

input_text:
  kids_bedroom_device_battery:
    name: Kids Bedroom Sensor

automation:
  - alias: 'notify_sensor_battery_low'
    initial_state: 'true'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.kids_window_sensor_batt
          - sensor.motion_sensor_kids_room_battery
          - sensor.kids_room_sensor_batt
          - sensor.kids_room_dimmer_battery
        below: 30
      - platform: state
        entity_id:
          - sensor.kids_room_temperature
          - sensor.kids_window_sensor_batt
          - sensor.motion_sensor_kids_room_battery
          - sensor.kids_room_sensor_batt
          - sensor.kids_room_dimmer_battery
        to: unknown
    action:
      - service_template: >
          {% if trigger.to_state.state | int < 30 %}
            input_boolean.turn_on
          {% elif trigger.to_state.state | lower == "unknown" %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.boolean_kids_sensor_watchdog
      - service: input_text.set_value
        data_template:
          entity_id: input_text.kids_bedroom_device_battery
          value: "{{ trigger.to_state.attributes.friendly_name }}"
      - service: shell_command.kids_sensor_dash
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - wait_template: "{{ states.media_player.ha_speaker.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id:
            - media_player.kids_room_cast
            - media_player.ha_speaker
          message: >
            {% if trigger.to_state.state | int < 30 %}
              {{ trigger.to_state.attributes.friendly_name }} has a low Battery Please Check Dashboard!
            {% elif trigger.to_state.state | lower == "unknown" %}
              {{ trigger.to_state.attributes.friendly_name }} has become Unknown Please Check Dashboard!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has been restored
            {% endif %}

  - alias: 'kids_annouce_sensor_issue'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_kids_bedroom
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_kids_sensor_watchdog
        state: 'on'
    action:
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "The {{ states('input_text.kids_bedroom_device_battery') }} has a problem in your room"
      - service: shell_command.kids_sensor_dash


  - alias: 'kids_clear_sensor_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_kids_sensor_watchdog
        to: 'off'
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.kids_bedroom_device_battery
          value: "All Good"
      - service: shell_command.gabbies_dash
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Thank You for Fixing Me Returning to main dash"
