homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Shed'
automation:
  - alias: 'shed_opened_no_alarm_set'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_shed_door
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_active_outside
          state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker, media_player.master_bedroom_cast
          message: 'The Shed has been Opened'
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_mac
          ringtone_id: 1
          ringtone_vol: 100
      - service: notify.pushbullet
        data:
          message: 'Shed Door Has Been Opened'
                     
