homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'master_bathroom_device_watchdog'

input_boolean:
  boolean_master_bathroom_netork_watchdog:
    initial: off

input_text:
  master_bathroom_device_watchdog:
    name: Master Bathroom Device 

automation:
  - alias: 'notify_master_bath_device_status'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.wemo_master_bath_vanity
          - binary_sensor.wemo_master_bath_fan
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: >
            {% if trigger.to_state.state | lower == "off" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline Please Check Dashboard!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
      - service_template: >
          {% if trigger.to_state.state | lower == "off" %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.boolean_master_bathroom_netork_watchdog
      - service: input_text.set_value
        data_template:
          entity_id: input_text.master_bathroom_device_watchdog
          value: "{{ trigger.to_state.attributes.friendly_name }}"

  - alias: 'master_bathroom_annouce_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_master_bathroom_netork_watchdog
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "The {{ states('input_text.master_bathroom_device_watchdog') }} is offline in your room"
      - service: shell_command.master_network_alert_dash

  - alias: 'master_clear_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_master_bathroom_netork_watchdog
        to: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "Thank You for Fixing Me Returning to main dash"
      - service: input_text.set_value
        data_template:
          entity_id: input_text.master_bathroom_device_watchdog
          value: "All Good"
      - service: shell_command.master_dash
