homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'master_bathroom_sensor_watchdog'

input_boolean:
  boolean_master_bath_sensor_watchdog:
    initial: off

automation:
  - alias: 'notify_sensor_battery_low_master_bath'
    initial_state: 'true'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.master_bath_motion_sensor_batt
          - sensor.master_humidity_sensor_batt
        below: 30
      - platform: state
        entity_id:
          - sensor.master_bath_motion_sensor_batt
          - sensor.master_humidity_sensor_batt
        to: 'unknown'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_master_bath_sensor_watchdog
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "There is a problem with a sensor battery in Bath room"
      - service: shell_command.master_dash_wake_up
      - delay: '00:00:10'
      - service: shell_command.master_battery_alert_dash

  - alias: 'master_bath_annouce_sensor_issue'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_master_bath_sensor_watchdog
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "There is a problem with a sensor in Bath room"
      - service: shell_command.master_dash_wake_up
      - delay: '00:00:10'
      - service: shell_command.master_dash
