homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Gabbies Room'
    light.kids_main:
      haaska_name: Kids Light
      friendly_name: Kids Light
    light.gabbies_light:
      haaska_name: Kids Lamp
      friendly_name: Kids Lamp
    binary_sensor.gabbies_room_motion:
      haaska_hidden: true
      device_class: motion
      friendly_name: Gabbies Room Motion
    sensor.motion_sensor_gabbies_room_battery:
      icon: mdi:battery
      unit_of_measurement: '%'
    sensor.illumination_gabbies_room_motion_sensor:
      friendly_name: Gabbies Room Light Level
      icon: mdi:theme-light-dark
    sensor.gabbie_status:
      friendly_name: Gabbie
      icon: mdi:human-child
      haaska_hidden: true
    sensor.kids_room_mode:
      friendly_name: Kids Room Mode
      icon: mdi:human-child
      haaska_hidden: true
    sensor.esp_kids_tv_state_wifi_signal:
      icon: mdi:signal
      friendly_name: Kids Tv State
    sensor.esp_kids_blinds_wifi_signal:
      icon: mdi:signal
      friendly_name: Kids Blinds WIFI
    input_boolean.boolean_gabbie_home:
      friendly_name: Gabbie Home
      haaska_hidden: true
      icon: mdi:human-child
      persistent: true
    input_boolean.boolean_gabbie_awake:
      friendly_name: Gabbie Awake
      haaska_hidden: true
      icon: mdi:sleep-off
      persistent: true
    input_boolean.boolean_gabbie_sleep:
      friendly_name: Gabbie Sleep
      haaska_hidden: true
      icon: mdi:sleep
      persistent: true
    script.gabbies_bedtime:
      friendly_name: Gabbies Bedtime
      icon: mdi:sleep
      haaska_name: Gabbies Bedtime
    script.gabbies_awake:
      friendly_name: Gabbie Awake
      icon: mdi:sleep-off
      haaska_name: Gabbie Awake
    script.watch_roku:
      friendly_name: Watch TV
      haaska_name: Watch TV
    automation.gabbie_going_sleep:
      friendly_name: Gabbie Going Asleep
      haaska_hidden: true
    automation.gabbie_waking_up:
      friendly_name: Gabbie Waking Up
      haaska_hidden: true
    automation.gabbie_home:
      friendly_name: Gabbie Home
      haaska_hidden: true
    automation.gabbie_not_home:
      friendly_name: Gabbie Gone
      haaska_hidden: true
    automation.kids_light_on:
      friendly_name: Gabbies Light On
      haaska_hidden: true
    automation.kids_light_off:
      friendly_name: Gabbies Light Off
      haaska_hidden: true


input_boolean:
  boolean_gabbie_home:
    initial: off
  boolean_gabbie_sleep:
    initial: off
  boolean_gabbie_awake:
    initial: off

sensor:
  - platform: template
    sensors:
      gabbie_status:
        value_template: '{% if is_state("input_boolean.boolean_gabbie_home", "on") %}Home{% else %}Gone{% endif %}'
  - platform: template
    sensors:
      kids_room_mode:
        value_template: '{% if is_state("input_boolean.boolean_gabbie_sleep", "on") %}Sleep{% else %}Awake{% endif %}'
  - platform: template
    sensors:
      motion_sensor_gabbies_room_battery:
        friendly_name: 'Gabbies Room Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.gabbies_room_motion', 'battery_level') }}"
  - platform: mqtt
    state_topic: "esp_kids_tv_state/Wifi Connect/wifi"
    unit_of_measurement: 'dbm'
    name: esp_kids_tv_state_wifi_signal



automation:
  - alias: 'gabbie_home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_home
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.kodi
          message: 'Welcome Home Gabbie'

  - alias: 'gabbie_not_home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_home
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
       - service: tts.google_say
         data:
           entity_id:
             - media_player.ha_speaker
             - media_player.kids_room_cast
           message: 'Goodbye Gabbie'

  - alias: 'gabbie_going_sleep'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_sleep
        to: 'on'
      - platform: time
        at: '21:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
       - service: tts.google_say
         data:
           entity_id:
             - media_player.ha_speaker
             - media_player.kids_room_cast
           message: 'Goodnight Gabbie'
       - service: script.turn_on
         entity_id: script.gabbies_bedtime

  - alias: 'gabbie_waking_up'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_gabbie_awake
        to: 'on'
      - platform: time
        at: '08:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.ha_start
        state: 'off'
    action:
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.kids_room_cast
          message: 'Goodmorning Gabbie'
      - service: script.turn_on
        entity_id: script.gabbies_awake


  - alias: 'kids_light_on'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.gabbies_room_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_gabbie_awake
        state: 'on'
    action:
       - service: light.turn_on
         data_template:
           entity_id:
             - light.gabbies_light
             - light.kids_main
           brightness_pct: >-
             {% if is_state("input_boolean.boolean_evening_time", "on") %}
             {{ states('input_number.evening_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_movie_time", "on") %}
             {{ states('input_number.movie_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_sleep", "on") %}
             {{ states('input_number.sleep_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_early_morning", "on") %}
             {{ states('input_number.earlymorning_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_home", "on") %}
             {{ states('input_number.home_mode_brightness_value') | int }}
             {% elif is_state("input_boolean.boolean_nap_time", "on") %}
             {{ states('input_number.nap_mode_brightness_value') | int }}
             {% else %}
               100
             {% endif %}

  - alias: 'kids_light_off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.gabbies_room_motion
        to: 'off'
        for: '00:05:00'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_gabbie_awake
        state: 'on'
    action:
       - service: light.turn_off
         entity_id:
           - light.gabbies_light
           - light.kids_main

  - alias: 'kids_room_xbox_on'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.xboxone_ping
        to: 'home'
    action:
      - service: media_player.turn_on
        entity_id: media_player.kids_room_tv
      - delay: '00:00:20'
      - service: media_player.select_source
        data:
          entity_id: media_player.kids_room_tv
          source: HDMI Side

  - alias: 'kids_room_xbox_off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.xboxone_ping
        to: 'not_home'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.kids_room_tv
          source: HDMI

script:
  gabbies_bedtime:
    sequence:
      - service: light.turn_on
        entity_id: light.gabbies_light
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_gabbie_sleep
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_gabbie_awake
      - service: switch.turn_on
        entity_id: switch.wemo_kids_fan
      - delay: '00:05:00'
      - service: light.turn_off
        data:
          entity_id:
            - light.gabbies_light
            - light.kids_main
          transition: 45

  gabbies_awake:
    sequence:
      - service: light.turn_on
        entity_id: light.gabbies_light
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_gabbie_sleep
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_gabbie_awake
      - delay: '00:00:10'
      - service: light.turn_off
        data:
          entity_id: light.gabbies_light
          transition: 180
      - service: switch.turn_off
        entity_id: switch.wemo_kids_fan

  watch_roku:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.kids_room_tv
      - delay: '00:00:20'
      - service: media_player.select_source
        data:
          entity_id: media_player.kids_room_tv
          source: HDMI
