homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Master Bathroom'
    automation.master_bath_light_left_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_master_bath_lights_on:
      haaska_hidden: true
      hidden: false
      friendly_name: Master Bath Lights On
    automation.motion_master_bathroom_motion_off:
      haaska_hidden: true
      hidden: false
      friendly_name: Master Bath Lights Off
    automation.master_bath_humidity_fan_on:
      friendly_name: Master Vent On
      haaska_hidden: true
    automation.master_bath_humidity_fan_off:
      friendly_name: Master Vent Off
      haaska_hidden: true
    binary_sensor.bathroom_motion:
      friendly_name: Bathroom Motion
      device_class: motion
    sensor.motion_sensor_bathroom_battery:
      icon: mdi:battery
    switch.master_bath_heater:
      friendly_name: Master Bath Heater
      haaska_name: Master Bath Heater
      haaska_hidden: false
    light.bathroom:
      persistence: false
######## Xiaomi ################
    binary_sensor.motion_sensor_master_bath:
      haaska_hidden: true
      friendly_name: Master Bath Motion
    sensor.illumination_master_bath:
      haaska_hidden: true
      friendly_name: Master Bath Lux
      icon: mdi:theme-light-dark
    sensor.master_bath_motion_sensor_batt:
      icon: mdi:battery
      unit_of_measurement: '%'
    switch.heater_lasko_power:
      haaska_name: Master Bathroom Heater Power
      icon: mdi:power
    switch.heater_lasko_oscillate:
      haaska_name: Bathroom heater Oscillate
      icon: mdi:rotate-3d
    script.bath_heater_on:
      friendly_name: Master Bath Heater On
    script.bath_heater_off:
      friendly_name: Master Bath Heater Off

automation:
  - alias: motion_master_bath_lights_on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_master_bath
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.bathroom
          color_temp: >-
             {% if is_state("input_boolean.boolean_evening_time", "on") %}
             {{ states('input_number.evening_mode_color_temp_value') | int }}
             {% elif is_state("input_boolean.boolean_movie_time", "on") %}
             {{ states('input_number.movie_mode_color_temp_value') | int }}
             {% elif is_state("input_boolean.boolean_home", "on") %}
             {{ states('input_number.home_mode_color_temp_value') | int }}
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
              {{ states('input_number.nap_mode_color_temp_value') | int }}
              {% elif is_state("input_boolean.boolean_sleep", "on") %}
              {{ states('input_number.sleep_mode_color_temp_value') | int }}
             {% else %}
               180
             {% endif %}
          brightness_pct: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
              {{ states('input_number.evening_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
              {{ states('input_number.movie_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_home", "on") %}
              {{ states('input_number.home_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
              {{ states('input_number.nap_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_sleep", "on") %}
              {{ states('input_number.sleep_mode_brightness_value') | int }}
              {% else %}
                100
              {% endif %}

  - alias: motion_master_bathroom_motion_off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'off'
        for: '00:05:00'
    action:
      - service: light.turn_off
        entity_id:
          - light.bathroom

  - alias: Master Bath light left on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.bathroom_vanity
        to: 'on'
        for:
          hours: 1
          minutes: 00
          seconds: 00
    action:
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom
###############################################################################
###  vent fan if humidity is over 60 control                            #######
###############################################################################
  - alias: Master Bath Humidity Fan On
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.sensor.master_bath_humidity.state > states.input_number.target_humidity_master_bathroom.state }}'
    action:
      - service: switch.turn_on
        entity_id: switch.wemo_master_bath_fan
  - alias: Master Bath Humidity Fan Off
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.sensor.master_bath_humidity.state < states.input_number.target_humidity_master_bathroom.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.wemo_master_bath_fan

  - alias: master bath heater state on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.heater_lasko_power
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.heater_lasko_power


  - alias: master bath heater state off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.heater_lasko_power
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.heater_lasko_power

script:
  bath_heater_on:
    sequence:
      - service: switch.turn_on
        entity_id: switch.heater_lasko_power
      - delay: '00:00:05'
      - service: switch.turn_on
        entity_id: switch.heater_lasko_oscillate

  bath_heater_off:
    sequence:
      - service: switch.turn_off
        entity_id: switch.heater_lasko_oscillate
      - delay: '00:00:05'
      - service: switch.turn_off
        entity_id: switch.heater_lasko_power

switch:
  - platform: template
    switches:
      master_bath_heater:
        value_template: "{{ is_state('switch.master_bath_heater', 'On') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.bath_heater_on      #in master_bathroom_broadlink_climate package
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.bath_heater_off      #in master_bathroom_broadlink_climate package
