homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'ruths_room'
############ xioomi window sensor #################
    binary_sensor.door_window_sensor_ruths_room:
      haaska_hidden: true
      friendly_name: Ruths Window Sensor
      device_class: window
    sensor.ruths_window_sensor_batt:
      haaska_hidden: true
      friendly_name: Ruths Window Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery
############## xiaomi door sensor ###################
    binary_sensor.door_window_sensor_ruths_room_door:
      haaska_hidden: true
      friendly_name: Ruths Room Door
      device_class: door
    sensor.ruths_room_sensor_batt:
      haaska_hidden: true
      friendly_name: Ruths Room Sensor Battery
      unit_of_measurement: '%'
      icon: mdi:battery

sensor:
  - platform: template
    sensors:
      ruths_window_sensor_batt:
        friendly_name: 'Ruths Window Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_ruths_room_window.attributes.battery_level }}"
  - platform: template
    sensors:
      ruths_room_sensor_batt:
        friendly_name: 'Ruths Room Door Sensor Battery Level'
        value_template: "{{ states.binary_sensor.door_window_sensor_ruths_room_door.attributes.battery_level }}"
