################### Porch lights on at night  ###########################
homeassistant:
  customize:
    automation.porch_lights_on:
      friendly_name: "Porch Lights On"
      haaska_hidden: true
      hidden: false
      persistence: true

    automation.porch_lights_off:
      friendly_name: "Porch Lights Off"
      haaska_hidden: true
      hidden: false
      persistence: true

    automation.front_carport_bright_and_white_on_motion:
      friendly_name: "Front Porch Lights White On Motion"
      haaska_hidden: true
      hidden: false
      persistence: true

    automation.front_back_to_yellow_dim_after_Motion:
      friendly_name: "Front Porch Lights Yellow No Motion"
      haaska_hidden: true
      hidden: false
      persistence: true

    automation.back_carport_bright_and_white_on_motion:
      friendly_name: "Front Porch Lights White On Motion"
      haaska_hidden: true
      hidden: false
      persistence: true

    automation.back_back_to_yellow_dim_after_Motion:
      friendly_name: "Front Porch Lights Yellow No Motion"
      haaska_hidden: true
      hidden: false
      persistence: true

    script.front_bright_outside:
      friendly_name: "Front Porch Lights Bright"
      haaska_hidden: false
      haaska_name: Front Porch Lights Bright

    script.front_normal_outside:
      friendly_name: "Front Porch Lights Normal"
      haaska_hidden: false
      haaska_name: Front Porch Lights Normal

    light.front_steps:
      persistence: true
    light.rear_steps:
      persistence: true

group:
 carport_lights_card:
    control: hidden
    name: Carport
    entities:
      - light.carport
      - light.front_steps
      - light.rear_steps
      - automation.porch_lights_on
      - automation.porch_lights_off
      - automation.front_carport_bright_and_white_on_motion
      - automation.front_back_to_yellow_dim_after_Motion
      - script.front_bright_outside
      - script.front_normal_outside
        
automation:
  - alias: Porch Lights on
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
#      offset: "00:30:00"
    action:
      - service: light.turn_on
        data:
          entity_id: light.carport
          color_temp: 426
          brightness: 125
  - alias: Porch Lights off
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunrise
#      offset: "-00:30:00"
    action:
      - service: light.turn_off
        entity_id: light.carport

# brigten front porch light if motion from shed camera

  - alias: Front Carport bright and white on motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed
        to: 'on'
        for: '00:00:10'
    condition:
      - condition: state
        entity_id: light.front_steps
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.front_steps
          color_temp: 154
          brightness: 255

  - alias: Front Back to yellow dim after Motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed
        to: 'off'
    condition:
      - condition: state
        entity_id: light.front_steps
        state: 'on'
    action:
      - delay: '00:005:00'
      - service: light.turn_on
        data:
          entity_id: light.front_steps
          color_temp: 426
          brightness: 125

# brigten rear porch light if motion from shed camera

  - alias: rear Carport bright and white on motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_backdoor
        to: 'on'
        for: '00:00:10'
    condition:
      - condition: state
        entity_id: light.rear_steps
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.rear_steps
          color_temp: 154
          brightness: 255

  - alias: Rear Back to yellow dim after Motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed
        to: 'off'
    condition:
      - condition: state
        entity_id: light.rear_steps
        state: 'on'
    action:
      - delay: '00:005:00'
      - service: light.turn_on
        data:
          entity_id: light.rear_steps
          color_temp: 426
          brightness: 125

# Turn Front  lights on bright till i turn off
script:
  front_bright_outside:
    sequence:
      - service: automation.turn_off
        entity_id: automation.front_carport_bright_and_white_on_motion
      - service: automation.turn_off
        entity_id: automation.front_back_to_yellow_dim_after_Motion
      - service: light.turn_on
        data:
          entity_id: light.front_steps
          color_temp: 154
          brightness: 255
  front_normal_outside:
    sequence:
      - service: automation.turn_on
        entity_id: automation.front_carport_bright_and_white_on_motion
      - service: automation.turn_on
        entity_id: automation.front_back_to_yellow_dim_after_Motion
      - service: light.turn_on
        data:
          entity_id: light.front_steps
          color_temp: 426
          brightness: 125
