homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'kids_room_device_watchdog'
    script.kids_blinds_powercycle:
      friendly_name: Kids Blinds Reboot
      icon: mdi:power
    automation.reboot_kids_blinds:
      friendly_name: Kids Blinds Auto Reboot

input_boolean:
  boolean_kids_netork_watchdog:
    initial: off
  boolean_kids_hadashboard_status:
    initial: off

input_text:
  kids_bedroom_device_watchdog:
    name: Kids Bedroom Device

script:
  kids_blinds_powercycle:
    sequence:
      - service: switch.turn_off
        entity_id: switch.kids_room_blinds_reboot
      - delay: '00:00:10'
      - service: switch.turn_on
        entity_id: switch.kids_room_blinds_reboot
      - service: media_player.volume_mute
        data:
          entity_id: media_player.stereo
          is_volume_muted: "True"
      - wait_template: "{{ states.media_player.ha_speaker.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.kids_room_cast
          message: 'Rebooting Kids Blinds'
      - delay: '00:00:05'
      - service: media_player.volume_mute
        data:
          entity_id: media_player.stereo
          is_volume_muted: "False"

automation:
  - alias: Notify Device Status Kids Room
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.camera_kids_room_camera_connect
          - binary_sensor.broadlink_mini
          - binary_sensor.xiaomi_gateway_2
          - binary_sensor.kids_workstation
          - binary_sensor.alexa_kids_room_dot
          - binary_sensor.kids_room_roku
          - binary_sensor.chromecast_kids_room
#          - binary_sensor.ap_kids_room
          - binary_sensor.wemo_kids_fan
          - binary_sensor.dash_kids_room
          - binary_sensor.esp_blinds_kids_room
          - binary_sensor.kids_bedroom_purifer
          - binary_sensor.kids_room_blinds_zha_plug

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service_template: >
          {% if trigger.to_state.state | lower == "off" %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.boolean_kids_netork_watchdog
      - service: input_text.set_value
        data_template:
          entity_id: input_text.kids_bedroom_device_watchdog
          value: "{{ trigger.to_state.attributes.friendly_name }}"
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: >
            {% if trigger.to_state.state | lower == "off" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline Please Check Dashboard!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}

  - alias: 'kids_annouce_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_kids_bedroom
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_kids_netork_watchdog
        state: 'on'
    action:
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "The {{ states('input_text.kids_bedroom_device_watchdog') }} is offline in your room"
      - service: shell_command.kids_network_alert_dash

  - alias: 'kids_clear_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_kids_netork_watchdog
        to: 'off'
    action:
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:00:30'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Thank You for Fixing Me Returning to main dash"
      - service: input_text.set_value
        data_template:
          entity_id: input_text.kids_bedroom_device_watchdog
          value: "All Good"
      - service: shell_command.gabbies_dash

############################## HADASHBOAD WATCHDOG ##########################################
  - alias: 'kids_room_hadashboard_notify_down'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_dash_kids_room
        to: 'unknown'
        for: '00:01:00'
    action:
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Dashboard Is Offline"
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_kids_hadashboard_status

  - alias: 'kids_room_hadashboard_notify_up'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_dash_kids_room
        from: 'unknown'
        to: 'Kids room Dash'
        for: '00:01:00'
    action:
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Dashboard Is Online"
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_kids_hadashboard_status


  - alias: 'kids_annouce_hadashboard_issue_on_motion'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_kids_bedroom
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_kids_hadashboard_status
        state: 'on'
    action:
      - wait_template: "{{ states.media_player.kids_room_cast.state == 'idle' }}"
        timeout: '00:02:00'
        continue_on_timeout: 'true'
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Your Hadashboard is Offline"

  - alias: reboot_kids_blinds
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.esp_blinds_kids_room
        to: 'off'
        for: '00:01:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.kids_blinds_powercycle
