homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Kids Hallway'
    binary_sensor.kids_hallway_motion:
      friendly_name: Kids Hallway Motion
      device_class: motion
    sensor.motion_sensor_kids_hall_battery:
      icon: mdi:battery
      unit_of_measurement: '%'
      friendly_name: Kids Hallway Motion Sensor
    sensor.illumination_motion_sensor_kids_hallway:
      friendly_name: Kids Hallway Light Level
      icon: mdi:theme-light-dark

sensor:
  - platform: template
    sensors:
      motion_sensor_kids_hall_battery:
        friendly_name: 'Kids Hallway Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.kids_hallway_motion', 'battery_level') }}"


automation:
  - alias: Motion Kids Hallway Motion On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_hallway_motion
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.kids_hallway
          brightness_pct: >-
            {% if is_state("input_boolean.boolean_evening_time", "on") %}
            {{ states('input_number.evening_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_movie_time", "on") %}
            {{ states('input_number.movie_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
            {{ states('input_number.sleep_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_early_morning", "on") %}
            {{ states('input_number.earlymorning_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_home", "on") %}
            {{ states('input_number.home_mode_brightness_value') | int }}
            {% elif is_state("input_boolean.boolean_nap_time", "on") %}
            {{ states('input_number.nap_mode_brightness_value') | int }}
            {% else %}
              100
            {% endif %}

  - alias: Motion Kids Hallway Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_hallway_motion
        to: 'off'
        for: '00:01:00'
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.kids_hallway
          transition: >-
            {% if is_state("input_boolean.boolean_evening_time", "on") %}
            {{ states('input_number.evening_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_movie_time", "on") %}
            {{ states('input_number.movie_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
            {{ states('input_number.sleep_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_early_morning", "on") %}
            {{ states('input_number.earlymorning_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_home", "on") %}
            {{ states('input_number.home_mode_transition_value') | int }}
            {% elif is_state("input_boolean.boolean_nap_time", "on") %}
            {{ states('input_number.nap_mode_transition_value') | int }}
            {% else %}
              15
            {% endif %}
