homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'kids_room_device_watchdog'

input_boolean:
  boolean_kids_netork_watchdog:
    initial: off
  boolean_kids_hadashboard_status:
    initial: off

automation:
  - alias: Notify Device Status Kids Room
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.number12_camera_connect
          - binary_sensor.driveway_camera_connect
          - binary_sensor.camera_kids_room_camera_connect
          - binary_sensor.broadlink_mini
          - binary_sensor.xiaomi_gateway_2
          - binary_sensor.kids_workstation
          - binary_sensor.alexa_kids_room_dot
          - binary_sensor.kids_room_roku
          - binary_sensor.chromecast_kids_room
#          - binary_sensor.ap_kids_room
          - binary_sensor.wemo_kids_fan
          - binary_sensor.wemo_driveway_reboot
          - binary_sensor.dash_kids_room
          - binary_sensor.esp_blinds_kids_room
          - binary_sensor.kids_bedroom_purifer

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: >
            {% if trigger.to_state.state | lower == "off" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline Please Check Dashboard!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
      - service_template: >
          {% if trigger.to_state.state | lower == "off" %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.boolean_kids_netork_watchdog
      # - service: input_boolean.turn_on
      #   entity_id: input_boolean.boolean_kids_netork_watchdog
      # - service: shell_command.kids_network_alert_dash

  - alias: 'kids_annouce_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_kids_bedroom
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_kids_netork_watchdog
        state: 'on'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "There is a problem with a device in your room"
      - service: shell_command.kids_network_alert_dash

  - alias: 'kids_clear_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_kids_netork_watchdog
        to: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Thank You for Fixing Me Returning to main dash"
      - service: shell_command.gabbies_dash

############################## HADASHBOAD WATCHDOG ##########################################
  - alias: 'kids_room_hadashboard_notify_down'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_dash_kids_room
        to: 'unknown'
        for: '00:01:00'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Dashboard Is Offline"
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_kids_hadashboard_status

  - alias: 'kids_room_hadashboard_notify_up'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_dash_kids_room
        from: 'unknown'
        to: 'Kids room Dash'
        for: '00:01:00'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Dashboard Is Online"
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_kids_hadashboard_status

  - alias: 'kids_annouce_hadashboard_issue_on_motion'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_room_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_kids_bedroom
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_kids_hadashboard_status
        state: 'on'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kids_room_cast
          message: "Your Hadashboard is Offline"
