homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'master_bedroom_device_watchdog'
    script.master_fan_powercycle:
      friendly_name: Master Fan Reboot
      icon: mdi:power
    automation.reboot_master_fan:
      friendly_name: Master Fan Auto Reboot

input_boolean:
  boolean_master_bedroom_netork_watchdog:
    initial: off
  boolean_master_bedroom_hadashboard_status:
    initial: off

input_text:
  bedroom_device_watchdog:
    name: Master Bedroom Device Offline

script:
  master_fan_powercycle:
    sequence:
      - service: switch.turn_off
        entity_id: switch.wemo_master_bedroom_ceiling_fan
      - delay: '00:00:30'
      - service: switch.turn_on
        entity_id: switch.wemo_master_bedroom_ceiling_fan
      - service: media_player.volume_mute
        data:
          entity_id: media_player.stereo
          is_volume_muted: "True"
      - wait_template: "{{ states.media_player.ha_speaker.state == 'idle' }}"
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Rebooting Master Fan'
      - delay: '00:00:05'
      - service: media_player.volume_mute
        data:
          entity_id: media_player.stereo
          is_volume_muted: "False"

automation:
  - alias: 'notify_master_device_status'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.masterbedroom_camera_connect
          - binary_sensor.broadlink_pro
          - binary_sensor.alexa_master_dot
          - binary_sensor.chromecast_master
          - binary_sensor.ac_pro
          - binary_sensor.master_bedroom_mixer
          - binary_sensor.printer_hp
          - binary_sensor.dash_master
          - binary_sensor.esp_blinds_master_dawns_side
          - binary_sensor.esp_blinds_master_herbs_side
          - binary_sensor.master_bedroom_purifer
          - binary_sensor.dawns_controller
          - binary_sensor.master_bedroom_fan
          - binary_sensor.master_bedroom_zha_plug
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: >
            {% if trigger.to_state.state | lower == "off" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline Please Check Dashboard!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
      - service_template: >
          {% if trigger.to_state.state | lower == "off" %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.boolean_master_bedroom_netork_watchdog
      - service: input_text.set_value
        data_template:
          entity_id: input_text.bedroom_device_watchdog
          value: "{{ trigger.to_state.attributes.friendly_name }}"

  - alias: 'master_annouce_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_master_bedroom
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_master_bedroom_netork_watchdog
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "The {{ states('input_text.bedroom_device_watchdog') }} is offline in your room"
      - service: shell_command.master_network_alert_dash

  - alias: 'master_clear_device_issue'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_master_bedroom_netork_watchdog
        to: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "Thank You for Fixing Me Returning to main dash"
      - service: shell_command.master_dash
      - service: input_text.set_value
        data_template:
          entity_id: input_text.bedroom_device_watchdog
          value: "Nothing"
############################## HADASHBOAD WATCHDOG ##########################################
  - alias: 'master_bedroom_hadashboard_notify_down'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_dash_master
        to: 'unknown'
        for: '00:01:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "Dashboard Is Offline"
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_master_bedroom_hadashboard_status

  - alias: 'master_bedroom_hadashboard_notify_up'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_dash_master
        from: 'unknown'
        to: 'Master Dash'
        for: '00:01:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "Dashboard Is Online"
      - service: input_boolean.turn_off
        entity_id: input_boolean.boolean_master_bedroom_hadashboard_status

  - alias: 'master_bedroom_annouce_hadashboard_issue_on_motion'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_master_bedroom
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.boolean_master_bedroom_hadashboard_status
        state: 'on'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.master_bedroom_cast
          message: "Your Hadashboard is Offline"

  - alias: reboot_master_fan
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_fan
        to: 'off'
        for: '00:01:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.boolean_network_reboot
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.master_fan_powercycle
