homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'laundry Room'
    binary_sensor.laundry_room_motion:
      friendly_name: Laundry Room Motion
      device_class: motion
    sensor.motion_sensor_laundry_battery:
      icon: mdi:battery
      unit_of_measurement: '%'
    sensor.illumination_motion_sensor_laundry:
      friendly_name: Laundry Room Light Level
      icon: mdi:theme-light-dark

group:
  laundry_room_card:
    control: hidden
    name: Laundry Room
    entities:
      - binary_sensor.door_window_sensor_back_door
      - binary_sensor.door_window_sensor_laundry_room_door
      - light.laundry_room
      - binary_sensor.laundry_room_motion
      - sensor.motion_sensor_laundry_battery
      - sensor.illumination_motion_sensor_laundry
      - automation.laundry_motion_homeMode
      - automation.laundry_motion_not_homeMode
      - automation.laundry_motion_off
      - switch.wemo_washing_machine
      - sensor.washing_machine_watts
      - sensor.washing_machine_power_up
      - sensor.washing_machine_power_down
      - input_boolean.stopwatch
      - input_boolean.dummy
      - input_boolean.washer_switch
      - sensor.stopwatch
      - sensor.washer_status
      - automation.washer_start
      - automation.washer_done
      - automation.stopwatch_start
      - automation.stopwatch_stop
      - automation.stopwatch_update

sensor:
  - platform: template
    sensors:
      motion_sensor_laundry_battery:
        friendly_name: 'Laundry Room Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.laundry_room_motion', 'battery_level') }}"

automation:
  - alias: Laundry Motion HomeMode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          color_temp: 154
          brightness: 255

  - alias: Laundry Motion not HomeMode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          color_temp: 154
          brightness: 125

  - alias: Laundry Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'off'
        for: '00:01:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.laundry_room
          transition: 30
