homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Master Bedroom'
    automation.motion_master_lights_on:
      haaska_hidden: true
      hidden: false
      persistence: true
      friendly_name: Master Lights On
    automation.motion_master_bedroom_motion_off:
      haaska_hidden: true
      hidden: false
      persistence: true
      friendly_name: Master Bedroom Automate Off
    automation.master_bedroom_home_mode:
      haaska_hidden: true
      hidden: false
      persistence: true
      friendly_name: Master Bedroom Home Mode
    binary_sensor.master_motion:
      friendly_name: Master Motion Sensor
      device_class: motion
    sensor.motion_sensor_master_battery:
      icon: mdi:battery
      friendly_name: Master Motion Sensor
      unit_of_measurement: '%'
    sensor.dawns_controller_wifi_signal:
      icon: mdi:signal
    sensor.illumination_master_bedroom:
      friendly_name: Master Bedroom Light Level
      icon: mdi:theme-light-dark
    light.dawns_bedside_lamp:
      friendly_name: Dawns Side
    light.herbs_bedside_lamp:
      friendly_name: Herbs Side
    switch.dawn_night:
      friendly_name: Dawns controls Night
      haaska_name: Bedroom Fan
      icon: mdi:fan

group:
  master_bedroom_card:
     control: hidden
     name: Master Bedroom
     entities:
      - light.dawns_bedside_lamp
      - light.herbs_bedside_lamp
      - light.master_table_lamps
      - light.light_bulb_2
      - switch.master_bedroom_network
      - switch.master_bedroom_mixer
      - fan.master_bedroom_fan
      - script.master_fan_auto
      - sensor.fan_speed_master
      - binary_sensor.gang_1
      - binary_sensor.master_motion
      - sensor.master_bedroom_temperature
      - sensor.motion_sensor_master_battery
      - sensor.illumination_master_bedroom
      - sensor.bedroom_wallpanel_battery
      - sensor.bedroom_wallpanel_brightness
      - binary_sensor.master_bedroom_occupancy
      - switch.fan_on
      - switch.dawn_day
      - switch.dawn_night
      - automation.motion_master_lights_on
      - automation.motion_master_bedroom_motion_off
      - input_select.master_blinds_status
      - sensor.master_blinds_state
      - binary_sensor.door_window_sensor_master_bedroom_door
      - sensor.master_door_sensor_batt
      - binary_sensor.door_window_sensor_master_closet
      - sensor.master_closet_door_sensor_batt
      - binary_sensor.door_window_sensor_dawns_side
      - sensor.dawns_side_window_sensor_batt
      - binary_sensor.door_window_sensor_herbs_side
      - sensor.herbs_side_window_sensor_batt

sensor:
  - platform: template
    sensors:
      motion_sensor_master_battery:
        friendly_name: 'Master Bedroom Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.master_motion', 'battery_level') }}"

  - platform: mqtt
    state_topic: "dawns/Wifi Connect/wifi"
    unit_of_measurement: 'dbm'
    name: Dawns Controller Wifi Signal

switch:
  - platform: mqtt
    name: "dawn_night"
    state_topic: "dawns/relay1/state"
    command_topic: "dawns/gpio/12"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

#######################################################################################################
#####    When home mode set on ecobee then master light turns on in bedroom (not while sleeping  ######
#####    ie house is in sleep mode                                                               ######
#####    use case app only allows set times and we go to bed at diff times                       ######
#######################################################################################################

automation:
  - alias: motion_master_lights_on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'off'
      - condition: state
        entity_id: input_boolean.boolean_day_time_sleep
        state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.light_bulb_2
            - light.master_table_lamps
          color_temp: >-
             {% if is_state("input_boolean.boolean_evening_time", "on") %}
             {{ states('input_number.evening_mode_color_temp_value') | int }}
             {% elif is_state("input_boolean.boolean_movie_time", "on") %}
             {{ states('input_number.movie_mode_color_temp_value') | int }}
             {% elif is_state("input_boolean.boolean_home", "on") %}
             {{ states('input_number.home_mode_color_temp_value') | int }}
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
              {{ states('input_number.nap_mode_color_temp_value') | int }}
             {% else %}
               180
             {% endif %}
          brightness_pct: >-
              {% if is_state("input_boolean.boolean_evening_time", "on") %}
              {{ states('input_number.evening_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_movie_time", "on") %}
              {{ states('input_number.movie_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_home", "on") %}
              {{ states('input_number.home_mode_brightness_value') | int }}
              {% elif is_state("input_boolean.boolean_nap_time", "on") %}
              {{ states('input_number.nap_mode_brightness_value') | int }}
              {% else %}
                100
              {% endif %}

  - alias: Motion Master Bedroom Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'off'
        for: '00:03:00'
    action:
      - service: light.turn_off
        entity_id: light.light_bulb_2
      - service: light.turn_off
        entity_id: light.master_table_lamps

  - alias: Master Bedroom Sleep mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_sleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.boolean_day_time_sleep
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.dawn_night
      - service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_fan
          speed: "high"

  - alias: Master Bedroom Home mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.dawn_night
      - service: switch.turn_on
        entity_id: switch.master_bedroom_mixer
      - service: fan.turn_off
        data:
          entity_id: fan.master_bedroom_fan
