homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'laundry Room'
    binary_sensor.laundry_room_motion:
      friendly_name: Laundry Room Motion
      device_class: motion
    sensor.motion_sensor_laundry_battery:
      icon: mdi:battery
      unit_of_measurement: '%'
    sensor.illumination_motion_sensor_laundry:
      friendly_name: Laundry Room Light Level
      icon: mdi:theme-light-dark

sensor:
  - platform: template
    sensors:
      motion_sensor_laundry_battery:
        friendly_name: 'Laundry Room Motion Sensor'
        value_template: "{{ state_attr('binary_sensor.laundry_room_motion', 'battery_level') }}"

automation:
  - alias: Laundry Motion HomeMode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          color_temp: 154
          brightness: 255

  - alias: Laundry Motion not HomeMode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          color_temp: 154
          brightness: 125

  - alias: Laundry Motion Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_motion
        to: 'off'
        for: '00:01:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.laundry_room
          transition: 30
