homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Settings'
################  EVENING MODE #################################################
    input_number.evening_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.evening_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
#    input_number.evening_mode_transition_value:
    input_number.evening_time_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.evening_time_off:
      friendly_name: Light Turn Off Timer
      persistent: true
    input_number.evening_mode_chromecast_lv:
      friendly_name: Chrome Cast Living Room Value
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.evening_mode_chromecast_masterbedroom:
      friendly_name: Chrome Cast Master Bedroom
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
################  Movie MODE #################################################
    input_number.movie_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.movie_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.movie_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.movie_mode_chromecast_lv:
      friendly_name: Chrome Cast Living Room Value
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.movie_mode_chromecast_masterbedroom:
      friendly_name: Chrome Cast Master Bedroom
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
################  Sleep MODE #################################################
    input_number.sleep_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.sleep_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.sleep_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.onkyo_volume_sleepmode:
      friendly_name: Onkyo Volume Early Morning
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.sleep_mode_chromecast_livingroom:
      friendly_name: Chrome Cast LV Volume Early Morning
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
################  Early Morning MODE ###########################################
    input_number.earlymorning_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.earlymorning_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.earlymorning_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.onkyo_volume_earlymorning:
      friendly_name: Onkyo Volume Early Morning
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.earlymorning_mode_chromecast_livingroom:
      friendly_name: Chrome Cast LV Volume Early Morning
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
################  Home MODE ###################################################
    input_number.home_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.home_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.home_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true
    input_number.home_mode_chromecast_lv:
      friendly_name: Chrome Cast Living Room Value
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.home_mode_chromecast_masterbedroom:
      friendly_name: Chrome Cast Master Bedroom
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
################  Alarm ###################################################
    input_number.alarm_mode_chromecast_lv:
      friendly_name: Chrome Cast Living Room Value
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true
    input_number.alarm_mode_chromecast_masterbedroom:
      friendly_name: Chrome Cast Master Bedroom
      icon: mdi:volume-high
      persistent: true
      haaska_hidden: true

################  Nap MODE ###################################################
    input_number.nap_mode_brightness_value:
      friendly_name: Light Brightness %
      icon: mdi:lightbulb-on-outline
      persistent: true
    input_number.nap_mode_color_temp_value:
      friendly_name: Light Color Temperature
      icon: mdi:lightbulb-on
      persistent: true
    input_number.nap_mode_transition_value:
      friendly_name: Light Transition Time
      icon: mdi:timer
      persistent: true


group:
  setting_view:
   view: yes
   name: Setting's
   icon: mdi:settings
   entities:
     - group.setting_evening_mode_settings_card
     - group.setting_movie_mode_settings_card
     - group.setting_sleep_mode_settings_card
     - group.setting_earlymorning_mode_settings_card
     - group.setting_home_mode_settings_card
     - group.setting_nap_mode_settings_card
     - group.setting_alarm_mode_settings_card
     - group.ha_server_automations
     - group.bi_server_automations

################  EVENING MODE #################################################
  setting_evening_mode_settings_card:
   name: Evening Mode
   entities:
     - input_number.evening_mode_brightness_value
     - input_number.evening_mode_color_temp_value
     - input_number.evening_time_mode_transition_value
#     - input_number.evening_mode_transition_value
     - input_number.evening_mode_chromecast_lv
     - input_number.evening_mode_chromecast_masterbedroom
     - input_number.evening_time_off
     - automation.motion_off

################  Movie MODE #################################################
  setting_movie_mode_settings_card:
   name: Movie Mode
   entities:
     - input_number.movie_mode_brightness_value
     - input_number.movie_mode_color_temp_value
     - input_number.movie_mode_transition_value
     - input_number.movie_mode_chromecast_lv
     - input_number.movie_mode_chromecast_masterbedroom
################  Sleep MODE #################################################
  setting_sleep_mode_settings_card:
   name: Sleep Mode
   entities:
     - input_number.sleep_mode_brightness_value
     - input_number.sleep_mode_color_temp_value
     - input_number.sleep_mode_transition_value
     - input_number.sleep_mode_chromecast_livingroom
     - input_number.onkyo_volume_sleepmode
################  Early Morning MODE #################################################
  setting_earlymorning_mode_settings_card:
   name: Early Morning Mode
   entities:
     - input_number.earlymorning_mode_brightness_value
     - input_number.earlymorning_mode_color_temp_value
     - input_number.earlymorning_mode_transition_value
     - input_number.earlymorning_mode_chromecast_livingroom
     - input_number.onkyo_volume_earlymorning
################  Home MODE #################################################
  setting_home_mode_settings_card:
   name: Home Mode
   entities:
     - input_number.home_mode_brightness_value
     - input_number.home_mode_color_temp_value
     - input_number.home_mode_transition_value
     - input_number.home_mode_chromecast_lv
     - input_number.home_mode_chromecast_masterbedroom
################  Alarm MODE #################################################
  setting_alarm_mode_settings_card:
   name: Alarm Mode
   entities:
     - input_number.alarm_mode_chromecast_lv
     - input_number.alarm_mode_chromecast_masterbedroom
################  Nap MODE #################################################
  setting_nap_mode_settings_card:
   name: Nap Mode
   entities:
     - input_number.nap_mode_brightness_value
     - input_number.nap_mode_color_temp_value
     - input_number.nap_mode_transition_value

input_number:
################  EVENING MODE #################################################
  evening_mode_brightness_value:
    name: Evening Mode Brightness
    initial: 50
    min: 0
    max: 100
    step: 1
  evening_mode_color_temp_value:
    name: Evening Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
#  evening_mode_transition_value:
  evening_time_mode_transition_value:
    name: Evening Mode Transition
    initial: 15
    min: 0
    max: 90
    step: 1
  evening_time_off:
    name: Evening Mode Timer
    initial: 3
    min: 1
    max: 15
    step: 1
  evening_mode_chromecast_lv:
    name: Evening Time TTS Living Room
    initial: .60
    min: 0
    max: 1
    step: .1
  evening_mode_chromecast_masterbedroom:
    name: Evening Time Mode TTS Master Bedroom
    initial: .30
    min: 0
    max: 1
    step: .1
################  Movie MODE #################################################
  movie_mode_brightness_value:
    name: Movie Mode Brightness
    initial: 30
    min: 0
    max: 100
    step: 1
  movie_mode_color_temp_value:
    name: Movie Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
  movie_mode_transition_value:
    name: Movie Mode Transition
    initial: 45
    min: 0
    max: 90
    step: 1
  movie_mode_chromecast_lv:
    name: Movie Time TTS Living Room
    initial: .75
    min: 0
    max: 1
    step: .1
  movie_mode_chromecast_masterbedroom:
    name: Movie Time Mode TTS Master Bedroom
    initial: .35
    min: 0
    max: 1
    step: .1
################  Sleep MODE #################################################
  sleep_mode_brightness_value:
    name: Sleep Mode Brightness
    initial: 20
    min: 0
    max: 100
    step: 1
  sleep_mode_color_temp_value:
    name: Sleep Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
  sleep_mode_transition_value:
    name: Sleep Mode Transition
    initial: 30
    min: 1
    max: 90
    step: 1
  sleep_mode_chromecast_livingroom:
    name: Early Morning Chrome Cast living room
    initial: .3
    min: 0
    max: 1
    step: .1
  onkyo_volume_sleepmode:
    name: Onkyo Volume
    initial: .6
    min: 0
    max: 1.75
    step: .1
################  Early Morning MODE ###########################################
  earlymorning_mode_brightness_value:
    name: Early Morning Mode Brightness
    initial: 60
    min: 0
    max: 100
    step: 1
  earlymorning_mode_color_temp_value:
    name: Early Morning Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
  earlymorning_mode_transition_value:
    name: Early Morning Mode Transition
    initial: 20
    min: 1
    max: 90
    step: 1
  earlymorning_mode_chromecast_livingroom:
    name: Early Morning Chrome Cast living room
    initial: .3
    min: 0
    max: 1
    step: .1
  onkyo_volume_earlymorning:
    name: Onkyo Volume
    initial: .6
    min: 0
    max: 1.75
    step: .1
################  Home MODE ###########################################
  home_mode_brightness_value:
    name: Home Mode Brightness
    initial: 100
    min: 0
    max: 100
    step: 1
  home_mode_color_temp_value:
    name: Home Mode Color Temp
    initial: 154
    min: 154
    max: 426
    step: 1
  home_mode_transition_value:
    name: Home Mode Transition
    initial: 10
    min: 1
    max: 90
    step: 1
  home_mode_chromecast_lv:
    name: Home Mode TTS Living Room
    initial: .80
    min: 0
    max: 1
    step: .1
  home_mode_chromecast_masterbedroom:
    name: Home Mode TTS Master Bedroom
    initial: .40
    min: 0
    max: 1
    step: .1
################  Alarm MODE ###########################################
  alarm_mode_chromecast_lv:
    name: Home Mode TTS Living Room
    initial: .99
    min: 0
    max: 1
    step: .1
  alarm_mode_chromecast_masterbedroom:
    name: Home Mode TTS Master Bedroom
    initial: .99
    min: 0
    max: 1
    step: .1
################  Nap MODE #####################################################
  nap_mode_brightness_value:
    name: Nap Mode Brightness
    initial: 60
    min: 0
    max: 100
    step: 1
  nap_mode_color_temp_value:
    name: Nap Mode Color Temp
    initial: 426
    min: 154
    max: 426
    step: 1
  nap_mode_transition_value:
    name: Nap Mode Transition
    initial: 20
    min: 1
    max: 90
    step: 1
