homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Settings'


group:
  setting_view:
   view: yes
   name: Setting's
   icon: mdi:settings
   entities:
     - group.setting_evening_mode_settings_card
     - group.setting_movie_mode_settings_card
     - group.setting_sleep_mode_settings_card
     - group.setting_earlymorning_mode_settings_card
     - group.setting_home_mode_settings_card
     - group.setting_nap_mode_settings_card
     - group.setting_alarm_mode_settings_card
     - group.ha_server_automations
     - group.bi_server_automations
     - group.setting_humdity_settings_card
     - group.input_boolean_main_modes_card
     - group.input_boolean_sub_modes_card

################  EVENING MODE #################################################
  setting_evening_mode_settings_card:
   name: Evening Mode
   entities:
     - input_number.evening_mode_brightness_value
     - input_number.evening_mode_color_temp_value
     - input_number.evening_time_mode_transition_value
#     - input_number.evening_mode_transition_value
     - input_number.evening_mode_chromecast_lv
     - input_number.evening_mode_chromecast_masterbedroom
     - input_number.evening_time_off
     - automation.motion_off

################  Movie MODE #################################################
  setting_movie_mode_settings_card:
   name: Movie Mode
   entities:
     - input_number.movie_mode_brightness_value
     - input_number.movie_mode_color_temp_value
     - input_number.movie_mode_transition_value
     - input_number.movie_mode_chromecast_lv
     - input_number.movie_mode_chromecast_masterbedroom
################  Sleep MODE #################################################
  setting_sleep_mode_settings_card:
   name: Sleep Mode
   entities:
     - input_number.sleep_mode_brightness_value
     - input_number.sleep_mode_color_temp_value
     - input_number.sleep_mode_transition_value
     - input_number.sleep_mode_chromecast_livingroom
     - input_number.onkyo_volume_sleepmode
################  Early Morning MODE #################################################
  setting_earlymorning_mode_settings_card:
   name: Early Morning Mode
   entities:
     - input_number.earlymorning_mode_brightness_value
     - input_number.earlymorning_mode_color_temp_value
     - input_number.earlymorning_mode_transition_value
     - input_number.earlymorning_mode_chromecast_livingroom
     - input_number.onkyo_volume_earlymorning
################  Home MODE #################################################
  setting_home_mode_settings_card:
   name: Home Mode
   entities:
     - input_number.home_mode_brightness_value
     - input_number.home_mode_color_temp_value
     - input_number.home_mode_transition_value
     - input_number.home_mode_chromecast_lv
     - input_number.home_mode_chromecast_masterbedroom
################  Alarm MODE #################################################
  setting_alarm_mode_settings_card:
   name: Alarm Mode
   entities:
     - input_number.alarm_mode_chromecast_lv
     - input_number.alarm_mode_chromecast_masterbedroom
################  Nap MODE #################################################
  setting_nap_mode_settings_card:
   name: Nap Mode
   entities:
     - input_number.nap_mode_brightness_value
     - input_number.nap_mode_color_temp_value
     - input_number.nap_mode_transition_value
################  Humidity #################################################
  setting_humdity_settings_card:
   name: Humidity
   entities:
     - input_number.target_humidity_kids_bathroom
     - input_number.target_humidity_master_bathroom

input_number:
###################### Humidity ################################################
  target_humidity_kids_bathroom:
    name: Kids Bathroom Humidity Setting
    initial: 65
    min: 0
    max: 100
    step: 1
  target_humidity_master_bathroom:
    name: Master Bathroom Humidity Setting
    initial: 65
    min: 0
    max: 100
    step: 1
