homeassistant:
  customize:
    script.lamps_on:
      friendly_name: Sleep
      icon: mdi:sleep
      haaska_name: Sleep

#########################################################################################
#                                                                                   #####
#                   Sleep Mode                                                      #####
#                                                                                   #####
#########################################################################################
script:
  lamps_on:
    sequence:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Good Night'
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_sleep
      - service: media_player.turn_off
        data:
          entity_id: media_player.stereo
      - delay: '00:00:03'
      - service: climate.set_hold_mode
        data:
          entity_id: climate.thermostat
          hold_mode: "sleep"
      - delay: '00:00:02'
      - service: remote.turn_off
        data:
          entity_id: remote.entertainment
      - service: fan.turn_off
        data:
          entity_id: fan.living_room_fan
      - service: light.turn_on
        data:
          entity_id: light.master_hallway
          color_temp: 426
          brightness: 125
      - service: light.turn_on
        data:
          entity_id: light.master_table_lamps
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 426
          brightness: 125
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_sleep_on
      - service: switch.turn_off
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:10'
      - service: light.turn_off
        data:
          entity_id: light.lamps
      - service: light.turn_on
        data:
          entity_id: light.dawns_lamp
          color_temp: 426
          brightness: 125
      - delay: '00:00:10'
      - service: script.turn_on
        entity_id: script.led_off
      - delay: '00:00:10'
      - wait_template: "{{ states.binary_sensor.hallway_motion.state == 'off' }}"
      - service: light.turn_off
        data:
          entity_id: light.master_hallway
      - delay: '00:01:15'
#      - wait_template: "{{ states.binary_sensor.motion_sensor_master_bath.state == 'off' }}"
      - wait_template: "{{ states.binary_sensor.master_motion.state == 'off' }}"
      - service: light.turn_off
        data:
          entity_id: light.bathroom
      - delay: '00:00:45'
      - wait_template: "{{ states.binary_sensor.master_motion.state == 'off' }}"
      - service: light.turn_off
        data:
          entity_id: light.master_table_lamps
          transition: 45
      - service: rest_command.sleep
      - service: rest_command.sleep
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on

# rest_command changes profile on blue iris
