homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Wax Warmers'

    switch.dawn_day:
      friendly_name: Dawns Scent
      haaska_name: Dawns Scent
      icon: mdi:flower

    switch.kids_bathroom_scent:
      friendly_name: Kids Bath Scent
      haaska_name: Kids Bath Scent
      icon: mdi:flower
    switch.dawns_scent:
      haaska_name: Living room Scent
      friendly_name: Living Room Scent
      icon: mdi:flower
      persistent: true
      assumed_state: false
    automation.warmers_scent_on:
      friendly_name: Warmers On
      haaska_hidden: true
    automation.warmers_scent_off:
      friendly_name: Warmers Off
      haaska_hidden: true

group:
  smellgood_card:
   name: Wax Warmers
   control: hidden
   entities:
     - switch.dawns_scent
     - switch.dawn_day
     - switch.kids_bathroom_scent
     - automation.warmers_scent_on
     - automation.warmers_scent_off

automation:
  - alias: warmers_scent_on
    trigger:
      - platform: state
        entity_id: sensor.house_mode_state
        to: 'Home'
    action:
      - service: switch.turn_on
        entity_id: switch.dawns_scent
      - service: switch.turn_on
        entity_id: switch.dawns_scent
      - service: switch.turn_on
        entity_id: switch.master_bath
      - service: switch.turn_on
        entity_id: switch.kids_bathroom_scent

  - alias: warmers_scent_off
    trigger:
      - platform: state
        entity_id: sensor.house_mode_state
        to: 'Evening Time'
      - platform: state
        entity_id: sensor.house_mode_state
        to: 'Away'
    action:
      - service: switch.turn_off
        entity_id: switch.dawns_scent
      - service: switch.turn_off
        entity_id: switch.dawns_scent
      - service: switch.turn_off
        entity_id: switch.master_bath
      - service: switch.turn_off
        entity_id: switch.kids_bathroom_scent
