homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Wax Warmers'
    switch.dawn_day:
      friendly_name: Dawns Scent
      haaska_name: Dawns Scent
      icon: mdi:flower
    switch.kids_bathroom_scent:
      friendly_name: Kids Bath Scent
      haaska_name: Kids Bath Scent
      icon: mdi:flower
    switch.kids_bathroom_scent_2:
      haaska_name: Living room Scent
      friendly_name: Living Room Scent
      icon: mdi:flower
      persistent: true
      assumed_state: false
    automation.warmers_scent_on:
      friendly_name: Warmers On
      haaska_hidden: true
    automation.warmers_scent_off:
      friendly_name: Warmers Off
      haaska_hidden: true

group:
  smellgood_card:
   name: Wax Warmers
   control: hidden
   entities:
     - switch.dawn_day
     - switch.kids_bathroom_scent
     - switch.kids_bathroom_scent_2
     - automation.warmers_scent_on
     - automation.warmers_scent_off

switch:
  - platform: mqtt
    name: "dawn_day"
    state_topic: "dawns/relay/state"
    command_topic: "dawns/gpio/14"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true

automation:
  - alias: warmers_scent_on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.house_mode_state
        to: 'Home'
    action:
      - service: switch.turn_on
        entity_id:
          - switch.kids_bathroom_scent_2
          - switch.kids_bathroom_scent
          - switch.dawn_day

  - alias: warmers_scent_off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.boolean_sleep
          - input_boolean.boolean_evening_time
          - input_boolean.boolean_away
        to: 'on'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.kids_bathroom_scent
          - switch.kids_bathroom_scent_2
          - switch.dawn_day
