homeassistant:
  customize:
    sensor.dark_sky_humidity:
      friendly_name: Humidity
    sensor.dark_sky_temperature:
      friendly_name: Temperature
    sensor.dark_sky_wind_bearing:
      icon: mdi:compass-outline
      friendly_name: Direction
      unit_of_measurement: 'deg'
    sensor.dark_sky_wind_speed:
      icon: mdi:speedometer
      friendly_name: Wind Speed
    sensor.dark_sky_precip_intensity:
      icon: mdi:weather-pouring
      friendly_name: Rain Intensity
    sensor.dark_sky_daily_summary:
      friendly_name: Daily
    sensor.dark_sky_hourly_summary:
      friendly_name: Hourly
    sensor.dark_sky_minutely_summary:
      friendly_name: To the Minute

group:
  ForecastWeather_card:
   name: Predication
   entities:
     - sensor.dark_sky_summary
     - sensor.dark_sky_daily_summary
     - sensor.dark_sky_hourly_summary
     - sensor.dark_sky_minutely_summary
     - sensor.dark_sky_daily_high_temperature
     - sensor.dark_sky_daily_low_temperature
     - sensor.dark_sky_precip_probability
     - sensor.dark_sky_nearest_storm_bearing
     - sensor.dark_sky_nearest_storm_distance

  daily_forecast_card:
    name: Daily Forecast
    entities:
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n

  Conditions_card:
   name: Current Weather
   entities:
     - sensor.dark_sky_icon
     - sensor.dark_sky_temperature
     - sensor.dark_sky_humidity
     - sensor.dark_sky_wind_speed
     - sensor.dark_sky_wind_bearing
     - sensor.dark_sky_precip_intensity
     - sun.sun

  animated_radar_card:
   name: Animated Radar
   entities:
     - camera.Radar_Animated

  still_image_radar_card:
   name: Still Radar
   entities:
     - camera.radar

camera:
  - platform: generic
    still_image_url: !secret radar
    name: Radar

  - platform: generic
    still_image_url: 'http://images.intellicast.com/WxImages/RadarLoop/msy_None_anim.gif'
    name: Radar Animated

#weather:
  # - platform: darksky
  #   api_key: !secret darksky_api

sensor:
  - platform: wunderground
    api_key: !secret wunderground_api
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n

  - platform: darksky
    api_key: !secret darksky_api

    monitored_conditions:
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_probability
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - temperature
      - humidity
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
