homeassistant:
  customize:
    sensor.dark_sky_daily_summary:
      friendly_name: Daily Summary
      haaska_hidden: true
    sensor.dark_sky_hourly_summary:
      friendly_name: Hourly Summary
      haaska_hidden: true
    sensor.dark_sky_minutely_summary:
      friendly_name: To The Minute
      haaska_hidden: true
    sensor.dark_sky_daytime_high_temperature_0:
      friendly_name: Daytime High
      haaska_hidden: true
    sensor.dark_sky_overnight_low_temperature_0:
      friendly_name: Overnight Low
      haaska_hidden: true
    sensor.dark_sky_nearest_storm_bearing:
      friendly_name: Nearest Storm Bearing
      haaska_hidden: true
    sensor.dark_sky_nearest_storm_distance:
      friendly_name: Nearest Storm Distance
      haaska_hidden: true
    sensor.dark_sky_precip_intensity:
      friendly_name: Precip Instensity
      haaska_hidden: True
#     sensor.dark_sky_precip_intensity_0:
    sensor.dark_sky_precip_probability:
      friendly_name: Percip Probability
      haaska_hidden: true
#     sensor.dark_sky_precip_probability_0


  animated_radar_card:
   name: Animated Radar
   entities:
     - camera.Radar_Animated

  still_image_radar_card:
   name: Still Radar
   entities:
     - camera.radar

camera:
  - platform: generic
    still_image_url: !secret radar
    name: Radar

  - platform: generic
    still_image_url: 'http://images.intellicast.com/WxImages/RadarLoop/msy_None_anim.gif'
    name: Radar Animated

sensor:
  - platform: wunderground
    api_key: !secret wunderground_api
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n

  - platform: darksky
    api_key: !secret darksky_api
    latitude: !secret latitude
    longitude: !secret longitude
    scan_interval: "00:15:00"
    forecast:
      - 0
    monitored_conditions:
      - temperature_high
      - temperature_low
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_probability
      - precip_intensity
      - hourly_summary
      - minutely_summary
      - daily_summary
      - temperature
      - apparent_temperature
      - temperature_min
      - temperature_max
      - humidity
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - wind_bearing
      - pressure
      - icon

  - platform: moon

weather:
  - platform: darksky
    api_key: !secret darksky_api
