homeassistant:
  customize:
    automation.fan_set_speed:
      friendly_name: "Fan Set Speed"
      haaska_hidden: true
      hidden: true

    automation.fan_turn_on:
      friendly_name: "Fan Turn On"
      haaska_hidden: true
      hidden: true

    automation.fan_low_with_hvac_automation:
      friendly_name: Low with Ac
      haaska_hidden: true

    automation.fan_medium_with_hvac_automation:
      friendly_name: Meduim without Ac
      haaska_hidden: true

    automation.reenable_fan_automation:
      friendly_name: Reenable Fan automation
      haaska_hidden: true

    script.living_room_fan_auto:
      friendly_name: "Breeze"
      icon: mdi:fan
      Haaska_hidden: false
      haaska_name: Breeze

    script.master_fan_auto:
      friendly_name: "Master Breeze"
      icon: mdi:fan
      Haaska_hidden: false
      haaska_name: Master Breeze

    script.refresh_wink:
      friendly_name: " Refresh Wink"
      icon: mdi:update

    switch.fan_override:
      friendly_name: Fan Auto
      icon: mdi:fan
      haaska_hidden: false
      haaska_name: Fan Auto

    switch.fan_master_override:
      friendly_name: Master Fan Auto
      icon: mdi:fan
      haaska_hidden: false
      haaska_name: Master Fan Auto

    sensor.fan_speed:
      icon: mdi:speedometer
      haaska_hidden: true

    sensor.fan_speed_master:
      icon: mdi:speedometer
      haaska_hidden: true

    binary_sensor.gang:
      friendly_name: Fan Connection
      icon: mdi:nfc
      haaska_hidden: true

    binary_sensor.gang_1:
      friendly_name: Master Fan Connection
      icon: mdi:nfc
      haaska_hidden: true

    light.light_bulb:
      friendly_name: Living Room Light
      haaska_hidden: false
      haaska_name: Living Room Light

    light.light_bulb_2:
      friendly_name: Master Bedroom Light
      haaska_hidden: false
      haaska_name: Master Bedroom Light

group:
  livingroomfan_card:
   control: hidden
   name: Living Room Fan
   entities:
     - fan.living_room_fan
     - switch.fan_override
     - script.living_room_fan_auto
     - input_select.living_room_ceiling_fan_speeds
     - binary_sensor.gang
     - script.refresh_wink

input_select:
  master_ceiling_fan_speeds:
    name: Master Ceiling Speeds
    options:
      - Select Input
      - Fast
      - Medium
      - Slow

  living_room_ceiling_fan_speeds:
    name: Living Room Ceiling Fan Speeds
    options:
      - Select Input
      - High
      - Medium
      - Low
      - Lowest

sensor:
  - platform: template
    sensors:
      fan_speed:
        friendly_name: 'Fan Speed'
        value_template: "{{ states.fan.living_room_fan.attributes.speed }}"
  - platform: template
    sensors:
      fan_speed_master:
        friendly_name: 'Fan Speed'
        value_template: "{{ states.fan.master_bedroom_fan.attributes.speed }}"

automation:
  - alias: master_fan_mode_select
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.master_ceiling_fan_speeds
    action:
      - service: fan.set_speed
        entity_id: fan.master_bedroom_fan
        data_template:
          speed: >-
            {% if is_state("input_select.master_ceiling_fan_speeds", "high") %}
              High
            {% elif is_state("input_select.master_ceiling_fan_speeds", "medium") %}
              Medium
            {% elif is_state("input_select.master_ceiling_fan_speeds", "low") %}
              Low
            {% elif is_state("input_select.master_ceiling_fan_speeds", "lowest") %}
              Lowest
            {% else %}
              Medium
            {% endif %}
  - alias: master_ceiling_update_input_select
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.fan_speed_master
    action:
      - service: input_select.select_option
        entity_id: input_select.master_ceiling_fan_speeds
        data_template:
          option: >-
            {% if is_state("sensor.fan_speed_master", "high") %}
               High
            {% elif is_state("sensor.fan_speed_master", "medium") %}
               Medium
            {% elif is_state("sensor.fan_speed_master", "low") %}
               Low
            {% elif is_state("sensor.fan_speed_master", "lowest") %}
               Lowest
            {% else %}
               Medium
            {% endif %}

  - alias: living_room_fan_mode_select
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.living_room_ceiling_fan_speeds
    action:
      - service: fan.set_speed
        entity_id: fan.living_room_fan
        data_template:
          speed: >-
            {% if is_state("input_select.living_room_ceiling_fan_speeds", "High") %}
              high
            {% elif is_state("input_select.living_room_ceiling_fan_speeds", "Medium") %}
              medium
            {% elif is_state("input_select.living_room_ceiling_fan_speeds", "Low") %}
              low
            {% elif is_state("input_select.living_room_ceiling_fan_speeds", "Lowest") %}
              lowest
            {% else %}
              medium
            {% endif %}

  - alias: living_room_ceiling_update_input_select
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.fan_speed
    action:
      - service: input_select.select_option
        entity_id: input_select.living_room_ceiling_fan_speeds
        data_template:
          option: >-
            {% if is_state("sensor.fan_speed", "high") %}
               High
            {% elif is_state("sensor.fan_speed", "medium") %}
               Medium
            {% elif is_state("sensor.fan_speed", "low") %}
               Low
            {% elif is_state("sensor.fan_speed", "lowest") %}
               Lowest
            {% else %}
               Medium
            {% endif %}

##########################################################################
############################  cieling fan automation with Hvac    ########
##########################################################################
  - alias: Fan low with Hvac automation
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.hvac_fan
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          speed: "low"

  - alias: Fan medium with hvac automation
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.hvac_fan
        to: 'off'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          speed: "medium"


# if wife turns disables fan automation this reenables it
  - alias: Reenable Fan Automation
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      - service: automation.turn_on
        entity_id: automation.fan_low_with_hvac_automation
      - service: automation.turn_on
        entity_id: automation.fan_medium_with_hvac_automation

script:
  living_room_fan_auto:
    sequence:
      - delay: '00:00:01'
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          speed: 'auto'
  master_fan_auto:
    sequence:
      - delay: '00:00:01'
      - service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_fan
          speed: 'auto'
  refresh_wink:
    sequence:
      - service: wink.refresh_state_from_wink
switch:
  - platform: template
    switches:
      fan_override:
        value_template: "{{ is_state('fan.living_room_fan', 'on') }}"
        turn_on:
          - service: fan.turn_on
            data:
              entity_id: fan.living_room_fan
          - service: automation.turn_on
            data:
              entity_id: automation.fan_low_with_hvac_automation, automation.fan_medium_with_hvac_automation
        turn_off:
          - service: fan.turn_off
            data:
              entity_id: fan.living_room_fan
          - service: automation.turn_off
            data:
              entity_id: automation.fan_low_with_hvac_automation, automation.fan_medium_with_hvac_automation
