homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum_kitchen_clean'
    script.susie_clean_kitchen:
      friendly_name: Susie Clean Kitchen
      haaska_name: Susie Clean Kitchen


input_boolean:
  boolean_susie_clean_kitchen:
    initial: off

script:
  susie_clean_kitchen:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_clean_kitchen
      - service: vacuum.send_command
        data:
          entity_id: vacuum.susie
          command: app_zoned_clean
          params: [[25500, 25500, 29500, 28900, 1]]
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is cleaning Kitchen'
