homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum_livingroom_clean'
    script.susie_clean_livingroom:
      friendly_name: Susie Clean Livingroom
      haaska_name: Susie Clean Livingroom


input_boolean:
  boolean_susie_clean_livingroom:
    initial: off

script:
  susie_clean_livingroom:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_clean_livingroom
      - service: vacuum.send_command
        data:
          entity_id: vacuum.susie
          command: app_zoned_clean
          params: [[29500, 25300, 34200, 29750, 1]]
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is cleaning Livingroom'
