homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum_master'
    script.susie_clean_master:
      friendly_name: Susie Clean Master Bedroom
      haaska_name: Susie Clean Master Bedroom

    script.susie_clean_master_door_closed:
      haaska_hidden: true


input_boolean:
  boolean_susie_clean_master:
    initial: off

script:
  susie_clean_master:
    sequence:
      - service: script.turn_on
        entity_id: script.susie_clean_master_door_closed
      - service: script.turn_on
        entity_id: script.susie_clean_master_bath_door_closed
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_clean_master
      - wait_template: "{{ is_state('binary_sensor.door_window_sensor_master_bedroom_door', 'on') }}"
      - wait_template: "{{ is_state('binary_sensor.door_window_sensor_master_bath_door', 'on') }}"
      - service: vacuum.send_command
        data:
          entity_id: vacuum.susie
          command: app_zoned_clean
          params: [[17800, 25200, 23700, 29600, 1]]
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is cleaning Master Bedroom'

  susie_clean_master_door_closed:
    sequence:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_master_bedroom_door
        state: 'off'
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie Cant Clean if Master Bedroom door is closed'

  susie_clean_master_bath_door_closed:
    sequence:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_master_bath_door
        state: 'off'
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie Cant Clean if Master Bath door is closed'
