homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum'
    binary_sensor.susie_docked:
      haaska_hidden: true
      friendly_name: Susie Docked
      icon: mdi:home
    sensor.susie_mode_state:
      haaska_hidden: true
      friendly_name: Susie Mode
    input_boolean.boolean_susie_home:
      friendly_name: Susie Home
      haaska_name: Susie Home
    switch.dock_susie:
      friendly_name: Dock Susie
      haaska_name: Susie Go Home
    script.susie_docked:
      haaska_hidden: true
    script.susie_undocked:
      haaska_hidden: true
    automation.susie_is_docked:
      haaska_hidden: true
    automation.susie_is_returning_home:
      haaska_hidden: true  


group:
  vacuum_card:
    name: Vacuum
    entities:
      - vacuum.susie
      - binary_sensor.susie_docked
      - sensor.susie_mode_state

  input_boolean_vacuum_jobs_card:
    name: Input Boolean Vacuum Mode
    control: hidden
    entities:
      - input_boolean.boolean_susie_home
      - input_boolean.boolean_susie_trash_can
      - input_boolean.boolean_susie_clean_kitchen


vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.12
    token: !secret xiaomi_vacuum_key
    name: 'Susie'

input_boolean:
  boolean_susie_home:
    initial: off

binary_sensor:
  - platform: template
    sensors:
      susie_docked:
        device_class: connectivity
        value_template: '{{ is_state("vacuum.susie", "docked") }}'

sensor:
  - platform: template
    sensors:
      susie_mode_state:
        value_template: >-
          {% if states('input_boolean.boolean_susie_home') == 'on' %}
              Docked
          {% elif states('input_boolean.boolean_susie_trash_can') == 'on' %}
              Trash Can
          {% elif states('input_boolean.boolean_susie_clean_kitchen') == 'on' %}
              Cleaning Kitchen
          {% else %}
              Unknown Do Better
          {% endif %}

switch:
  - platform: template
    switches:
      dock_susie:
        value_template: "{{ is_state('vacuum.susie', 'docked') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.susie_undocked
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.susie_docked

script:
  susie_docked:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_home
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is Already at Home and Docked'

  susie_undocked:
    sequence:
      # - service: tts.google_say
      #   data:
      #     entity_id:
      #       - media_player.ha_speaker
      #       - media_player.master_bedroom_cast
          # message: 'Susie is returning to Dock'
      - service: vacuum.return_to_base
        entity_id: vacuum.susie
      - delay: '00:02:00'
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_home

automation:
  - alias: 'susie_is_docked'
    trigger:
      platform: state
      entity_id: vacuum.susie
      to: 'docked'
    action:
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is docked'
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_home

  - alias: 'susie_is_returning_home'
    trigger:
      platform: state
      entity_id: vacuum.susie
      to: 'returning'
    action:
      - service: tts.google_say
        data_template:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: >
             {% if states('input_boolean.boolean_susie_trash_can') == 'on' %}
                 Susie is going home from trash can
             {% elif states('input_boolean.boolean_susie_clean_kitchen') == 'on' %}
                 Susie is finished cleaning kitchen returning home
             {% else %}
                Unknown Do Better
             {% endif %}
