homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum_kids_hallway'
    script.susie_clean_kids_hallway:
      friendly_name: Susie Clean Kids Hallway
      haaska_name: Susie Clean Kids Hallway


input_boolean:
  boolean_susie_clean_kids_hallway:
    initial: off

script:
  susie_clean_kids_hallway:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_clean_kids_hallway
      - service: vacuum.send_command
        data:
          entity_id: vacuum.susie
          command: app_zoned_clean
          params: [[ 33950, 25200, 37950, 26300, 1]]
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is cleaning kids Hallway'
