homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum'
    binary_sensor.susie_docked:
      haaska_hidden: true
      friendly_name: Susie Docked
      icon: mdi:home
    sensor.susie_mode_state:
      haaska_hidden: true
      friendly_name: Susie Mode
    sensor.susie_mode_error:
      haaska_hidden: true
      friendly_name: Susie Error
    input_boolean.boolean_susie_home:
      friendly_name: Susie Home
      haaska_name: Susie Home
    switch.dock_susie:
      friendly_name: Dock Susie
      haaska_name: Susie Go Home
    script.susie_docked:
      haaska_hidden: true
    script.susie_undocked:
      haaska_hidden: true
    automation.susie_is_docked:
      haaska_hidden: true
    automation.susie_is_returning_home:
      haaska_hidden: true
    automation.susie_error:
      haaska_hidden: true


group:
  vacuum_card:
    name: Vacuum
    entities:
      - vacuum.susie
      - input_select.susie_selection
      - binary_sensor.susie_docked
      - sensor.susie_mode_state
      - sensor.susie_mode_error

  input_boolean_vacuum_jobs_card:
    name: Input Boolean Vacuum Mode
    control: hidden
    entities:
      - input_boolean.boolean_susie_home
      - input_boolean.boolean_susie_trash_can
      - input_boolean.boolean_susie_clean_kitchen
      - input_boolean.boolean_susie_clean_master_hallway
      - input_boolean.boolean_susie_clean_master
      - input_boolean.boolean_susie_clean_livingroom
      - input_boolean.boolean_susie_clean_kids_hallway
      - input_boolean.boolean_susie_clean_ruths_room
      - input_boolean.boolean_susie_clean_kids_bathroom
      - input_boolean.boolean_susie_clean_kids_room

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.12
    token: !secret xiaomi_vacuum_key
    name: 'Susie'

input_select:
  susie_selection:
    initial: 'Select Task'
    name: 'Select Susie Todo:'
    options:
      - Select Task
      - Trash Can
      - Return To Dock
      - Clean Kitchen
      - Clean Master Hallway
      - Clean Master
      - Clean Living Room
      - Clean Kids Hallway
      - Clean Ruths Room
      - Clean Kids Bathroom
      - Clean Kids Room

input_boolean:
  boolean_susie_home:
    initial: off

binary_sensor:
  - platform: template
    sensors:
      susie_docked:
        device_class: connectivity
        value_template: '{{ is_state("vacuum.susie", "docked") }}'

sensor:
  - platform: template
    sensors:
      susie_mode_state:
        value_template: >-
          {% if states('input_boolean.boolean_susie_home') == 'on' %}
              Docked
          {% elif states('input_boolean.boolean_susie_trash_can') == 'on' %}
              Trash Can
          {% elif states('input_boolean.boolean_susie_clean_kitchen') == 'on' %}
              Cleaning Kitchen
          {% elif states('input_boolean.boolean_susie_clean_master_hallway') == 'on' %}
              Cleaning Master Hallway
          {% elif states('input_boolean.boolean_susie_clean_master') == 'on' %}
              Cleaning Master
          {% elif states('input_boolean.boolean_susie_clean_livingroom') == 'on' %}
              Cleaning Livingroom
          {% elif states('input_boolean.boolean_susie_clean_kids_hallway') == 'on' %}
              Cleaning Kids Hallway
          {% elif states('input_boolean.boolean_susie_clean_ruths_room') == 'on' %}
              Cleaning Ruths Room
          {% elif states('input_boolean.boolean_susie_clean_kids_bathroom') == 'on' %}
              Cleaning Kids Bathroom
          {% elif states('input_boolean.boolean_susie_clean_kids_room') == 'on' %}
              Cleaning Kids Room
          {% else %}
              Unknown Do Better
          {% endif %}

  - platform: template
    sensors:
      susie_mode_error:
        value_template: "{{ state_attr('vacuum.susie', 'error') }}"


switch:
  - platform: template
    switches:
      dock_susie:
        value_template: "{{ is_state('vacuum.susie', 'docked') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.susie_undocked
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.susie_docked

script:
  susie_docked:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_home
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is Already at Home and Docked'

  susie_undocked:
    sequence:
      # - service: tts.google_say
      #   data:
      #     entity_id:
      #       - media_player.ha_speaker
      #       - media_player.master_bedroom_cast
          # message: 'Susie is returning to Dock'
      - service: vacuum.return_to_base
        entity_id: vacuum.susie
      - delay: '00:02:00'
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_home

automation:
  - alias: 'susie_is_docked'
    trigger:
      platform: state
      entity_id: vacuum.susie
      to: 'docked'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_home
      - service: input_select.select_option
        entity_id: input_select.susie_selection
        data_template:
          option: 'Select Task'
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is docked'

  - alias: 'susie_is_returning_home'
    trigger:
      platform: state
      entity_id: vacuum.susie
      to: 'returning'
    action:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - service: tts.google_say
        data_template:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: >
             {% if states('input_boolean.boolean_susie_trash_can') == 'on' %}
                 Susie is going home from trash can
             {% elif states('input_boolean.boolean_susie_clean_kitchen') == 'on' %}
                 Susie is finished cleaning kitchen returning home
             {% elif states('input_boolean.boolean_susie_clean_master_hallway') == 'on' %}
                Susie is finished cleaning master hallway returing home
             {% elif states('input_boolean.boolean_susie_clean_master') == 'on' %}
                Susie is finished cleaning master bedroom returing home
             {% elif states('input_boolean.boolean_susie_clean_livingroom') == 'on' %}
                Susie is finished cleaning Livingroom returing home
             {% elif states('input_boolean.boolean_susie_clean_kids_hallway') == 'on' %}
                Susie is finished cleaning Kids Hallway returing home
             {% elif states('input_boolean.boolean_susie_clean_ruths_room') == 'on' %}
                Susie is finished cleaning Ruths Room returing home
             {% elif states('input_boolean.boolean_susie_clean_kids_bathroom') == 'on' %}
                Susie is finished cleaning Kids Bathroom returing home
             {% elif states('input_boolean.boolean_susie_clean_kids_room') == 'on' %}
                Susie is finished cleaning Kids Room returing home
             {% else %}
                Unknown Do Better
             {% endif %}

  - alias: 'susie_error'
    trigger:
      platform: state
      entity_id: sensor.susie_error
      from: 'None'
    action:
      - service: tts.google_say
        data_template:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: "Susie has a error {{states('sensor.susie_error')}}"

  - alias: 'susie_todo'
    trigger:
      platform: state
      entity_id: input_select.susie_selection
      from: 'Select Task'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.susie_selection", "Trash Can") %}
              script.susie_trash_can
            {% elif is_state("input_select.susie_selection", "Return To Dock") %}
              script.susie_undocked
            {% elif is_state("input_select.susie_selection", "Clean Kitchen") %}
              script.susie_clean_kitchen
            {% elif is_state("input_select.susie_selection", "Clean Master Hallway") %}
              script.susie_clean.master_hallway
            {% elif is_state("input_select.susie_selection", "Clean Master") %}
              script.susie_clean_master
            {% elif is_state("input_select.susie_selection", "Clean Livingroom") %}
              script.susie_clean_Livingroom
            {% elif is_state("input_select.susie_selection", "Clean Kids Hallway") %}
              script.susie_clean_kids_hallway
            {% elif is_state("input_select.susie_selection", "Clean Ruths Room") %}
              script.susie_clean_ruths_room
            {% elif is_state("input_select.susie_selection", "Clean Kids Bathroom") %}
              script.susie_clean_kids_bathroom
            {% elif is_state("input_select.susie_selection", "Clean Kids Room") %}
              script.susie_clean_kids_room
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.susie_selection
        data_template:
          option: 'Select Task'
