homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'robot_vacuum_master_hallway'
    script.susie_clean_master_hallway:
      friendly_name: Susie Clean Master Hallway
      haaska_name: Susie Clean Master Hallway


input_boolean:
  boolean_susie_clean_master_hallway:
    initial: off

script:
  susie_clean_master_hallway:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_vacuum_jobs_card
      - service: input_boolean.turn_on
        entity_id: input_boolean.boolean_susie_clean_master_hallway
      - service: vacuum.send_command
        data:
          entity_id: vacuum.susie
          command: app_zoned_clean
          params: [[23600, 25200, 26400, 26250, 1]]
      - service: tts.google_say
        data:
          entity_id:
            - media_player.ha_speaker
            - media_player.master_bedroom_cast
          message: 'Susie is cleaning Master Hallway'
