homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'air_puirfier'
    fan.living_room_purifer:
      friendly_name: Living room Purifer
      haaska_hidden: true
    sensor.living_room_purifer_mode:
      hasska_hidden: true
      friendly_name: Living room Purifer Mode
    sensor.living_room_purifer_temp:
      hasska_hidden: true
      friendly_name: Living Room Temperature
    sensor.living_room_purifer_humd:
      hasska_hidden: true
      friendly_name: Living Room Humidity
      icon: mdi:water-percent
    sensor.living_room_purifer_aqi_current:
      hasska_hidden: true
      friendly_name: Living Room AQI
      icon: mdi:crosshairs
    script.living_room_purifer_led_off:
      haaska_name: Living Room Purifier Led Off
    script.living_room_purifer_led_on:
      haaska_name: Living Room Purifier Led On
    fan.master_bedroom_purifer:
      friendly_name: Master Bedroom Purifer
      haaska_hidden: true
    sensor.master_bdrm_purifer_mode:
      hasska_hidden: true
      friendly_name: Master Bedroom Purifer Mode
    sensor.master_bdrm_purifer_temp:
      hasska_hidden: true
      friendly_name: Master Bedroom Temperature
    sensor.master_bdrm_purifer_humd:
      hasska_hidden: true
      friendly_name: Master Bedroom Humidity
      icon: mdi:water-percent
    sensor.master_bdrm_purifer_aqi_current:
      hasska_hidden: true
      friendly_name: Master Bedroom AQI
      icon: mdi:crosshairs
    script.master_bdrm_purifer_led_off:
      haaska_name: Master Bedroom Purifier Led Off
    script.master_bdrm_purifer_led_on:
      haaska_name: Master Bedroom Purifier Led On

group:
  air_puirfier_card:
   control: hidden
   name: Air Purifer
   entities:
     - fan.living_room_purifer
     - fan.master_bedroom_purifer
     - sensor.house_avg_aqi
     - sensor.living_room_purifer_mode
     - sensor.living_room_purifer_aqi_current
     - sensor.master_bdrm_purifer_mode
     - sensor.master_bdrm_purifer_aqi_current

fan:
  - platform: xiaomi_miio
    host:  192.168.1.60
    token: !secret xiaomi_purifer_lv
    name: Living Room Purifer
  - platform: xiaomi_miio
    host:  192.168.1.62
    token: !secret xiaomi_purifer_mstr_bdrm
    name: Master Bedroom Purifer

sensor:
  - platform: template
    sensors:
      living_room_purifer_mode:
        value_template: '{{ states.fan.living_room_purifer.attributes["mode"] }}'
      living_room_purifer_temp:
        value_template: '{{ states.fan.living_room_purifer.attributes["temperature"] }}'
        unit_of_measurement: '°C'
      living_room_purifer_humd:
        value_template: '{{ states.fan.living_room_purifer.attributes["humidity"] }}'
        unit_of_measurement: '%'
      living_room_purifer_aqi_current:
        value_template: '{{ states.fan.living_room_purifer.attributes["aqi"] }}'
        unit_of_measurement: '%'
      master_bdrm_purifer_mode:
        value_template: '{{ states.fan.master_bedroom_purifer.attributes["mode"] }}'
      master_bdrm_purifer_temp:
        value_template: '{{ states.fan.master_bedroom_purifer.attributes["temperature"] }}'
        unit_of_measurement: '°C'
      master_bdrm_purifer_humd:
        value_template: '{{ states.fan.master_bedroom_purifer.attributes["humidity"] }}'
        unit_of_measurement: '%'
      master_bdrm_purifer_aqi_current:
        value_template: '{{ states.fan.master_bedroom_purifer.attributes["aqi"] }}'
        unit_of_measurement: '%'
  - platform: min_max
    type: mean
    name: House Avg AQI
    entity_ids:
      - sensor.living_room_purifer_aqi_current
      - sensor.master_bdrm_purifer_aqi_current

script:
  living_room_purifer_led_off:
    sequence:
      - service: fan.xiaomi_miio_set_led_off
        entity_id: fan.living_room_purifer
  living_room_purifer_led_on:
    sequence:
      - service: fan.xiaomi_miio_set_led_on
        entity_id: fan.living_room_purifer
  master_bdrm_purifer_led_off:
    sequence:
      - service: fan.xiaomi_miio_set_led_off
        entity_id: fan.master_bedroom_purifer
  master_bdrm_purifer_led_on:
    sequence:
      - service: fan.xiaomi_miio_set_led_on
        entity_id: fan.master_bedroom_purifer
##### service call not working need to open pr
  living_room_purifer_led_dim:
    sequence:
      - service: fan.xiaomi_miio_set_led_brightness
        data:
          entity_id: fan.living_room_purifer
          brightness: 1

automation:
  - alias: 'led_control_xiaomi_purifer'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_home
        to: 'on'
      - platform: state
        entity_id: input_boolean.boolean_sleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.boolean_early_morning
        to: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_boolean.boolean_home", "on") %}
              script.living_room_purifer_led_on
            {% elif is_state("input_boolean.boolean_early_morning", "on") %}
              script.living_room_purifer_led_on
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
              script.living_room_purifer_led_off
            {% else %}
              script.living_room_purifer_led_off
            {% endif %}
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_boolean.boolean_home", "on") %}
              script.master_bdrm_purifer_led_on
            {% elif is_state("input_boolean.boolean_sleep", "on") %}
              script.master_bdrm_purifer_led_off
            {% else %}
              script.master_bdrm_purifer_led_off
            {% endif %}
